namespace DevExpress.Printing.Native.PrintEditor
{
    using System;

    [Flags]
    public enum PrinterAttributes
    {
        PRINTER_ATTRIBUTE_NONE = 0,
        PRINTER_ATTRIBUTE_QUEUED = 1,
        PRINTER_ATTRIBUTE_DIRECT = 2,
        PRINTER_ATTRIBUTE_DEFAULT = 4,
        PRINTER_ATTRIBUTE_SHARED = 8,
        PRINTER_ATTRIBUTE_NETWORK = 0x10,
        PRINTER_ATTRIBUTE_HIDDEN = 0x20,
        PRINTER_ATTRIBUTE_LOCAL = 0x40,
        PRINTER_ATTRIBUTE_ENABLE_DEVQ = 0x80,
        PRINTER_ATTRIBUTE_KEEPPRINTEDJOBS = 0x100,
        PRINTER_ATTRIBUTE_DO_COMPLETE_FIRST = 0x200,
        PRINTER_ATTRIBUTE_WORK_OFFLINE = 0x400,
        PRINTER_ATTRIBUTE_ENABLE_BIDI = 0x800,
        PRINTER_ATTRIBUTE_RAW_ONLY = 0x1000,
        PRINTER_ATTRIBUTE_PUBLISHED = 0x2000,
        PRINTER_ATTRIBUTE_FAX = 0x4000,
        PRINTER_ATTRIBUTE_TS = 0x8000,
        PRINTER_ATTRIBUTE_PUSHED_USER = 0x20000,
        PRINTER_ATTRIBUTE_PUSHED_MACHINE = 0x40000,
        PRINTER_ATTRIBUTE_MACHINE = 0,
        PRINTER_ATTRIBUTE_FRIENDLY_NAME = 0x100000,
        PRINTER_ATTRIBUTE_TS_GENERIC_DRIVER = 0x200000
    }
}

