namespace DevExpress.Mvvm.DataAnnotations
{
    using DevExpress.Mvvm.Native;
    using System;

    public class EnumMemberMetadataBuilderGeneric<T, TBuilder> : MemberMetadataBuilderBase<T, TBuilder, EnumMetadataBuilder<T>> where T: struct where TBuilder: EnumMemberMetadataBuilderGeneric<T, TBuilder>
    {
        internal EnumMemberMetadataBuilderGeneric(MemberMetadataStorage storage, EnumMetadataBuilder<T> parent) : base(storage, parent)
        {
        }

        public TBuilder Description(string description) => 
            base.DescriptionCore(description);

        public TBuilder DisplayName(string name) => 
            base.DisplayNameCore(name);

        public EnumMetadataBuilder<T> EndMember() => 
            base.parent;

        public TBuilder ImageUri(string imageUri) => 
            base.ImageUriCore(imageUri);

        public TBuilder NotAutoGenerated() => 
            base.NotAutoGeneratedCore();
    }
}

