namespace DevExpress.Xpf.Bars
{
    using System;

    public enum BarsStringId
    {
        public const BarsStringId CustomizationMenu_AddOrRemoveItemCaption = BarsStringId.CustomizationMenu_AddOrRemoveItemCaption;,
        public const BarsStringId CustomizationForm_Caption = BarsStringId.CustomizationForm_Caption;,
        public const BarsStringId CustomizationMenu_VisibleItemCaption = BarsStringId.CustomizationMenu_VisibleItemCaption;,
        public const BarsStringId CustomizationMenu_BeginGroupItemCaption = BarsStringId.CustomizationMenu_BeginGroupItemCaption;,
        public const BarsStringId CustomizationMenu_DeleteItemCaption = BarsStringId.CustomizationMenu_DeleteItemCaption;,
        public const BarsStringId CustomizationMenu_ResetItemCaption = BarsStringId.CustomizationMenu_ResetItemCaption;,
        public const BarsStringId CustomizationMenu_LinkItemCaption = BarsStringId.CustomizationMenu_LinkItemCaption;,
        public const BarsStringId CustomizationMenu_DisplayModeItemCaption = BarsStringId.CustomizationMenu_DisplayModeItemCaption;,
        public const BarsStringId BarItemDisplayMode_Default = BarsStringId.BarItemDisplayMode_Default;,
        public const BarsStringId BarItemDisplayMode_Content = BarsStringId.BarItemDisplayMode_Content;,
        public const BarsStringId BarItemDisplayMode_ContentAndGlyph = BarsStringId.BarItemDisplayMode_ContentAndGlyph;,
        public const BarsStringId CustomizationMenu_GlyphAlignmentItemCaption = BarsStringId.CustomizationMenu_GlyphAlignmentItemCaption;,
        public const BarsStringId CustomizationMenu_AlignmentItemCaption = BarsStringId.CustomizationMenu_AlignmentItemCaption;,
        public const BarsStringId CustomizationMenu_GlyphSizeItemCaption = BarsStringId.CustomizationMenu_GlyphSizeItemCaption;,
        public const BarsStringId Dock_Left = BarsStringId.Dock_Left;,
        public const BarsStringId Dock_Right = BarsStringId.Dock_Right;,
        public const BarsStringId Dock_Top = BarsStringId.Dock_Top;,
        public const BarsStringId Dock_Bottom = BarsStringId.Dock_Bottom;,
        public const BarsStringId BarItemAlignment_Default = BarsStringId.BarItemAlignment_Default;,
        public const BarsStringId BarItemAlignment_Near = BarsStringId.BarItemAlignment_Near;,
        public const BarsStringId BarItemAlignment_Far = BarsStringId.BarItemAlignment_Far;,
        public const BarsStringId GlyphSize_Default = BarsStringId.GlyphSize_Default;,
        public const BarsStringId GlyphSize_Small = BarsStringId.GlyphSize_Small;,
        public const BarsStringId GlyphSize_Large = BarsStringId.GlyphSize_Large;,
        public const BarsStringId GalleryControlFilterMenu_ShowAllItemCaption = BarsStringId.GalleryControlFilterMenu_ShowAllItemCaption;,
        public const BarsStringId BarManagerCategory_UnassignedCategoryCaption = BarsStringId.BarManagerCategory_UnassignedCategoryCaption;,
        public const BarsStringId BarManagerCategory_AllItemsCategoryCaption = BarsStringId.BarManagerCategory_AllItemsCategoryCaption;,
        public const BarsStringId ToolbarsCustomizationControl_EditorWindowCaption = BarsStringId.ToolbarsCustomizationControl_EditorWindowCaption;,
        public const BarsStringId LinkListItem_CustomizationItemCaption = BarsStringId.LinkListItem_CustomizationItemCaption;,
        public const BarsStringId ToolbarListItem_CustomizationItemCaption = BarsStringId.ToolbarListItem_CustomizationItemCaption;,
        public const BarsStringId ToolbarCaptionEditor_Caption = BarsStringId.ToolbarCaptionEditor_Caption;,
        public const BarsStringId Ok = BarsStringId.Ok;,
        public const BarsStringId Cancel = BarsStringId.Cancel;,
        public const BarsStringId New = BarsStringId.New;,
        public const BarsStringId Rename = BarsStringId.Rename;,
        public const BarsStringId Delete = BarsStringId.Delete;,
        public const BarsStringId Close = BarsStringId.Close;,
        public const BarsStringId OptionsControl_IconsGroupCaption = BarsStringId.OptionsControl_IconsGroupCaption;,
        public const BarsStringId OptionsControl_ScreenTipsGroupCaption = BarsStringId.OptionsControl_ScreenTipsGroupCaption;,
        public const BarsStringId OptionsControl_LargeIconsInToolbarsCaption = BarsStringId.OptionsControl_LargeIconsInToolbarsCaption;,
        public const BarsStringId OptionsControl_LargeIconsInMenuCaption = BarsStringId.OptionsControl_LargeIconsInMenuCaption;,
        public const BarsStringId OptionsControl_ShowScreenTipsOnToolbarsCaption = BarsStringId.OptionsControl_ShowScreenTipsOnToolbarsCaption;,
        public const BarsStringId OptionsControl_ShowShortcutKeysOnScreenTipsCaption = BarsStringId.OptionsControl_ShowShortcutKeysOnScreenTipsCaption;,
        public const BarsStringId CommandsCustomizationControl_CategoriesListCaption = BarsStringId.CommandsCustomizationControl_CategoriesListCaption;,
        public const BarsStringId CommandsCustomizationControl_CommandsListCaption = BarsStringId.CommandsCustomizationControl_CommandsListCaption;,
        public const BarsStringId CommandsCustomizationControl_DescriptionCaption = BarsStringId.CommandsCustomizationControl_DescriptionCaption;,
        public const BarsStringId CustomizationControl_ToolbarsTabCaption = BarsStringId.CustomizationControl_ToolbarsTabCaption;,
        public const BarsStringId CustomizationControl_CommandsTabCaption = BarsStringId.CustomizationControl_CommandsTabCaption;,
        public const BarsStringId CustomizationControl_OptionsTabCaption = BarsStringId.CustomizationControl_OptionsTabCaption;,
        public const BarsStringId ToolbarsCustomizationControl_ToolbarsListCaption = BarsStringId.ToolbarsCustomizationControl_ToolbarsListCaption;,
        public const BarsStringId HistoryItem_Undo = BarsStringId.HistoryItem_Undo;,
        public const BarsStringId HistoryItem_Redo = BarsStringId.HistoryItem_Redo;,
        public const BarsStringId HistoryItem_UndoSingleAction = BarsStringId.HistoryItem_UndoSingleAction;,
        public const BarsStringId HistoryItem_RedoSingleAction = BarsStringId.HistoryItem_RedoSingleAction;,
        public const BarsStringId HistoryItem_UndoMultipleFormat = BarsStringId.HistoryItem_UndoMultipleFormat;,
        public const BarsStringId HistoryItem_RedoMultipleFormat = BarsStringId.HistoryItem_RedoMultipleFormat;,
        public const BarsStringId BarItemSearchControl_NoResult = BarsStringId.BarItemSearchControl_NoResult;,
        public const BarsStringId BarItemSearchControl_BestMatch = BarsStringId.BarItemSearchControl_BestMatch;,
        public const BarsStringId BarItemSearchControl_DefaultCategory = BarsStringId.BarItemSearchControl_DefaultCategory;,
        public const BarsStringId BarItemSearchControl_NullText = BarsStringId.BarItemSearchControl_NullText;
    }
}

