namespace DevExpress.Xpf.Grid.Native
{
    using DevExpress.Mvvm.UI.Native.ViewGenerator.Model;
    using System;
    using System.Windows;

    public class DesignTimeColumnPropertiesPopulator : RuntimeColumnPropertiesPopulator
    {
        public DesignTimeColumnPropertiesPopulator(IModelItem columnModel, GenerateColumnWrapper wrapper) : base(columnModel, wrapper)
        {
        }

        protected override bool IsAutoGeneratedColumn() => 
            false;

        protected override bool IsSmartColumn() => 
            true;

        protected override void SafeSetValueIsNotSet(IModelItem modelItem, DependencyProperty property, object value)
        {
            modelItem.Properties[property.Name].SetValue(value);
        }

        protected override void SetValueIfNotSet(IModelItem modelItem, DependencyProperty property, object value)
        {
            modelItem.Properties[property.Name].SetValue(value);
        }
    }
}

