namespace DevExpress.Office.Drawing
{
    using DevExpress.Office;
    using DevExpress.Office.Layout;
    using DevExpress.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Reflection;

    public abstract class FontCache : IDisposable
    {
        private bool isDisposed;
        private FontInfoMeasurer measurer;
        private Dictionary<long, int> indexHash;
        private Dictionary<string, int> charsets;
        private List<FontInfo> fontInfoList;
        private static readonly Dictionary<string, FontCharacterSet> nameToCharacterSetMap = new Dictionary<string, FontCharacterSet>();
        private static readonly ConcurrentDictionary<string, FontCapabilitiesInfo> fontCapabilitiesMap = CreateFontCapabilitiesMap();
        protected static bool nameToCharacterMapPopulated;
        private readonly DocumentLayoutUnitConverter unitConverter;
        private readonly bool allowCjkCorrection;

        protected FontCache(DocumentLayoutUnitConverter unitConverter, bool allowCjkCorrection)
        {
            Guard.ArgumentNotNull(unitConverter, "unitConverter");
            this.unitConverter = unitConverter;
            this.indexHash = new Dictionary<long, int>();
            this.charsets = new Dictionary<string, int>(StringExtensions.ComparerInvariantCultureIgnoreCase);
            this.fontInfoList = new List<FontInfo>();
            this.allowCjkCorrection = allowCjkCorrection;
        }

        public virtual int CalcFontIndex(string fontName, int doubleFontSize, bool fontBold, bool fontItalic, CharacterFormattingScript script, bool fontStrikeout, bool fontUnderline) => 
            this.CalcFontIndex(fontName, doubleFontSize, fontBold, fontItalic, script, fontStrikeout, fontUnderline, 0);

        public int CalcFontIndex(string fontName, int doubleFontSize, bool fontBold, bool fontItalic, CharacterFormattingScript script, bool fontStrikeout, bool fontUnderline, int textRotation)
        {
            int num = this.unitConverter.PointsToFontUnits(doubleFontSize);
            int baseFontIndex = this.CalcNormalFontIndex(fontName, num, fontBold, fontItalic, fontStrikeout, fontUnderline, textRotation);
            if (script == CharacterFormattingScript.Normal)
            {
                return baseFontIndex;
            }
            int num3 = (script != CharacterFormattingScript.Subscript) ? this.CalcSuperscriptFontSize(baseFontIndex) : this.CalcSubscriptFontSize(baseFontIndex);
            return this.CalcFontIndexCore(fontName, num3 * 2, num, fontBold, fontItalic, script, fontStrikeout, fontUnderline, textRotation, this[baseFontIndex]);
        }

        protected internal virtual int CalcFontIndexCore(string fontName, int doubleFontSize, int doubleBaselineFontSize, bool fontBold, bool fontItalic, CharacterFormattingScript script, bool fontStrikeout, bool fontUnderline, int textRotation, FontInfo baselineFontInfo)
        {
            int num2;
            long key = this.CalcHash(fontName, doubleFontSize, doubleBaselineFontSize, fontBold, fontItalic, script, fontStrikeout, fontUnderline, textRotation);
            if (this.indexHash.TryGetValue(key, out num2))
            {
                return num2;
            }
            FontCache cache = this;
            lock (cache)
            {
                return (this.indexHash.TryGetValue(key, out num2) ? num2 : this.CreateFontInfo(key, fontName, doubleFontSize, fontBold, fontItalic, fontStrikeout, fontUnderline, textRotation, baselineFontInfo));
            }
        }

        protected internal virtual long CalcHash(string fontName, int doubleFontSize, int doubleBaselineFontSize, bool bold, bool italic, CharacterFormattingScript script, bool strikeout, bool underline, int textRotation)
        {
            long hashCode = fontName.ToLower().GetHashCode();
            long num2 = doubleFontSize + doubleBaselineFontSize;
            int num3 = ((((((textRotation + 90) << 6) | (underline ? 0x20 : 0)) | (strikeout ? 0x10 : 0)) | (italic ? 8 : 0)) | (bold ? 4 : 0)) | ((int) script);
            return (((hashCode << 0x20) + (num2 << 14)) + num3);
        }

        public int CalcNormalFontIndex(string fontName, int doubleFontSize, bool fontBold, bool fontItalic, bool fontStrikeout, bool fontUnderline, int textRotation) => 
            this.CalcFontIndexCore(fontName, doubleFontSize, doubleFontSize, fontBold, fontItalic, CharacterFormattingScript.Normal, fontStrikeout, fontUnderline, textRotation, null);

        protected internal int CalcSubscriptFontSize(int baseFontIndex) => 
            (int) Math.Round((double) (this.fontInfoList[baseFontIndex].SubscriptSize.Height * this.unitConverter.FontSizeScale));

        protected internal int CalcSuperscriptFontSize(int baseFontIndex) => 
            (int) Math.Round((double) (this.fontInfoList[baseFontIndex].SuperscriptSize.Height * this.unitConverter.FontSizeScale));

        private static ConcurrentDictionary<string, FontCapabilitiesInfo> CreateFontCapabilitiesMap()
        {
            ConcurrentDictionary<string, FontCapabilitiesInfo> dictionary = new ConcurrentDictionary<string, FontCapabilitiesInfo>(StringComparer.InvariantCultureIgnoreCase);
            FontCapabilitiesInfo info1 = new FontCapabilitiesInfo();
            info1.IsCjk = false;
            info1.IsComplexScript = false;
            dictionary["Agency FB"] = info1;
            FontCapabilitiesInfo info2 = new FontCapabilitiesInfo();
            info2.IsCjk = false;
            info2.IsComplexScript = true;
            dictionary["Aharoni"] = info2;
            FontCapabilitiesInfo info3 = new FontCapabilitiesInfo();
            info3.IsCjk = false;
            info3.IsComplexScript = true;
            dictionary["Aldhabi"] = info3;
            FontCapabilitiesInfo info4 = new FontCapabilitiesInfo();
            info4.IsCjk = false;
            info4.IsComplexScript = true;
            dictionary["Alef"] = info4;
            FontCapabilitiesInfo info5 = new FontCapabilitiesInfo();
            info5.IsCjk = false;
            info5.IsComplexScript = false;
            dictionary["Algerian"] = info5;
            FontCapabilitiesInfo info6 = new FontCapabilitiesInfo();
            info6.IsCjk = false;
            info6.IsComplexScript = true;
            dictionary["Amiri"] = info6;
            FontCapabilitiesInfo info7 = new FontCapabilitiesInfo();
            info7.IsCjk = false;
            info7.IsComplexScript = true;
            dictionary["Amiri Quran"] = info7;
            FontCapabilitiesInfo info8 = new FontCapabilitiesInfo();
            info8.IsCjk = false;
            info8.IsComplexScript = true;
            dictionary["Andalus"] = info8;
            FontCapabilitiesInfo info9 = new FontCapabilitiesInfo();
            info9.IsCjk = false;
            info9.IsComplexScript = false;
            dictionary["Angsana New"] = info9;
            FontCapabilitiesInfo info10 = new FontCapabilitiesInfo();
            info10.IsCjk = false;
            info10.IsComplexScript = false;
            dictionary["AngsanaUPC"] = info10;
            FontCapabilitiesInfo info11 = new FontCapabilitiesInfo();
            info11.IsCjk = false;
            info11.IsComplexScript = false;
            dictionary["Aparajita"] = info11;
            FontCapabilitiesInfo info12 = new FontCapabilitiesInfo();
            info12.IsCjk = false;
            info12.IsComplexScript = true;
            dictionary["Arabic Typesetting"] = info12;
            FontCapabilitiesInfo info13 = new FontCapabilitiesInfo();
            info13.IsCjk = false;
            info13.IsComplexScript = true;
            dictionary["Arial"] = info13;
            FontCapabilitiesInfo info14 = new FontCapabilitiesInfo();
            info14.IsCjk = false;
            info14.IsComplexScript = false;
            dictionary["Arial Black"] = info14;
            FontCapabilitiesInfo info15 = new FontCapabilitiesInfo();
            info15.IsCjk = false;
            info15.IsComplexScript = false;
            dictionary["Arial Narrow"] = info15;
            FontCapabilitiesInfo info16 = new FontCapabilitiesInfo();
            info16.IsCjk = false;
            info16.IsComplexScript = false;
            dictionary["Arial Rounded MT Bold"] = info16;
            FontCapabilitiesInfo info17 = new FontCapabilitiesInfo();
            info17.IsCjk = true;
            info17.IsComplexScript = true;
            dictionary["Arial Unicode MS"] = info17;
            FontCapabilitiesInfo info18 = new FontCapabilitiesInfo();
            info18.IsCjk = false;
            info18.IsComplexScript = false;
            dictionary["Baskerville Old Face"] = info18;
            FontCapabilitiesInfo info19 = new FontCapabilitiesInfo();
            info19.IsCjk = true;
            info19.IsComplexScript = false;
            dictionary["Batang"] = info19;
            FontCapabilitiesInfo info20 = new FontCapabilitiesInfo();
            info20.IsCjk = true;
            info20.IsComplexScript = false;
            dictionary["BatangChe"] = info20;
            FontCapabilitiesInfo info21 = new FontCapabilitiesInfo();
            info21.IsCjk = false;
            info21.IsComplexScript = false;
            dictionary["Bauhaus 93"] = info21;
            FontCapabilitiesInfo info22 = new FontCapabilitiesInfo();
            info22.IsCjk = false;
            info22.IsComplexScript = false;
            dictionary["Bell MT"] = info22;
            FontCapabilitiesInfo info23 = new FontCapabilitiesInfo();
            info23.IsCjk = false;
            info23.IsComplexScript = false;
            dictionary["Berlin Sans FB"] = info23;
            FontCapabilitiesInfo info24 = new FontCapabilitiesInfo();
            info24.IsCjk = false;
            info24.IsComplexScript = false;
            dictionary["Berlin Sans FB Demi"] = info24;
            FontCapabilitiesInfo info25 = new FontCapabilitiesInfo();
            info25.IsCjk = false;
            info25.IsComplexScript = false;
            dictionary["Bernard MT Condensed"] = info25;
            FontCapabilitiesInfo info26 = new FontCapabilitiesInfo();
            info26.IsCjk = false;
            info26.IsComplexScript = false;
            dictionary["Blackadder ITC"] = info26;
            FontCapabilitiesInfo info27 = new FontCapabilitiesInfo();
            info27.IsCjk = false;
            info27.IsComplexScript = false;
            dictionary["Bodoni MT"] = info27;
            FontCapabilitiesInfo info28 = new FontCapabilitiesInfo();
            info28.IsCjk = false;
            info28.IsComplexScript = false;
            dictionary["Bodoni MT Black"] = info28;
            FontCapabilitiesInfo info29 = new FontCapabilitiesInfo();
            info29.IsCjk = false;
            info29.IsComplexScript = false;
            dictionary["Bodoni MT Condensed"] = info29;
            FontCapabilitiesInfo info30 = new FontCapabilitiesInfo();
            info30.IsCjk = false;
            info30.IsComplexScript = false;
            dictionary["Bodoni MT Poster Compressed"] = info30;
            FontCapabilitiesInfo info31 = new FontCapabilitiesInfo();
            info31.IsCjk = false;
            info31.IsComplexScript = false;
            dictionary["Book Antiqua"] = info31;
            FontCapabilitiesInfo info32 = new FontCapabilitiesInfo();
            info32.IsCjk = false;
            info32.IsComplexScript = false;
            dictionary["Bookman Old Style"] = info32;
            FontCapabilitiesInfo info33 = new FontCapabilitiesInfo();
            info33.IsCjk = false;
            info33.IsComplexScript = false;
            dictionary["Bookshelf Symbol 7"] = info33;
            FontCapabilitiesInfo info34 = new FontCapabilitiesInfo();
            info34.IsCjk = false;
            info34.IsComplexScript = false;
            dictionary["Bradley Hand ITC"] = info34;
            FontCapabilitiesInfo info35 = new FontCapabilitiesInfo();
            info35.IsCjk = false;
            info35.IsComplexScript = false;
            dictionary["Britannic Bold"] = info35;
            FontCapabilitiesInfo info36 = new FontCapabilitiesInfo();
            info36.IsCjk = false;
            info36.IsComplexScript = false;
            dictionary["Broadway"] = info36;
            FontCapabilitiesInfo info37 = new FontCapabilitiesInfo();
            info37.IsCjk = false;
            info37.IsComplexScript = false;
            dictionary["Browallia New"] = info37;
            FontCapabilitiesInfo info38 = new FontCapabilitiesInfo();
            info38.IsCjk = false;
            info38.IsComplexScript = false;
            dictionary["BrowalliaUPC"] = info38;
            FontCapabilitiesInfo info39 = new FontCapabilitiesInfo();
            info39.IsCjk = false;
            info39.IsComplexScript = false;
            dictionary["Brush Script MT"] = info39;
            FontCapabilitiesInfo info40 = new FontCapabilitiesInfo();
            info40.IsCjk = false;
            info40.IsComplexScript = false;
            dictionary["Buxton Sketch"] = info40;
            FontCapabilitiesInfo info41 = new FontCapabilitiesInfo();
            info41.IsCjk = false;
            info41.IsComplexScript = false;
            dictionary["Caladea"] = info41;
            FontCapabilitiesInfo info42 = new FontCapabilitiesInfo();
            info42.IsCjk = false;
            info42.IsComplexScript = false;
            dictionary["Calibri"] = info42;
            FontCapabilitiesInfo info43 = new FontCapabilitiesInfo();
            info43.IsCjk = false;
            info43.IsComplexScript = false;
            dictionary["Calibri Light"] = info43;
            FontCapabilitiesInfo info44 = new FontCapabilitiesInfo();
            info44.IsCjk = false;
            info44.IsComplexScript = false;
            dictionary["Californian FB"] = info44;
            FontCapabilitiesInfo info45 = new FontCapabilitiesInfo();
            info45.IsCjk = false;
            info45.IsComplexScript = false;
            dictionary["Calisto MT"] = info45;
            FontCapabilitiesInfo info46 = new FontCapabilitiesInfo();
            info46.IsCjk = false;
            info46.IsComplexScript = false;
            dictionary["Cambria"] = info46;
            FontCapabilitiesInfo info47 = new FontCapabilitiesInfo();
            info47.IsCjk = false;
            info47.IsComplexScript = false;
            dictionary["Cambria Math"] = info47;
            FontCapabilitiesInfo info48 = new FontCapabilitiesInfo();
            info48.IsCjk = false;
            info48.IsComplexScript = false;
            dictionary["Candara"] = info48;
            FontCapabilitiesInfo info49 = new FontCapabilitiesInfo();
            info49.IsCjk = false;
            info49.IsComplexScript = false;
            dictionary["Carlito"] = info49;
            FontCapabilitiesInfo info50 = new FontCapabilitiesInfo();
            info50.IsCjk = false;
            info50.IsComplexScript = false;
            dictionary["Castellar"] = info50;
            FontCapabilitiesInfo info51 = new FontCapabilitiesInfo();
            info51.IsCjk = false;
            info51.IsComplexScript = false;
            dictionary["Centaur"] = info51;
            FontCapabilitiesInfo info52 = new FontCapabilitiesInfo();
            info52.IsCjk = false;
            info52.IsComplexScript = false;
            dictionary["Century"] = info52;
            FontCapabilitiesInfo info53 = new FontCapabilitiesInfo();
            info53.IsCjk = false;
            info53.IsComplexScript = false;
            dictionary["Century Gothic"] = info53;
            FontCapabilitiesInfo info54 = new FontCapabilitiesInfo();
            info54.IsCjk = false;
            info54.IsComplexScript = false;
            dictionary["Century Schoolbook"] = info54;
            FontCapabilitiesInfo info55 = new FontCapabilitiesInfo();
            info55.IsCjk = false;
            info55.IsComplexScript = false;
            dictionary["Chiller"] = info55;
            FontCapabilitiesInfo info56 = new FontCapabilitiesInfo();
            info56.IsCjk = false;
            info56.IsComplexScript = false;
            dictionary["Colonna MT"] = info56;
            FontCapabilitiesInfo info57 = new FontCapabilitiesInfo();
            info57.IsCjk = false;
            info57.IsComplexScript = false;
            dictionary["Comic Sans MS"] = info57;
            FontCapabilitiesInfo info58 = new FontCapabilitiesInfo();
            info58.IsCjk = false;
            info58.IsComplexScript = false;
            dictionary["Consolas"] = info58;
            FontCapabilitiesInfo info59 = new FontCapabilitiesInfo();
            info59.IsCjk = false;
            info59.IsComplexScript = false;
            dictionary["Constantia"] = info59;
            FontCapabilitiesInfo info60 = new FontCapabilitiesInfo();
            info60.IsCjk = false;
            info60.IsComplexScript = false;
            dictionary["Cooper Black"] = info60;
            FontCapabilitiesInfo info61 = new FontCapabilitiesInfo();
            info61.IsCjk = false;
            info61.IsComplexScript = false;
            dictionary["Copperplate Gothic Bold"] = info61;
            FontCapabilitiesInfo info62 = new FontCapabilitiesInfo();
            info62.IsCjk = false;
            info62.IsComplexScript = false;
            dictionary["Copperplate Gothic Light"] = info62;
            FontCapabilitiesInfo info63 = new FontCapabilitiesInfo();
            info63.IsCjk = false;
            info63.IsComplexScript = false;
            dictionary["Corbel"] = info63;
            FontCapabilitiesInfo info64 = new FontCapabilitiesInfo();
            info64.IsCjk = false;
            info64.IsComplexScript = false;
            dictionary["Cordia New"] = info64;
            FontCapabilitiesInfo info65 = new FontCapabilitiesInfo();
            info65.IsCjk = false;
            info65.IsComplexScript = false;
            dictionary["CordiaUPC"] = info65;
            FontCapabilitiesInfo info66 = new FontCapabilitiesInfo();
            info66.IsCjk = false;
            info66.IsComplexScript = true;
            dictionary["Courier New"] = info66;
            FontCapabilitiesInfo info67 = new FontCapabilitiesInfo();
            info67.IsCjk = false;
            info67.IsComplexScript = false;
            dictionary["Curlz MT"] = info67;
            FontCapabilitiesInfo info68 = new FontCapabilitiesInfo();
            info68.IsCjk = false;
            info68.IsComplexScript = false;
            dictionary["DaunPenh"] = info68;
            FontCapabilitiesInfo info69 = new FontCapabilitiesInfo();
            info69.IsCjk = false;
            info69.IsComplexScript = true;
            dictionary["David"] = info69;
            FontCapabilitiesInfo info70 = new FontCapabilitiesInfo();
            info70.IsCjk = false;
            info70.IsComplexScript = true;
            dictionary["David CLM"] = info70;
            FontCapabilitiesInfo info71 = new FontCapabilitiesInfo();
            info71.IsCjk = false;
            info71.IsComplexScript = true;
            dictionary["David Libre"] = info71;
            FontCapabilitiesInfo info72 = new FontCapabilitiesInfo();
            info72.IsCjk = true;
            info72.IsComplexScript = false;
            dictionary["DejaVu Math TeX Gyre"] = info72;
            FontCapabilitiesInfo info73 = new FontCapabilitiesInfo();
            info73.IsCjk = false;
            info73.IsComplexScript = true;
            dictionary["DejaVu Sans"] = info73;
            FontCapabilitiesInfo info74 = new FontCapabilitiesInfo();
            info74.IsCjk = false;
            info74.IsComplexScript = true;
            dictionary["DejaVu Sans Condensed"] = info74;
            FontCapabilitiesInfo info75 = new FontCapabilitiesInfo();
            info75.IsCjk = false;
            info75.IsComplexScript = true;
            dictionary["DejaVu Sans Light"] = info75;
            FontCapabilitiesInfo info76 = new FontCapabilitiesInfo();
            info76.IsCjk = false;
            info76.IsComplexScript = true;
            dictionary["DejaVu Sans Mono"] = info76;
            FontCapabilitiesInfo info77 = new FontCapabilitiesInfo();
            info77.IsCjk = false;
            info77.IsComplexScript = false;
            dictionary["DejaVu Serif"] = info77;
            FontCapabilitiesInfo info78 = new FontCapabilitiesInfo();
            info78.IsCjk = false;
            info78.IsComplexScript = false;
            dictionary["DejaVu Serif Condensed"] = info78;
            FontCapabilitiesInfo info79 = new FontCapabilitiesInfo();
            info79.IsCjk = true;
            info79.IsComplexScript = false;
            dictionary["DengXian"] = info79;
            FontCapabilitiesInfo info80 = new FontCapabilitiesInfo();
            info80.IsCjk = true;
            info80.IsComplexScript = false;
            dictionary["DFKai-SB"] = info80;
            FontCapabilitiesInfo info81 = new FontCapabilitiesInfo();
            info81.IsCjk = false;
            info81.IsComplexScript = false;
            dictionary["DilleniaUPC"] = info81;
            FontCapabilitiesInfo info82 = new FontCapabilitiesInfo();
            info82.IsCjk = false;
            info82.IsComplexScript = false;
            dictionary["DokChampa"] = info82;
            FontCapabilitiesInfo info83 = new FontCapabilitiesInfo();
            info83.IsCjk = true;
            info83.IsComplexScript = false;
            dictionary["Dotum"] = info83;
            FontCapabilitiesInfo info84 = new FontCapabilitiesInfo();
            info84.IsCjk = true;
            info84.IsComplexScript = false;
            dictionary["DotumChe"] = info84;
            FontCapabilitiesInfo info85 = new FontCapabilitiesInfo();
            info85.IsCjk = false;
            info85.IsComplexScript = false;
            dictionary["Ebrima"] = info85;
            FontCapabilitiesInfo info86 = new FontCapabilitiesInfo();
            info86.IsCjk = false;
            info86.IsComplexScript = false;
            dictionary["Edwardian Script ITC"] = info86;
            FontCapabilitiesInfo info87 = new FontCapabilitiesInfo();
            info87.IsCjk = false;
            info87.IsComplexScript = false;
            dictionary["Elephant"] = info87;
            FontCapabilitiesInfo info88 = new FontCapabilitiesInfo();
            info88.IsCjk = true;
            info88.IsComplexScript = false;
            dictionary["EmojiOne Color"] = info88;
            FontCapabilitiesInfo info89 = new FontCapabilitiesInfo();
            info89.IsCjk = false;
            info89.IsComplexScript = false;
            dictionary["Engravers MT"] = info89;
            FontCapabilitiesInfo info90 = new FontCapabilitiesInfo();
            info90.IsCjk = false;
            info90.IsComplexScript = false;
            dictionary["Eras Bold ITC"] = info90;
            FontCapabilitiesInfo info91 = new FontCapabilitiesInfo();
            info91.IsCjk = false;
            info91.IsComplexScript = false;
            dictionary["Eras Demi ITC"] = info91;
            FontCapabilitiesInfo info92 = new FontCapabilitiesInfo();
            info92.IsCjk = false;
            info92.IsComplexScript = false;
            dictionary["Eras Light ITC"] = info92;
            FontCapabilitiesInfo info93 = new FontCapabilitiesInfo();
            info93.IsCjk = false;
            info93.IsComplexScript = false;
            dictionary["Eras Medium ITC"] = info93;
            FontCapabilitiesInfo info94 = new FontCapabilitiesInfo();
            info94.IsCjk = false;
            info94.IsComplexScript = true;
            dictionary["Estrangelo Edessa"] = info94;
            FontCapabilitiesInfo info95 = new FontCapabilitiesInfo();
            info95.IsCjk = false;
            info95.IsComplexScript = false;
            dictionary["EucrosiaUPC"] = info95;
            FontCapabilitiesInfo info96 = new FontCapabilitiesInfo();
            info96.IsCjk = true;
            info96.IsComplexScript = false;
            dictionary["EUDC"] = info96;
            FontCapabilitiesInfo info97 = new FontCapabilitiesInfo();
            info97.IsCjk = false;
            info97.IsComplexScript = false;
            dictionary["Euphemia"] = info97;
            FontCapabilitiesInfo info98 = new FontCapabilitiesInfo();
            info98.IsCjk = true;
            info98.IsComplexScript = false;
            dictionary["FangSong"] = info98;
            FontCapabilitiesInfo info99 = new FontCapabilitiesInfo();
            info99.IsCjk = false;
            info99.IsComplexScript = false;
            dictionary["Felix Titling"] = info99;
            FontCapabilitiesInfo info100 = new FontCapabilitiesInfo();
            info100.IsCjk = false;
            info100.IsComplexScript = false;
            dictionary["Footlight MT Light"] = info100;
            FontCapabilitiesInfo info101 = new FontCapabilitiesInfo();
            info101.IsCjk = false;
            info101.IsComplexScript = false;
            dictionary["Forte"] = info101;
            FontCapabilitiesInfo info102 = new FontCapabilitiesInfo();
            info102.IsCjk = false;
            info102.IsComplexScript = true;
            dictionary["Frank Ruehl CLM"] = info102;
            FontCapabilitiesInfo info103 = new FontCapabilitiesInfo();
            info103.IsCjk = false;
            info103.IsComplexScript = true;
            dictionary["Frank Ruhl Hofshi"] = info103;
            FontCapabilitiesInfo info104 = new FontCapabilitiesInfo();
            info104.IsCjk = false;
            info104.IsComplexScript = false;
            dictionary["Franklin Gothic Book"] = info104;
            FontCapabilitiesInfo info105 = new FontCapabilitiesInfo();
            info105.IsCjk = false;
            info105.IsComplexScript = false;
            dictionary["Franklin Gothic Demi"] = info105;
            FontCapabilitiesInfo info106 = new FontCapabilitiesInfo();
            info106.IsCjk = false;
            info106.IsComplexScript = false;
            dictionary["Franklin Gothic Demi Cond"] = info106;
            FontCapabilitiesInfo info107 = new FontCapabilitiesInfo();
            info107.IsCjk = false;
            info107.IsComplexScript = false;
            dictionary["Franklin Gothic Heavy"] = info107;
            FontCapabilitiesInfo info108 = new FontCapabilitiesInfo();
            info108.IsCjk = false;
            info108.IsComplexScript = false;
            dictionary["Franklin Gothic Medium"] = info108;
            FontCapabilitiesInfo info109 = new FontCapabilitiesInfo();
            info109.IsCjk = false;
            info109.IsComplexScript = false;
            dictionary["Franklin Gothic Medium Cond"] = info109;
            FontCapabilitiesInfo info110 = new FontCapabilitiesInfo();
            info110.IsCjk = false;
            info110.IsComplexScript = true;
            dictionary["FrankRuehl"] = info110;
            FontCapabilitiesInfo info111 = new FontCapabilitiesInfo();
            info111.IsCjk = false;
            info111.IsComplexScript = false;
            dictionary["FreesiaUPC"] = info111;
            FontCapabilitiesInfo info112 = new FontCapabilitiesInfo();
            info112.IsCjk = false;
            info112.IsComplexScript = false;
            dictionary["Freestyle Script"] = info112;
            FontCapabilitiesInfo info113 = new FontCapabilitiesInfo();
            info113.IsCjk = false;
            info113.IsComplexScript = false;
            dictionary["French Script MT"] = info113;
            FontCapabilitiesInfo info114 = new FontCapabilitiesInfo();
            info114.IsCjk = false;
            info114.IsComplexScript = false;
            dictionary["Gabriola"] = info114;
            FontCapabilitiesInfo info115 = new FontCapabilitiesInfo();
            info115.IsCjk = false;
            info115.IsComplexScript = false;
            dictionary["Gadugi"] = info115;
            FontCapabilitiesInfo info116 = new FontCapabilitiesInfo();
            info116.IsCjk = false;
            info116.IsComplexScript = false;
            dictionary["Garamond"] = info116;
            FontCapabilitiesInfo info117 = new FontCapabilitiesInfo();
            info117.IsCjk = false;
            info117.IsComplexScript = false;
            dictionary["Gautami"] = info117;
            FontCapabilitiesInfo info118 = new FontCapabilitiesInfo();
            info118.IsCjk = false;
            info118.IsComplexScript = false;
            dictionary["Gentium Basic"] = info118;
            FontCapabilitiesInfo info119 = new FontCapabilitiesInfo();
            info119.IsCjk = false;
            info119.IsComplexScript = false;
            dictionary["Gentium Book Basic"] = info119;
            FontCapabilitiesInfo info120 = new FontCapabilitiesInfo();
            info120.IsCjk = false;
            info120.IsComplexScript = false;
            dictionary["Georgia"] = info120;
            FontCapabilitiesInfo info121 = new FontCapabilitiesInfo();
            info121.IsCjk = false;
            info121.IsComplexScript = false;
            dictionary["Gigi"] = info121;
            FontCapabilitiesInfo info122 = new FontCapabilitiesInfo();
            info122.IsCjk = false;
            info122.IsComplexScript = false;
            dictionary["Gill Sans MT"] = info122;
            FontCapabilitiesInfo info123 = new FontCapabilitiesInfo();
            info123.IsCjk = false;
            info123.IsComplexScript = false;
            dictionary["Gill Sans MT Condensed"] = info123;
            FontCapabilitiesInfo info124 = new FontCapabilitiesInfo();
            info124.IsCjk = false;
            info124.IsComplexScript = false;
            dictionary["Gill Sans MT Ext Condensed Bold"] = info124;
            FontCapabilitiesInfo info125 = new FontCapabilitiesInfo();
            info125.IsCjk = false;
            info125.IsComplexScript = false;
            dictionary["Gill Sans Ultra Bold"] = info125;
            FontCapabilitiesInfo info126 = new FontCapabilitiesInfo();
            info126.IsCjk = false;
            info126.IsComplexScript = false;
            dictionary["Gill Sans Ultra Bold Condensed"] = info126;
            FontCapabilitiesInfo info127 = new FontCapabilitiesInfo();
            info127.IsCjk = false;
            info127.IsComplexScript = true;
            dictionary["Gisha"] = info127;
            FontCapabilitiesInfo info128 = new FontCapabilitiesInfo();
            info128.IsCjk = false;
            info128.IsComplexScript = false;
            dictionary["Gloucester MT Extra Condensed"] = info128;
            FontCapabilitiesInfo info129 = new FontCapabilitiesInfo();
            info129.IsCjk = false;
            info129.IsComplexScript = false;
            dictionary["Gost"] = info129;
            FontCapabilitiesInfo info130 = new FontCapabilitiesInfo();
            info130.IsCjk = false;
            info130.IsComplexScript = false;
            dictionary["Goudy Old Style"] = info130;
            FontCapabilitiesInfo info131 = new FontCapabilitiesInfo();
            info131.IsCjk = false;
            info131.IsComplexScript = false;
            dictionary["Goudy Stout"] = info131;
            FontCapabilitiesInfo info132 = new FontCapabilitiesInfo();
            info132.IsCjk = true;
            info132.IsComplexScript = false;
            dictionary["Gulim"] = info132;
            FontCapabilitiesInfo info133 = new FontCapabilitiesInfo();
            info133.IsCjk = true;
            info133.IsComplexScript = false;
            dictionary["GulimChe"] = info133;
            FontCapabilitiesInfo info134 = new FontCapabilitiesInfo();
            info134.IsCjk = true;
            info134.IsComplexScript = false;
            dictionary["Gungsuh"] = info134;
            FontCapabilitiesInfo info135 = new FontCapabilitiesInfo();
            info135.IsCjk = true;
            info135.IsComplexScript = false;
            dictionary["GungsuhChe"] = info135;
            FontCapabilitiesInfo info136 = new FontCapabilitiesInfo();
            info136.IsCjk = false;
            info136.IsComplexScript = false;
            dictionary["Haettenschweiler"] = info136;
            FontCapabilitiesInfo info137 = new FontCapabilitiesInfo();
            info137.IsCjk = false;
            info137.IsComplexScript = false;
            dictionary["Harlow Solid Italic"] = info137;
            FontCapabilitiesInfo info138 = new FontCapabilitiesInfo();
            info138.IsCjk = false;
            info138.IsComplexScript = false;
            dictionary["Harrington"] = info138;
            FontCapabilitiesInfo info139 = new FontCapabilitiesInfo();
            info139.IsCjk = false;
            info139.IsComplexScript = true;
            dictionary["Helvetica"] = info139;
            FontCapabilitiesInfo info140 = new FontCapabilitiesInfo();
            info140.IsCjk = false;
            info140.IsComplexScript = true;
            dictionary["HelveticaNeue-Light"] = info140;
            FontCapabilitiesInfo info141 = new FontCapabilitiesInfo();
            info141.IsCjk = false;
            info141.IsComplexScript = true;
            dictionary["Helvetica Neue Light"] = info141;
            FontCapabilitiesInfo info142 = new FontCapabilitiesInfo();
            info142.IsCjk = false;
            info142.IsComplexScript = false;
            dictionary["High Tower Text"] = info142;
            FontCapabilitiesInfo info143 = new FontCapabilitiesInfo();
            info143.IsCjk = false;
            info143.IsComplexScript = false;
            dictionary["Impact"] = info143;
            FontCapabilitiesInfo info144 = new FontCapabilitiesInfo();
            info144.IsCjk = false;
            info144.IsComplexScript = false;
            dictionary["Imprint MT Shadow"] = info144;
            FontCapabilitiesInfo info145 = new FontCapabilitiesInfo();
            info145.IsCjk = false;
            info145.IsComplexScript = false;
            dictionary["Informal Roman"] = info145;
            FontCapabilitiesInfo info146 = new FontCapabilitiesInfo();
            info146.IsCjk = false;
            info146.IsComplexScript = false;
            dictionary["IrisUPC"] = info146;
            FontCapabilitiesInfo info147 = new FontCapabilitiesInfo();
            info147.IsCjk = false;
            info147.IsComplexScript = false;
            dictionary["Iskoola Pota"] = info147;
            FontCapabilitiesInfo info148 = new FontCapabilitiesInfo();
            info148.IsCjk = false;
            info148.IsComplexScript = false;
            dictionary["JasmineUPC"] = info148;
            FontCapabilitiesInfo info149 = new FontCapabilitiesInfo();
            info149.IsCjk = false;
            info149.IsComplexScript = false;
            dictionary["Javanese Text"] = info149;
            FontCapabilitiesInfo info150 = new FontCapabilitiesInfo();
            info150.IsCjk = false;
            info150.IsComplexScript = false;
            dictionary["Jokerman"] = info150;
            FontCapabilitiesInfo info151 = new FontCapabilitiesInfo();
            info151.IsCjk = false;
            info151.IsComplexScript = false;
            dictionary["Juice ITC"] = info151;
            FontCapabilitiesInfo info152 = new FontCapabilitiesInfo();
            info152.IsCjk = false;
            info152.IsComplexScript = true;
            dictionary["KacstBook"] = info152;
            FontCapabilitiesInfo info153 = new FontCapabilitiesInfo();
            info153.IsCjk = false;
            info153.IsComplexScript = true;
            dictionary["KacstOffice"] = info153;
            FontCapabilitiesInfo info154 = new FontCapabilitiesInfo();
            info154.IsCjk = true;
            info154.IsComplexScript = false;
            dictionary["KaiTi"] = info154;
            FontCapabilitiesInfo info155 = new FontCapabilitiesInfo();
            info155.IsCjk = false;
            info155.IsComplexScript = false;
            dictionary["Kalinga"] = info155;
            FontCapabilitiesInfo info156 = new FontCapabilitiesInfo();
            info156.IsCjk = false;
            info156.IsComplexScript = false;
            dictionary["Kartika"] = info156;
            FontCapabilitiesInfo info157 = new FontCapabilitiesInfo();
            info157.IsCjk = false;
            info157.IsComplexScript = false;
            dictionary["Khmer UI"] = info157;
            FontCapabilitiesInfo info158 = new FontCapabilitiesInfo();
            info158.IsCjk = false;
            info158.IsComplexScript = false;
            dictionary["KodchiangUPC"] = info158;
            FontCapabilitiesInfo info159 = new FontCapabilitiesInfo();
            info159.IsCjk = false;
            info159.IsComplexScript = false;
            dictionary["Kokila"] = info159;
            FontCapabilitiesInfo info160 = new FontCapabilitiesInfo();
            info160.IsCjk = false;
            info160.IsComplexScript = false;
            dictionary["Kristen ITC"] = info160;
            FontCapabilitiesInfo info161 = new FontCapabilitiesInfo();
            info161.IsCjk = false;
            info161.IsComplexScript = false;
            dictionary["Kunstler Script"] = info161;
            FontCapabilitiesInfo info162 = new FontCapabilitiesInfo();
            info162.IsCjk = false;
            info162.IsComplexScript = false;
            dictionary["Lao UI"] = info162;
            FontCapabilitiesInfo info163 = new FontCapabilitiesInfo();
            info163.IsCjk = false;
            info163.IsComplexScript = false;
            dictionary["Latha"] = info163;
            FontCapabilitiesInfo info164 = new FontCapabilitiesInfo();
            info164.IsCjk = false;
            info164.IsComplexScript = false;
            dictionary["Leelawadee"] = info164;
            FontCapabilitiesInfo info165 = new FontCapabilitiesInfo();
            info165.IsCjk = false;
            info165.IsComplexScript = false;
            dictionary["Leelawadee UI"] = info165;
            FontCapabilitiesInfo info166 = new FontCapabilitiesInfo();
            info166.IsCjk = false;
            info166.IsComplexScript = false;
            dictionary["Leelawadee UI Semilight"] = info166;
            FontCapabilitiesInfo info167 = new FontCapabilitiesInfo();
            info167.IsCjk = false;
            info167.IsComplexScript = true;
            dictionary["Levenim MT"] = info167;
            FontCapabilitiesInfo info168 = new FontCapabilitiesInfo();
            info168.IsCjk = false;
            info168.IsComplexScript = true;
            dictionary["Liberation Mono"] = info168;
            FontCapabilitiesInfo info169 = new FontCapabilitiesInfo();
            info169.IsCjk = false;
            info169.IsComplexScript = true;
            dictionary["Liberation Sans"] = info169;
            FontCapabilitiesInfo info170 = new FontCapabilitiesInfo();
            info170.IsCjk = false;
            info170.IsComplexScript = false;
            dictionary["Liberation Sans Narrow"] = info170;
            FontCapabilitiesInfo info171 = new FontCapabilitiesInfo();
            info171.IsCjk = false;
            info171.IsComplexScript = true;
            dictionary["Liberation Serif"] = info171;
            FontCapabilitiesInfo info172 = new FontCapabilitiesInfo();
            info172.IsCjk = false;
            info172.IsComplexScript = false;
            dictionary["LilyUPC"] = info172;
            FontCapabilitiesInfo info173 = new FontCapabilitiesInfo();
            info173.IsCjk = false;
            info173.IsComplexScript = true;
            dictionary["Linux Biolinum G"] = info173;
            FontCapabilitiesInfo info174 = new FontCapabilitiesInfo();
            info174.IsCjk = false;
            info174.IsComplexScript = true;
            dictionary["Linux Libertine Display G"] = info174;
            FontCapabilitiesInfo info175 = new FontCapabilitiesInfo();
            info175.IsCjk = false;
            info175.IsComplexScript = true;
            dictionary["Linux Libertine G"] = info175;
            FontCapabilitiesInfo info176 = new FontCapabilitiesInfo();
            info176.IsCjk = false;
            info176.IsComplexScript = false;
            dictionary["Lucida Bright"] = info176;
            FontCapabilitiesInfo info177 = new FontCapabilitiesInfo();
            info177.IsCjk = false;
            info177.IsComplexScript = false;
            dictionary["Lucida Calligraphy"] = info177;
            FontCapabilitiesInfo info178 = new FontCapabilitiesInfo();
            info178.IsCjk = false;
            info178.IsComplexScript = false;
            dictionary["Lucida Console"] = info178;
            FontCapabilitiesInfo info179 = new FontCapabilitiesInfo();
            info179.IsCjk = false;
            info179.IsComplexScript = false;
            dictionary["Lucida Fax"] = info179;
            FontCapabilitiesInfo info180 = new FontCapabilitiesInfo();
            info180.IsCjk = false;
            info180.IsComplexScript = false;
            dictionary["Lucida Handwriting"] = info180;
            FontCapabilitiesInfo info181 = new FontCapabilitiesInfo();
            info181.IsCjk = false;
            info181.IsComplexScript = false;
            dictionary["Lucida Sans"] = info181;
            FontCapabilitiesInfo info182 = new FontCapabilitiesInfo();
            info182.IsCjk = false;
            info182.IsComplexScript = false;
            dictionary["Lucida Sans Typewriter"] = info182;
            FontCapabilitiesInfo info183 = new FontCapabilitiesInfo();
            info183.IsCjk = false;
            info183.IsComplexScript = true;
            dictionary["Lucida Sans Unicode"] = info183;
            FontCapabilitiesInfo info184 = new FontCapabilitiesInfo();
            info184.IsCjk = false;
            info184.IsComplexScript = false;
            dictionary["Magneto"] = info184;
            FontCapabilitiesInfo info185 = new FontCapabilitiesInfo();
            info185.IsCjk = false;
            info185.IsComplexScript = false;
            dictionary["Maiandra GD"] = info185;
            FontCapabilitiesInfo info186 = new FontCapabilitiesInfo();
            info186.IsCjk = true;
            info186.IsComplexScript = false;
            dictionary["Malgun Gothic"] = info186;
            FontCapabilitiesInfo info187 = new FontCapabilitiesInfo();
            info187.IsCjk = false;
            info187.IsComplexScript = false;
            dictionary["Mangal"] = info187;
            FontCapabilitiesInfo info188 = new FontCapabilitiesInfo();
            info188.IsCjk = false;
            info188.IsComplexScript = false;
            dictionary["Marlett"] = info188;
            FontCapabilitiesInfo info189 = new FontCapabilitiesInfo();
            info189.IsCjk = false;
            info189.IsComplexScript = false;
            dictionary["Matura MT Script Capitals"] = info189;
            FontCapabilitiesInfo info190 = new FontCapabilitiesInfo();
            info190.IsCjk = true;
            info190.IsComplexScript = false;
            dictionary["Meiryo"] = info190;
            FontCapabilitiesInfo info191 = new FontCapabilitiesInfo();
            info191.IsCjk = true;
            info191.IsComplexScript = false;
            dictionary["Meiryo UI"] = info191;
            FontCapabilitiesInfo info192 = new FontCapabilitiesInfo();
            info192.IsCjk = true;
            info192.IsComplexScript = false;
            dictionary["Microsoft Himalaya"] = info192;
            FontCapabilitiesInfo info193 = new FontCapabilitiesInfo();
            info193.IsCjk = true;
            info193.IsComplexScript = false;
            dictionary["Microsoft JhengHei"] = info193;
            FontCapabilitiesInfo info194 = new FontCapabilitiesInfo();
            info194.IsCjk = true;
            info194.IsComplexScript = false;
            dictionary["Microsoft JhengHei Light"] = info194;
            FontCapabilitiesInfo info195 = new FontCapabilitiesInfo();
            info195.IsCjk = true;
            info195.IsComplexScript = false;
            dictionary["Microsoft JhengHei UI"] = info195;
            FontCapabilitiesInfo info196 = new FontCapabilitiesInfo();
            info196.IsCjk = true;
            info196.IsComplexScript = false;
            dictionary["Microsoft JhengHei UI Light"] = info196;
            FontCapabilitiesInfo info197 = new FontCapabilitiesInfo();
            info197.IsCjk = true;
            info197.IsComplexScript = false;
            dictionary["Microsoft MHei"] = info197;
            FontCapabilitiesInfo info198 = new FontCapabilitiesInfo();
            info198.IsCjk = true;
            info198.IsComplexScript = false;
            dictionary["Microsoft NeoGothic"] = info198;
            FontCapabilitiesInfo info199 = new FontCapabilitiesInfo();
            info199.IsCjk = false;
            info199.IsComplexScript = false;
            dictionary["Microsoft New Tai Lue"] = info199;
            FontCapabilitiesInfo info200 = new FontCapabilitiesInfo();
            info200.IsCjk = false;
            info200.IsComplexScript = false;
            dictionary["Microsoft PhagsPa"] = info200;
            FontCapabilitiesInfo info201 = new FontCapabilitiesInfo();
            info201.IsCjk = false;
            info201.IsComplexScript = true;
            dictionary["Microsoft Sans Serif"] = info201;
            FontCapabilitiesInfo info202 = new FontCapabilitiesInfo();
            info202.IsCjk = false;
            info202.IsComplexScript = false;
            dictionary["Microsoft Tai Le"] = info202;
            FontCapabilitiesInfo info203 = new FontCapabilitiesInfo();
            info203.IsCjk = false;
            info203.IsComplexScript = true;
            dictionary["Microsoft Uighur"] = info203;
            FontCapabilitiesInfo info204 = new FontCapabilitiesInfo();
            info204.IsCjk = true;
            info204.IsComplexScript = false;
            dictionary["Microsoft YaHei"] = info204;
            FontCapabilitiesInfo info205 = new FontCapabilitiesInfo();
            info205.IsCjk = true;
            info205.IsComplexScript = false;
            dictionary["Microsoft YaHei Light"] = info205;
            FontCapabilitiesInfo info206 = new FontCapabilitiesInfo();
            info206.IsCjk = true;
            info206.IsComplexScript = false;
            dictionary["Microsoft YaHei UI"] = info206;
            FontCapabilitiesInfo info207 = new FontCapabilitiesInfo();
            info207.IsCjk = true;
            info207.IsComplexScript = false;
            dictionary["Microsoft YaHei UI Light"] = info207;
            FontCapabilitiesInfo info208 = new FontCapabilitiesInfo();
            info208.IsCjk = true;
            info208.IsComplexScript = false;
            dictionary["Microsoft Yi Baiti"] = info208;
            FontCapabilitiesInfo info209 = new FontCapabilitiesInfo();
            info209.IsCjk = true;
            info209.IsComplexScript = false;
            dictionary["MingLiU"] = info209;
            FontCapabilitiesInfo info210 = new FontCapabilitiesInfo();
            info210.IsCjk = false;
            info210.IsComplexScript = false;
            dictionary["MingLiU-ExtB"] = info210;
            FontCapabilitiesInfo info211 = new FontCapabilitiesInfo();
            info211.IsCjk = true;
            info211.IsComplexScript = false;
            dictionary["MingLiU_HKSCS"] = info211;
            FontCapabilitiesInfo info212 = new FontCapabilitiesInfo();
            info212.IsCjk = false;
            info212.IsComplexScript = false;
            dictionary["MingLiU_HKSCS-ExtB"] = info212;
            FontCapabilitiesInfo info213 = new FontCapabilitiesInfo();
            info213.IsCjk = false;
            info213.IsComplexScript = true;
            dictionary["Miriam"] = info213;
            FontCapabilitiesInfo info214 = new FontCapabilitiesInfo();
            info214.IsCjk = false;
            info214.IsComplexScript = true;
            dictionary["Miriam CLM"] = info214;
            FontCapabilitiesInfo info215 = new FontCapabilitiesInfo();
            info215.IsCjk = false;
            info215.IsComplexScript = true;
            dictionary["Miriam Fixed"] = info215;
            FontCapabilitiesInfo info216 = new FontCapabilitiesInfo();
            info216.IsCjk = false;
            info216.IsComplexScript = true;
            dictionary["Miriam Libre"] = info216;
            FontCapabilitiesInfo info217 = new FontCapabilitiesInfo();
            info217.IsCjk = false;
            info217.IsComplexScript = true;
            dictionary["Miriam Mono CLM"] = info217;
            FontCapabilitiesInfo info218 = new FontCapabilitiesInfo();
            info218.IsCjk = false;
            info218.IsComplexScript = false;
            dictionary["Mistral"] = info218;
            FontCapabilitiesInfo info219 = new FontCapabilitiesInfo();
            info219.IsCjk = false;
            info219.IsComplexScript = false;
            dictionary["Modern No. 20"] = info219;
            FontCapabilitiesInfo info220 = new FontCapabilitiesInfo();
            info220.IsCjk = false;
            info220.IsComplexScript = false;
            dictionary["Mongolian Baiti"] = info220;
            FontCapabilitiesInfo info221 = new FontCapabilitiesInfo();
            info221.IsCjk = false;
            info221.IsComplexScript = false;
            dictionary["Monotype Corsiva"] = info221;
            FontCapabilitiesInfo info222 = new FontCapabilitiesInfo();
            info222.IsCjk = false;
            info222.IsComplexScript = false;
            dictionary["MoolBoran"] = info222;
            FontCapabilitiesInfo info223 = new FontCapabilitiesInfo();
            info223.IsCjk = true;
            info223.IsComplexScript = false;
            dictionary["MS Gothic"] = info223;
            FontCapabilitiesInfo info224 = new FontCapabilitiesInfo();
            info224.IsCjk = true;
            info224.IsComplexScript = false;
            dictionary["MS Mincho"] = info224;
            FontCapabilitiesInfo info225 = new FontCapabilitiesInfo();
            info225.IsCjk = false;
            info225.IsComplexScript = false;
            dictionary["MS Outlook"] = info225;
            FontCapabilitiesInfo info226 = new FontCapabilitiesInfo();
            info226.IsCjk = true;
            info226.IsComplexScript = false;
            dictionary["MS PGothic"] = info226;
            FontCapabilitiesInfo info227 = new FontCapabilitiesInfo();
            info227.IsCjk = true;
            info227.IsComplexScript = false;
            dictionary["MS PMincho"] = info227;
            FontCapabilitiesInfo info228 = new FontCapabilitiesInfo();
            info228.IsCjk = false;
            info228.IsComplexScript = false;
            dictionary["MS Reference Sans Serif"] = info228;
            FontCapabilitiesInfo info229 = new FontCapabilitiesInfo();
            info229.IsCjk = false;
            info229.IsComplexScript = false;
            dictionary["MS Reference Specialty"] = info229;
            FontCapabilitiesInfo info230 = new FontCapabilitiesInfo();
            info230.IsCjk = true;
            info230.IsComplexScript = false;
            dictionary["MS UI Gothic"] = info230;
            FontCapabilitiesInfo info231 = new FontCapabilitiesInfo();
            info231.IsCjk = false;
            info231.IsComplexScript = false;
            dictionary["MT Extra"] = info231;
            FontCapabilitiesInfo info232 = new FontCapabilitiesInfo();
            info232.IsCjk = false;
            info232.IsComplexScript = false;
            dictionary["MV Boli"] = info232;
            FontCapabilitiesInfo info233 = new FontCapabilitiesInfo();
            info233.IsCjk = false;
            info233.IsComplexScript = false;
            dictionary["Myanmar Text"] = info233;
            FontCapabilitiesInfo info234 = new FontCapabilitiesInfo();
            info234.IsCjk = false;
            info234.IsComplexScript = true;
            dictionary["Nachlieli CLM"] = info234;
            FontCapabilitiesInfo info235 = new FontCapabilitiesInfo();
            info235.IsCjk = false;
            info235.IsComplexScript = true;
            dictionary["Narkisim"] = info235;
            FontCapabilitiesInfo info236 = new FontCapabilitiesInfo();
            info236.IsCjk = false;
            info236.IsComplexScript = false;
            dictionary["Niagara Engraved"] = info236;
            FontCapabilitiesInfo info237 = new FontCapabilitiesInfo();
            info237.IsCjk = false;
            info237.IsComplexScript = false;
            dictionary["Niagara Solid"] = info237;
            FontCapabilitiesInfo info238 = new FontCapabilitiesInfo();
            info238.IsCjk = false;
            info238.IsComplexScript = false;
            dictionary["Nirmala UI"] = info238;
            FontCapabilitiesInfo info239 = new FontCapabilitiesInfo();
            info239.IsCjk = false;
            info239.IsComplexScript = false;
            dictionary["Nirmala UI Semilight"] = info239;
            FontCapabilitiesInfo info240 = new FontCapabilitiesInfo();
            info240.IsCjk = false;
            info240.IsComplexScript = true;
            dictionary["Noto Kufi Arabic"] = info240;
            FontCapabilitiesInfo info241 = new FontCapabilitiesInfo();
            info241.IsCjk = false;
            info241.IsComplexScript = false;
            dictionary["Noto Mono"] = info241;
            FontCapabilitiesInfo info242 = new FontCapabilitiesInfo();
            info242.IsCjk = false;
            info242.IsComplexScript = true;
            dictionary["Noto Naskh Arabic"] = info242;
            FontCapabilitiesInfo info243 = new FontCapabilitiesInfo();
            info243.IsCjk = false;
            info243.IsComplexScript = true;
            dictionary["Noto Naskh Arabic UI"] = info243;
            FontCapabilitiesInfo info244 = new FontCapabilitiesInfo();
            info244.IsCjk = false;
            info244.IsComplexScript = false;
            dictionary["Noto Sans"] = info244;
            FontCapabilitiesInfo info245 = new FontCapabilitiesInfo();
            info245.IsCjk = false;
            info245.IsComplexScript = false;
            dictionary["Noto Sans Arabic"] = info245;
            FontCapabilitiesInfo info246 = new FontCapabilitiesInfo();
            info246.IsCjk = false;
            info246.IsComplexScript = false;
            dictionary["Noto Sans Arabic UI"] = info246;
            FontCapabilitiesInfo info247 = new FontCapabilitiesInfo();
            info247.IsCjk = false;
            info247.IsComplexScript = false;
            dictionary["Noto Sans Armenian"] = info247;
            FontCapabilitiesInfo info248 = new FontCapabilitiesInfo();
            info248.IsCjk = false;
            info248.IsComplexScript = false;
            dictionary["Noto Sans Cond"] = info248;
            FontCapabilitiesInfo info249 = new FontCapabilitiesInfo();
            info249.IsCjk = false;
            info249.IsComplexScript = false;
            dictionary["Noto Sans Georgian"] = info249;
            FontCapabilitiesInfo info250 = new FontCapabilitiesInfo();
            info250.IsCjk = false;
            info250.IsComplexScript = false;
            dictionary["Noto Sans Hebrew"] = info250;
            FontCapabilitiesInfo info251 = new FontCapabilitiesInfo();
            info251.IsCjk = false;
            info251.IsComplexScript = false;
            dictionary["Noto Sans Lao"] = info251;
            FontCapabilitiesInfo info252 = new FontCapabilitiesInfo();
            info252.IsCjk = false;
            info252.IsComplexScript = false;
            dictionary["Noto Sans Light"] = info252;
            FontCapabilitiesInfo info253 = new FontCapabilitiesInfo();
            info253.IsCjk = true;
            info253.IsComplexScript = false;
            dictionary["Noto Sans Lisu"] = info253;
            FontCapabilitiesInfo info254 = new FontCapabilitiesInfo();
            info254.IsCjk = false;
            info254.IsComplexScript = false;
            dictionary["Noto Serif"] = info254;
            FontCapabilitiesInfo info255 = new FontCapabilitiesInfo();
            info255.IsCjk = false;
            info255.IsComplexScript = false;
            dictionary["Noto Serif Armenian"] = info255;
            FontCapabilitiesInfo info256 = new FontCapabilitiesInfo();
            info256.IsCjk = false;
            info256.IsComplexScript = false;
            dictionary["Noto Serif Cond"] = info256;
            FontCapabilitiesInfo info257 = new FontCapabilitiesInfo();
            info257.IsCjk = false;
            info257.IsComplexScript = false;
            dictionary["Noto Serif Georgian"] = info257;
            FontCapabilitiesInfo info258 = new FontCapabilitiesInfo();
            info258.IsCjk = false;
            info258.IsComplexScript = false;
            dictionary["Noto Serif Hebrew"] = info258;
            FontCapabilitiesInfo info259 = new FontCapabilitiesInfo();
            info259.IsCjk = false;
            info259.IsComplexScript = false;
            dictionary["Noto Serif Lao"] = info259;
            FontCapabilitiesInfo info260 = new FontCapabilitiesInfo();
            info260.IsCjk = false;
            info260.IsComplexScript = false;
            dictionary["Noto Serif Light"] = info260;
            FontCapabilitiesInfo info261 = new FontCapabilitiesInfo();
            info261.IsCjk = true;
            info261.IsComplexScript = false;
            dictionary["NSimSun"] = info261;
            FontCapabilitiesInfo info262 = new FontCapabilitiesInfo();
            info262.IsCjk = false;
            info262.IsComplexScript = false;
            dictionary["Nyala"] = info262;
            FontCapabilitiesInfo info263 = new FontCapabilitiesInfo();
            info263.IsCjk = false;
            info263.IsComplexScript = false;
            dictionary["OCR A Extended"] = info263;
            FontCapabilitiesInfo info264 = new FontCapabilitiesInfo();
            info264.IsCjk = false;
            info264.IsComplexScript = false;
            dictionary["Old English Text MT"] = info264;
            FontCapabilitiesInfo info265 = new FontCapabilitiesInfo();
            info265.IsCjk = false;
            info265.IsComplexScript = false;
            dictionary["Onyx"] = info265;
            FontCapabilitiesInfo info266 = new FontCapabilitiesInfo();
            info266.IsCjk = false;
            info266.IsComplexScript = false;
            dictionary["Open Sans"] = info266;
            FontCapabilitiesInfo info267 = new FontCapabilitiesInfo();
            info267.IsCjk = true;
            info267.IsComplexScript = false;
            dictionary["OpenSymbol"] = info267;
            FontCapabilitiesInfo info268 = new FontCapabilitiesInfo();
            info268.IsCjk = false;
            info268.IsComplexScript = false;
            dictionary["Palace Script MT"] = info268;
            FontCapabilitiesInfo info269 = new FontCapabilitiesInfo();
            info269.IsCjk = false;
            info269.IsComplexScript = false;
            dictionary["Palatino Linotype"] = info269;
            FontCapabilitiesInfo info270 = new FontCapabilitiesInfo();
            info270.IsCjk = false;
            info270.IsComplexScript = false;
            dictionary["Papyrus"] = info270;
            FontCapabilitiesInfo info271 = new FontCapabilitiesInfo();
            info271.IsCjk = false;
            info271.IsComplexScript = false;
            dictionary["Parchment"] = info271;
            FontCapabilitiesInfo info272 = new FontCapabilitiesInfo();
            info272.IsCjk = false;
            info272.IsComplexScript = false;
            dictionary["Perpetua"] = info272;
            FontCapabilitiesInfo info273 = new FontCapabilitiesInfo();
            info273.IsCjk = false;
            info273.IsComplexScript = false;
            dictionary["Perpetua Titling MT"] = info273;
            FontCapabilitiesInfo info274 = new FontCapabilitiesInfo();
            info274.IsCjk = false;
            info274.IsComplexScript = false;
            dictionary["Plantagenet Cherokee"] = info274;
            FontCapabilitiesInfo info275 = new FontCapabilitiesInfo();
            info275.IsCjk = false;
            info275.IsComplexScript = false;
            dictionary["Playbill"] = info275;
            FontCapabilitiesInfo info276 = new FontCapabilitiesInfo();
            info276.IsCjk = true;
            info276.IsComplexScript = false;
            dictionary["PMingLiU"] = info276;
            FontCapabilitiesInfo info277 = new FontCapabilitiesInfo();
            info277.IsCjk = false;
            info277.IsComplexScript = false;
            dictionary["PMingLiU-ExtB"] = info277;
            FontCapabilitiesInfo info278 = new FontCapabilitiesInfo();
            info278.IsCjk = false;
            info278.IsComplexScript = false;
            dictionary["Poor Richard"] = info278;
            FontCapabilitiesInfo info279 = new FontCapabilitiesInfo();
            info279.IsCjk = false;
            info279.IsComplexScript = false;
            dictionary["Pristina"] = info279;
            FontCapabilitiesInfo info280 = new FontCapabilitiesInfo();
            info280.IsCjk = false;
            info280.IsComplexScript = false;
            dictionary["PT Serif"] = info280;
            FontCapabilitiesInfo info281 = new FontCapabilitiesInfo();
            info281.IsCjk = false;
            info281.IsComplexScript = false;
            dictionary["Raavi"] = info281;
            FontCapabilitiesInfo info282 = new FontCapabilitiesInfo();
            info282.IsCjk = false;
            info282.IsComplexScript = false;
            dictionary["Rage Italic"] = info282;
            FontCapabilitiesInfo info283 = new FontCapabilitiesInfo();
            info283.IsCjk = false;
            info283.IsComplexScript = false;
            dictionary["Ravie"] = info283;
            FontCapabilitiesInfo info284 = new FontCapabilitiesInfo();
            info284.IsCjk = false;
            info284.IsComplexScript = false;
            dictionary["Reem Kufi Regular"] = info284;
            FontCapabilitiesInfo info285 = new FontCapabilitiesInfo();
            info285.IsCjk = false;
            info285.IsComplexScript = false;
            dictionary["Rockwell"] = info285;
            FontCapabilitiesInfo info286 = new FontCapabilitiesInfo();
            info286.IsCjk = false;
            info286.IsComplexScript = false;
            dictionary["Rockwell Condensed"] = info286;
            FontCapabilitiesInfo info287 = new FontCapabilitiesInfo();
            info287.IsCjk = false;
            info287.IsComplexScript = false;
            dictionary["Rockwell Extra Bold"] = info287;
            FontCapabilitiesInfo info288 = new FontCapabilitiesInfo();
            info288.IsCjk = false;
            info288.IsComplexScript = true;
            dictionary["Rod"] = info288;
            FontCapabilitiesInfo info289 = new FontCapabilitiesInfo();
            info289.IsCjk = false;
            info289.IsComplexScript = true;
            dictionary["Rubik"] = info289;
            FontCapabilitiesInfo info290 = new FontCapabilitiesInfo();
            info290.IsCjk = false;
            info290.IsComplexScript = true;
            dictionary["Sakkal Majalla"] = info290;
            FontCapabilitiesInfo info291 = new FontCapabilitiesInfo();
            info291.IsCjk = false;
            info291.IsComplexScript = true;
            dictionary["Scheherazade"] = info291;
            FontCapabilitiesInfo info292 = new FontCapabilitiesInfo();
            info292.IsCjk = false;
            info292.IsComplexScript = false;
            dictionary["Script MT Bold"] = info292;
            FontCapabilitiesInfo info293 = new FontCapabilitiesInfo();
            info293.IsCjk = false;
            info293.IsComplexScript = false;
            dictionary["Segoe Marker"] = info293;
            FontCapabilitiesInfo info294 = new FontCapabilitiesInfo();
            info294.IsCjk = false;
            info294.IsComplexScript = false;
            dictionary["Segoe Print"] = info294;
            FontCapabilitiesInfo info295 = new FontCapabilitiesInfo();
            info295.IsCjk = false;
            info295.IsComplexScript = false;
            dictionary["Segoe Script"] = info295;
            FontCapabilitiesInfo info296 = new FontCapabilitiesInfo();
            info296.IsCjk = false;
            info296.IsComplexScript = true;
            dictionary["Segoe UI"] = info296;
            FontCapabilitiesInfo info297 = new FontCapabilitiesInfo();
            info297.IsCjk = false;
            info297.IsComplexScript = false;
            dictionary["Segoe UI Black"] = info297;
            FontCapabilitiesInfo info298 = new FontCapabilitiesInfo();
            info298.IsCjk = false;
            info298.IsComplexScript = false;
            dictionary["Segoe UI Emoji"] = info298;
            FontCapabilitiesInfo info299 = new FontCapabilitiesInfo();
            info299.IsCjk = false;
            info299.IsComplexScript = true;
            dictionary["Segoe UI Light"] = info299;
            FontCapabilitiesInfo info300 = new FontCapabilitiesInfo();
            info300.IsCjk = false;
            info300.IsComplexScript = true;
            dictionary["Segoe UI Semibold"] = info300;
            FontCapabilitiesInfo info301 = new FontCapabilitiesInfo();
            info301.IsCjk = false;
            info301.IsComplexScript = true;
            dictionary["Segoe UI Semilight"] = info301;
            FontCapabilitiesInfo info302 = new FontCapabilitiesInfo();
            info302.IsCjk = false;
            info302.IsComplexScript = false;
            dictionary["Segoe UI Symbol"] = info302;
            FontCapabilitiesInfo info303 = new FontCapabilitiesInfo();
            info303.IsCjk = false;
            info303.IsComplexScript = true;
            dictionary["Segoe WP"] = info303;
            FontCapabilitiesInfo info304 = new FontCapabilitiesInfo();
            info304.IsCjk = false;
            info304.IsComplexScript = false;
            dictionary["Segoe WP Black"] = info304;
            FontCapabilitiesInfo info305 = new FontCapabilitiesInfo();
            info305.IsCjk = false;
            info305.IsComplexScript = true;
            dictionary["Segoe WP Light"] = info305;
            FontCapabilitiesInfo info306 = new FontCapabilitiesInfo();
            info306.IsCjk = false;
            info306.IsComplexScript = true;
            dictionary["Segoe WP Semibold"] = info306;
            FontCapabilitiesInfo info307 = new FontCapabilitiesInfo();
            info307.IsCjk = false;
            info307.IsComplexScript = true;
            dictionary["Segoe WP SemiLight"] = info307;
            FontCapabilitiesInfo info308 = new FontCapabilitiesInfo();
            info308.IsCjk = false;
            info308.IsComplexScript = false;
            dictionary["Shonar Bangla"] = info308;
            FontCapabilitiesInfo info309 = new FontCapabilitiesInfo();
            info309.IsCjk = false;
            info309.IsComplexScript = false;
            dictionary["Showcard Gothic"] = info309;
            FontCapabilitiesInfo info310 = new FontCapabilitiesInfo();
            info310.IsCjk = false;
            info310.IsComplexScript = false;
            dictionary["Shruti"] = info310;
            FontCapabilitiesInfo info311 = new FontCapabilitiesInfo();
            info311.IsCjk = true;
            info311.IsComplexScript = false;
            dictionary["SimHei"] = info311;
            FontCapabilitiesInfo info312 = new FontCapabilitiesInfo();
            info312.IsCjk = false;
            info312.IsComplexScript = true;
            dictionary["Simplified Arabic"] = info312;
            FontCapabilitiesInfo info313 = new FontCapabilitiesInfo();
            info313.IsCjk = false;
            info313.IsComplexScript = true;
            dictionary["Simplified Arabic Fixed"] = info313;
            FontCapabilitiesInfo info314 = new FontCapabilitiesInfo();
            info314.IsCjk = true;
            info314.IsComplexScript = false;
            dictionary["SimSun"] = info314;
            FontCapabilitiesInfo info315 = new FontCapabilitiesInfo();
            info315.IsCjk = false;
            info315.IsComplexScript = false;
            dictionary["SimSun-ExtB"] = info315;
            FontCapabilitiesInfo info316 = new FontCapabilitiesInfo();
            info316.IsCjk = false;
            info316.IsComplexScript = false;
            dictionary["Sitka Banner"] = info316;
            FontCapabilitiesInfo info317 = new FontCapabilitiesInfo();
            info317.IsCjk = false;
            info317.IsComplexScript = false;
            dictionary["Sitka Display"] = info317;
            FontCapabilitiesInfo info318 = new FontCapabilitiesInfo();
            info318.IsCjk = false;
            info318.IsComplexScript = false;
            dictionary["Sitka Heading"] = info318;
            FontCapabilitiesInfo info319 = new FontCapabilitiesInfo();
            info319.IsCjk = false;
            info319.IsComplexScript = false;
            dictionary["Sitka Small"] = info319;
            FontCapabilitiesInfo info320 = new FontCapabilitiesInfo();
            info320.IsCjk = false;
            info320.IsComplexScript = false;
            dictionary["Sitka Subheading"] = info320;
            FontCapabilitiesInfo info321 = new FontCapabilitiesInfo();
            info321.IsCjk = false;
            info321.IsComplexScript = false;
            dictionary["Sitka Text"] = info321;
            FontCapabilitiesInfo info322 = new FontCapabilitiesInfo();
            info322.IsCjk = false;
            info322.IsComplexScript = false;
            dictionary["SketchFlow Print"] = info322;
            FontCapabilitiesInfo info323 = new FontCapabilitiesInfo();
            info323.IsCjk = false;
            info323.IsComplexScript = false;
            dictionary["Snap ITC"] = info323;
            FontCapabilitiesInfo info324 = new FontCapabilitiesInfo();
            info324.IsCjk = false;
            info324.IsComplexScript = false;
            dictionary["Source Code Pro"] = info324;
            FontCapabilitiesInfo info325 = new FontCapabilitiesInfo();
            info325.IsCjk = false;
            info325.IsComplexScript = false;
            dictionary["Source Code Pro Black"] = info325;
            FontCapabilitiesInfo info326 = new FontCapabilitiesInfo();
            info326.IsCjk = false;
            info326.IsComplexScript = false;
            dictionary["Source Code Pro ExtraLight"] = info326;
            FontCapabilitiesInfo info327 = new FontCapabilitiesInfo();
            info327.IsCjk = false;
            info327.IsComplexScript = false;
            dictionary["Source Code Pro Light"] = info327;
            FontCapabilitiesInfo info328 = new FontCapabilitiesInfo();
            info328.IsCjk = false;
            info328.IsComplexScript = false;
            dictionary["Source Code Pro Medium"] = info328;
            FontCapabilitiesInfo info329 = new FontCapabilitiesInfo();
            info329.IsCjk = false;
            info329.IsComplexScript = false;
            dictionary["Source Code Pro Semibold"] = info329;
            FontCapabilitiesInfo info330 = new FontCapabilitiesInfo();
            info330.IsCjk = false;
            info330.IsComplexScript = false;
            dictionary["Source Sans Pro"] = info330;
            FontCapabilitiesInfo info331 = new FontCapabilitiesInfo();
            info331.IsCjk = false;
            info331.IsComplexScript = false;
            dictionary["Source Sans Pro Black"] = info331;
            FontCapabilitiesInfo info332 = new FontCapabilitiesInfo();
            info332.IsCjk = false;
            info332.IsComplexScript = false;
            dictionary["Source Sans Pro ExtraLight"] = info332;
            FontCapabilitiesInfo info333 = new FontCapabilitiesInfo();
            info333.IsCjk = false;
            info333.IsComplexScript = false;
            dictionary["Source Sans Pro Light"] = info333;
            FontCapabilitiesInfo info334 = new FontCapabilitiesInfo();
            info334.IsCjk = false;
            info334.IsComplexScript = false;
            dictionary["Source Sans Pro Semibold"] = info334;
            FontCapabilitiesInfo info335 = new FontCapabilitiesInfo();
            info335.IsCjk = false;
            info335.IsComplexScript = false;
            dictionary["Stencil"] = info335;
            FontCapabilitiesInfo info336 = new FontCapabilitiesInfo();
            info336.IsCjk = false;
            info336.IsComplexScript = false;
            dictionary["Sylfaen"] = info336;
            FontCapabilitiesInfo info337 = new FontCapabilitiesInfo();
            info337.IsCjk = false;
            info337.IsComplexScript = false;
            dictionary["Symbol"] = info337;
            FontCapabilitiesInfo info338 = new FontCapabilitiesInfo();
            info338.IsCjk = false;
            info338.IsComplexScript = true;
            dictionary["Tahoma"] = info338;
            FontCapabilitiesInfo info339 = new FontCapabilitiesInfo();
            info339.IsCjk = false;
            info339.IsComplexScript = false;
            dictionary["TeamViewer12"] = info339;
            FontCapabilitiesInfo info340 = new FontCapabilitiesInfo();
            info340.IsCjk = false;
            info340.IsComplexScript = false;
            dictionary["Tempus Sans ITC"] = info340;
            FontCapabilitiesInfo info341 = new FontCapabilitiesInfo();
            info341.IsCjk = false;
            info341.IsComplexScript = true;
            dictionary["Times New Roman"] = info341;
            FontCapabilitiesInfo info342 = new FontCapabilitiesInfo();
            info342.IsCjk = false;
            info342.IsComplexScript = true;
            dictionary["Traditional Arabic"] = info342;
            FontCapabilitiesInfo info343 = new FontCapabilitiesInfo();
            info343.IsCjk = false;
            info343.IsComplexScript = false;
            dictionary["Trebuchet MS"] = info343;
            FontCapabilitiesInfo info344 = new FontCapabilitiesInfo();
            info344.IsCjk = false;
            info344.IsComplexScript = false;
            dictionary["Tunga"] = info344;
            FontCapabilitiesInfo info345 = new FontCapabilitiesInfo();
            info345.IsCjk = false;
            info345.IsComplexScript = false;
            dictionary["Tw Cen MT"] = info345;
            FontCapabilitiesInfo info346 = new FontCapabilitiesInfo();
            info346.IsCjk = false;
            info346.IsComplexScript = false;
            dictionary["Tw Cen MT Condensed"] = info346;
            FontCapabilitiesInfo info347 = new FontCapabilitiesInfo();
            info347.IsCjk = false;
            info347.IsComplexScript = false;
            dictionary["Tw Cen MT Condensed Extra Bold"] = info347;
            FontCapabilitiesInfo info348 = new FontCapabilitiesInfo();
            info348.IsCjk = false;
            info348.IsComplexScript = true;
            dictionary["Urdu Typesetting"] = info348;
            FontCapabilitiesInfo info349 = new FontCapabilitiesInfo();
            info349.IsCjk = false;
            info349.IsComplexScript = false;
            dictionary["Utsaah"] = info349;
            FontCapabilitiesInfo info350 = new FontCapabilitiesInfo();
            info350.IsCjk = false;
            info350.IsComplexScript = false;
            dictionary["Vani"] = info350;
            FontCapabilitiesInfo info351 = new FontCapabilitiesInfo();
            info351.IsCjk = false;
            info351.IsComplexScript = false;
            dictionary["Verdana"] = info351;
            FontCapabilitiesInfo info352 = new FontCapabilitiesInfo();
            info352.IsCjk = false;
            info352.IsComplexScript = false;
            dictionary["Vijaya"] = info352;
            FontCapabilitiesInfo info353 = new FontCapabilitiesInfo();
            info353.IsCjk = false;
            info353.IsComplexScript = false;
            dictionary["Viner Hand ITC"] = info353;
            FontCapabilitiesInfo info354 = new FontCapabilitiesInfo();
            info354.IsCjk = false;
            info354.IsComplexScript = false;
            dictionary["Vivaldi"] = info354;
            FontCapabilitiesInfo info355 = new FontCapabilitiesInfo();
            info355.IsCjk = false;
            info355.IsComplexScript = false;
            dictionary["Vladimir Script"] = info355;
            FontCapabilitiesInfo info356 = new FontCapabilitiesInfo();
            info356.IsCjk = false;
            info356.IsComplexScript = false;
            dictionary["Vrinda"] = info356;
            FontCapabilitiesInfo info357 = new FontCapabilitiesInfo();
            info357.IsCjk = false;
            info357.IsComplexScript = false;
            dictionary["Webdings"] = info357;
            FontCapabilitiesInfo info358 = new FontCapabilitiesInfo();
            info358.IsCjk = false;
            info358.IsComplexScript = false;
            dictionary["Wide Latin"] = info358;
            FontCapabilitiesInfo info359 = new FontCapabilitiesInfo();
            info359.IsCjk = false;
            info359.IsComplexScript = false;
            dictionary["Wingdings"] = info359;
            FontCapabilitiesInfo info360 = new FontCapabilitiesInfo();
            info360.IsCjk = false;
            info360.IsComplexScript = false;
            dictionary["Wingdings 2"] = info360;
            FontCapabilitiesInfo info361 = new FontCapabilitiesInfo();
            info361.IsCjk = false;
            info361.IsComplexScript = false;
            dictionary["Wingdings 3"] = info361;
            FontCapabilitiesInfo info362 = new FontCapabilitiesInfo();
            info362.IsCjk = true;
            info362.IsComplexScript = false;
            dictionary["Yu Gothic"] = info362;
            FontCapabilitiesInfo info363 = new FontCapabilitiesInfo();
            info363.IsCjk = true;
            info363.IsComplexScript = false;
            dictionary["Yu Gothic Light"] = info363;
            FontCapabilitiesInfo info364 = new FontCapabilitiesInfo();
            info364.IsCjk = true;
            info364.IsComplexScript = false;
            dictionary["Yu Mincho"] = info364;
            FontCapabilitiesInfo info365 = new FontCapabilitiesInfo();
            info365.IsCjk = true;
            info365.IsComplexScript = false;
            dictionary["Yu Mincho Demibold"] = info365;
            FontCapabilitiesInfo info366 = new FontCapabilitiesInfo();
            info366.IsCjk = true;
            info366.IsComplexScript = false;
            dictionary["Yu Mincho Light"] = info366;
            return dictionary;
        }

        public FontInfo CreateFontInfo(string fontName, int doubleFontSize, bool fontBold, bool fontItalic, bool fontStrikeout, bool fontUnderline) => 
            this.CreateFontInfo(fontName, doubleFontSize, fontBold, fontItalic, fontStrikeout, fontUnderline, 0);

        public FontInfo CreateFontInfo(string fontName, int doubleFontSize, bool fontBold, bool fontItalic, bool fontStrikeout, bool fontUnderline, int textRotation) => 
            this.CreateFontInfoCore(fontName, doubleFontSize, fontBold, fontItalic, fontStrikeout, fontUnderline, textRotation, null);

        protected internal virtual int CreateFontInfo(long hash, string fontName, int doubleFontSize, bool fontBold, bool fontItalic, bool fontStrikeout, bool fontUnderline, int textRotation, FontInfo baselineFontInfo)
        {
            FontInfo item = this.CreateFontInfoCore(fontName, doubleFontSize, fontBold, fontItalic, fontStrikeout, fontUnderline, textRotation, baselineFontInfo);
            int count = this.fontInfoList.Count;
            this.fontInfoList.Add(item);
            if (!this.charsets.ContainsKey(fontName))
            {
                this.charsets.Add(fontName, item.Charset);
            }
            this.indexHash.Add(hash, count);
            return count;
        }

        protected internal abstract FontInfo CreateFontInfoCore(string fontName, int doubleFontSize, bool fontBold, bool fontItalic, bool fontStrikeout, bool fontUnderline, int textRotation, FontInfo baselineFontInfo);
        protected internal abstract FontInfoMeasurer CreateFontInfoMeasurer(DocumentLayoutUnitConverter unitConverter);
        public void Dispose()
        {
            this.Dispose(true);
        }

        protected virtual void Dispose(bool disposing)
        {
            if (disposing)
            {
                this.DisposeContent();
                if (this.measurer != null)
                {
                    this.measurer.Dispose();
                    this.measurer = null;
                }
            }
            this.isDisposed = true;
        }

        protected internal virtual void DisposeContent()
        {
            if (this.fontInfoList != null)
            {
                int count = this.fontInfoList.Count;
                int num2 = 0;
                while (true)
                {
                    if (num2 >= count)
                    {
                        this.fontInfoList.Clear();
                        this.fontInfoList = null;
                        break;
                    }
                    this[num2].Dispose();
                    num2++;
                }
            }
            if (this.indexHash != null)
            {
                this.indexHash.Clear();
                this.indexHash = null;
            }
        }

        public virtual string FindSubstituteFont(string sourceFontName, char ch)
        {
            this.PopulateNameToCharacterSetMap();
            int num = 0x7fffffff;
            string key = sourceFontName;
            Dictionary<string, FontCharacterSet> nameToCharacterSetMap = this.NameToCharacterSetMap;
            lock (nameToCharacterSetMap)
            {
                FontCharacterSet set = this.NameToCharacterSetMap[sourceFontName];
                foreach (KeyValuePair<string, FontCharacterSet> pair in this.NameToCharacterSetMap)
                {
                    FontCharacterSet set2 = pair.Value;
                    if (set2.ContainsChar(ch))
                    {
                        int num2 = FontCharacterSet.CalculatePanoseDistance(set, set2);
                        if (num2 < num)
                        {
                            num = num2;
                            key = pair.Key;
                        }
                    }
                }
            }
            return key;
        }

        public int GetCharsetByFontName(string fontName)
        {
            int num;
            if (!this.charsets.TryGetValue(fontName, out num))
            {
                this.CalcFontIndex(fontName, 0x18, false, false, CharacterFormattingScript.Normal, false, false, 0);
            }
            return this.charsets[fontName];
        }

        public FontCapabilitiesInfo GetFontCapabilities(string fontName)
        {
            FontCapabilitiesInfo fontCapabilitiesCore;
            if (string.IsNullOrEmpty(fontName))
            {
                return null;
            }
            if (!fontCapabilitiesMap.TryGetValue(fontName, out fontCapabilitiesCore))
            {
                fontCapabilitiesCore = this.GetFontCapabilitiesCore(fontName);
                fontCapabilitiesMap[fontName] = fontCapabilitiesCore;
            }
            return fontCapabilitiesCore;
        }

        protected abstract FontCapabilitiesInfo GetFontCapabilitiesCore(string fontName);
        protected abstract List<FontCharacterRange> GetFontCharacterRanges(FontInfo fontInfo);
        public abstract FontCharacterSet GetFontCharacterSet(string fontName);
        public bool IsCjkFont(string fontName, bool fallbackValue)
        {
            if (string.IsNullOrEmpty(fontName))
            {
                return false;
            }
            FontCapabilitiesInfo fontCapabilities = this.GetFontCapabilities(fontName);
            return (((fontCapabilities == null) || fontCapabilities.IsSubstituted) ? fallbackValue : fontCapabilities.IsCjk);
        }

        public bool IsComplexScriptFont(string fontName, bool fallbackValue)
        {
            if (string.IsNullOrEmpty(fontName))
            {
                return false;
            }
            FontCapabilitiesInfo fontCapabilities = this.GetFontCapabilities(fontName);
            return (((fontCapabilities == null) || fontCapabilities.IsSubstituted) ? fallbackValue : fontCapabilities.IsComplexScript);
        }

        protected internal abstract void PopulateNameToCharacterSetMap();
        public virtual bool ShouldUseDefaultFontToDrawInvisibleCharacter(FontInfo fontInfo, char character) => 
            true;

        internal bool IsDisposed =>
            this.isDisposed;

        public FontInfo this[int index] =>
            this.fontInfoList[index];

        internal List<FontInfo> FontInfoList =>
            this.fontInfoList;

        internal Dictionary<long, int> IndexHash =>
            this.indexHash;

        public FontInfoMeasurer Measurer
        {
            get
            {
                this.measurer ??= this.CreateFontInfoMeasurer(this.unitConverter);
                return this.measurer;
            }
        }

        protected internal virtual Dictionary<string, FontCharacterSet> NameToCharacterSetMap =>
            nameToCharacterSetMap;

        public DocumentLayoutUnitConverter UnitConverter =>
            this.unitConverter;

        public bool AllowCjkCorrection =>
            this.allowCjkCorrection;
    }
}

