namespace DevExpress.Xpf.Core.Native
{
    using System;

    [Flags]
    internal enum SHGSI : uint
    {
        public const SHGSI SHGSI_ICONLOCATION = SHGSI.SHGSI_ICONLOCATION;,
        public const SHGSI SHGSI_ICON = SHGSI.SHGSI_ICON;,
        public const SHGSI SHGSI_SYSICONINDEX = (SHGSI.SHGSI_ICONLOCATION | SHGSI.SHGSI_SYSICONINDEX);,
        public const SHGSI SHGSI_LINKOVERLAY = (SHGSI.SHGSI_ICONLOCATION | SHGSI.SHGSI_LINKOVERLAY);,
        public const SHGSI SHGSI_SELECTED = (SHGSI.SHGSI_ICONLOCATION | SHGSI.SHGSI_SELECTED);,
        public const SHGSI SHGSI_LARGEICON = SHGSI.SHGSI_ICONLOCATION;,
        public const SHGSI SHGSI_SMALLICON = (SHGSI.SHGSI_ICONLOCATION | SHGSI.SHGSI_SMALLICON);,
        public const SHGSI SHGSI_SHELLICONSIZE = (SHGSI.SHGSI_ICONLOCATION | SHGSI.SHGSI_SHELLICONSIZE);
    }
}

