namespace DevExpress.Xpf.Core.ConditionalFormatting.Native
{
    using System;
    using System.Windows;

    public static class AutogeneratedTimelineHelper
    {
        public static readonly DependencyProperty HideRatioProperty = DependencyProperty.RegisterAttached("HideRatio", typeof(double), typeof(AutogeneratedTimelineHelper), new PropertyMetadata(0.0));

        public static double GetHideRatio(DependencyObject obj) => 
            (double) obj.GetValue(HideRatioProperty);

        public static void SetHideRatio(DependencyObject obj, double value)
        {
            obj.SetValue(HideRatioProperty, value);
        }
    }
}

