namespace DevExpress.Pdf
{
    using System;

    public enum PdfFontFamilyClass
    {
        NoClassification = 0,
        OldStyleSerifNoClassification = 0x100,
        OldStyleSerifIBMRoundedLegibility = 0x101,
        OldStyleSerifGaralde = 0x102,
        OldStyleSerifVenetian = 0x103,
        OldStyleSerifModifiedVenetian = 260,
        OldStyleSerifDutchModern = 0x105,
        OldStyleSerifDutchTraditional = 0x106,
        OldStyleSerifContemporary = 0x107,
        OldStyleSerifCalligraphic = 0x108,
        OldStyleSerifMiscellaneous = 0x10f,
        TransitionalSerifNoClassification = 0x200,
        TransitionalSerifDirectLine = 0x201,
        TransitionalSerifScript = 0x202,
        TransitionalSerifMiscellaneous = 0x20f,
        ModernSerifNoClassification = 0x300,
        ModernSerifItalian = 0x301,
        ModernSerifScript = 770,
        ModernSerifMiscellaneous = 0x30f,
        ClarendonSerifNoClassification = 0x400,
        ClarendonSerifClarendon = 0x401,
        ClarendonSerifModern = 0x402,
        ClarendonSerifTraditional = 0x403,
        ClarendonSerifNewspaper = 0x404,
        ClarendonSerifStubSerif = 0x405,
        ClarendonSerifMonotone = 0x406,
        ClarendonSerifTypewriter = 0x407,
        ClarendonSerifMiscellaneous = 0x40f,
        SlabSerifNoClassification = 0x500,
        SlabSerifMonotone = 0x501,
        SlabSerifHumanist = 0x502,
        SlabSerifGeometric = 0x503,
        SlabSerifSwiss = 0x504,
        SlabSerifTypewriter = 0x505,
        SlabSerifMiscellaneous = 0x50f,
        FreeformSerifNoClassification = 0x700,
        FreeformSerifModern = 0x701,
        FreeformSerifMiscellaneous = 0x70f,
        SansSerifNoClassification = 0x800,
        SansSerifIBMNewGrotesqueGothic = 0x801,
        SansSerifHumanist = 0x802,
        SansSerifLowXRoundGeometric = 0x803,
        SansSerifHighXRoundGeometric = 0x804,
        SansSerifNeoGrotesqueGothic = 0x805,
        SansSerifModifiedNeoGrotesqueGothic = 0x806,
        SansSerifTypewriterGothic = 0x809,
        SansSerifMatrix = 0x80a,
        SansSerifMiscellaneous = 0x80f,
        OrnamentalNoClassification = 0x900,
        OrnamentalEngraver = 0x901,
        OrnamentalBlackLetter = 0x902,
        OrnamentalDecorative = 0x903,
        OrnamentalThreeDimensional = 0x904,
        OrnamentalMiscellaneous = 0x90f,
        ScriptNoClassification = 0xa00,
        ScriptUncial = 0xa01,
        ScriptBrushJoined = 0xa02,
        ScriptFormalJoined = 0xa03,
        ScriptMonotoneJoined = 0xa04,
        ScriptCalligraphic = 0xa05,
        ScriptBrushUnjoined = 0xa06,
        ScriptFormalUnjoined = 0xa07,
        ScriptMonotoneUnjoined = 0xa08,
        ScriptMiscellaneous = 0xa0f,
        SymbolicNoClassification = 0xc00,
        SymbolicMixedSerif = 0xc03,
        SymbolicOldstyleSerif = 0xc06,
        SymbolicNeoGrotesqueSansSerif = 0xc07,
        SymbolicMiscellaneous = 0xc0f
    }
}

