namespace DevExpress.XtraPrinting.Localization
{
    using DevExpress.Utils.Localization;
    using DevExpress.Utils.Localization.Internal;
    using System;
    using System.ComponentModel;

    [ToolboxItem(false)]
    public class PreviewLocalizer : XtraLocalizer<PreviewStringId>
    {
        internal static readonly PreviewLocalizer Default = new PreviewLocalizer();

        static PreviewLocalizer()
        {
            SetActiveLocalizerProvider(new DefaultActiveLocalizerProvider<PreviewStringId>(CreateDefaultLocalizer()));
        }

        private void AddStrings()
        {
            this.AddString(PreviewStringId.Button_Cancel, "Cancel");
            this.AddString(PreviewStringId.Button_Ok, "OK");
            this.AddString(PreviewStringId.Button_Help, "Help");
            this.AddString(PreviewStringId.Button_Apply, "Apply");
            this.AddString(PreviewStringId.PreviewForm_Caption, "Preview");
            this.AddString(PreviewStringId.TB_TTip_Customize, "Customize");
            this.AddString(PreviewStringId.TB_TTip_Print, "Print");
            this.AddString(PreviewStringId.TB_TTip_PrintDirect, "Quick Print");
            this.AddString(PreviewStringId.TB_TTip_PageSetup, "Page Setup");
            this.AddString(PreviewStringId.TB_TTip_Magnifier, "Magnifier");
            this.AddString(PreviewStringId.TB_TTip_ZoomIn, "Zoom In");
            this.AddString(PreviewStringId.TB_TTip_ZoomOut, "Zoom Out");
            this.AddString(PreviewStringId.TB_TTip_Zoom, "Zoom");
            this.AddString(PreviewStringId.TB_TTip_Search, "Search");
            this.AddString(PreviewStringId.TB_TTip_FirstPage, "First Page");
            this.AddString(PreviewStringId.TB_TTip_PreviousPage, "Previous Page");
            this.AddString(PreviewStringId.TB_TTip_NextPage, "Next Page");
            this.AddString(PreviewStringId.TB_TTip_LastPage, "Last Page");
            this.AddString(PreviewStringId.TB_TTip_MultiplePages, "Multiple Pages");
            this.AddString(PreviewStringId.TB_TTip_Backgr, "Background");
            this.AddString(PreviewStringId.TB_TTip_Close, "Close Preview");
            this.AddString(PreviewStringId.TB_TTip_EditPageHF, "Header And Footer");
            this.AddString(PreviewStringId.TB_TTip_HandTool, "Hand Tool");
            this.AddString(PreviewStringId.TB_TTip_Export, "Export Document...");
            this.AddString(PreviewStringId.TB_TTip_Send, "Send via E-Mail...");
            this.AddString(PreviewStringId.TB_TTip_Map, "Document Map");
            this.AddString(PreviewStringId.TB_TTip_Thumbnails, "Thumbnails");
            this.AddString(PreviewStringId.TB_TTip_HighlightEditingFields, "Highlight Editing Fields");
            this.AddString(PreviewStringId.TB_TTip_Parameters, "Parameters");
            this.AddString(PreviewStringId.TB_TTip_Watermark, "Watermark");
            this.AddString(PreviewStringId.TB_TTip_Scale, "Scale");
            this.AddString(PreviewStringId.TB_TTip_Open, "Open a document");
            this.AddString(PreviewStringId.TB_TTip_Save, "Save the document");
            this.AddString(PreviewStringId.MenuItem_PdfDocument, "PDF File");
            this.AddString(PreviewStringId.MenuItem_PageLayout, "&Page Layout");
            this.AddString(PreviewStringId.MenuItem_TxtDocument, "Text File");
            this.AddString(PreviewStringId.MenuItem_GraphicDocument, "Image File");
            this.AddString(PreviewStringId.MenuItem_CsvDocument, "CSV File");
            this.AddString(PreviewStringId.MenuItem_MhtDocument, "MHT File");
            this.AddString(PreviewStringId.MenuItem_XlsDocument, "XLS File");
            this.AddString(PreviewStringId.MenuItem_XlsxDocument, "XLSX File");
            this.AddString(PreviewStringId.MenuItem_RtfDocument, "RTF File");
            this.AddString(PreviewStringId.MenuItem_DocxDocument, "DOCX File");
            this.AddString(PreviewStringId.MenuItem_HtmDocument, "HTML File");
            this.AddString(PreviewStringId.SaveDlg_FilterBmp, "BMP Bitmap Format");
            this.AddString(PreviewStringId.SaveDlg_FilterGif, "GIF Graphics Interchange Format");
            this.AddString(PreviewStringId.SaveDlg_FilterJpeg, "JPEG File Interchange Format");
            this.AddString(PreviewStringId.SaveDlg_FilterPng, "PNG Portable Network Graphics Format");
            this.AddString(PreviewStringId.SaveDlg_FilterTiff, "TIFF Tag Image File Format");
            this.AddString(PreviewStringId.SaveDlg_FilterEmf, "EMF Enhanced Windows Metafile");
            this.AddString(PreviewStringId.SaveDlg_FilterWmf, "WMF Windows Metafile");
            this.AddString(PreviewStringId.SB_PageOfPages, "Page {0} of {1}");
            this.AddString(PreviewStringId.SB_ZoomFactor, "Zoom Factor: ");
            this.AddString(PreviewStringId.SB_PageNone, "Nothing");
            this.AddString(PreviewStringId.SB_PageInfo, "{0} of {1}");
            this.AddString(PreviewStringId.SB_PageOfPagesHint, "Page number in document. Click to open the Go To Page dialog.");
            this.AddString(PreviewStringId.SB_TTip_Stop, "Stop");
            this.AddString(PreviewStringId.MPForm_Lbl_Pages, "Pages");
            this.AddString(PreviewStringId.WaitForm_Caption, "Please Wait");
            this.AddString(PreviewStringId.Msg_ErrorTitle, "Error");
            this.AddString(PreviewStringId.Msg_EmptyDocument, "The document does not contain any pages.");
            this.AddString(PreviewStringId.Msg_CreatingDocument, "Creating the document...");
            this.AddString(PreviewStringId.Msg_WaitingForParameterValues, "Waiting for parameter values...");
            this.AddString(PreviewStringId.Msg_ExportingDocument, "Exporting the document...");
            this.AddString(PreviewStringId.Msg_UnavailableNetPrinter, "The net printer is unavailable.");
            this.AddString(PreviewStringId.Msg_NeedPrinter, "No printers installed.");
            this.AddString(PreviewStringId.Msg_WrongPrinter, "The printer name is invalid. Please check the printer settings.");
            this.AddString(PreviewStringId.Msg_WrongPrinting, "An error occurred during printing a document.");
            this.AddString(PreviewStringId.Msg_WrongPageSettings, "The current printer doesn't support the selected paper size.\r\nProceed with printing anyway?");
            this.AddString(PreviewStringId.Msg_CustomDrawWarning, "Warning!");
            this.AddString(PreviewStringId.Msg_PageMarginsWarning, "One or more margins are set outside the printable area of the page. Continue?");
            this.AddString(PreviewStringId.Msg_IncorrectPageRange, "This is not a valid page range");
            this.AddString(PreviewStringId.Msg_FontInvalidNumber, "The font size cannot be set to zero or a negative number");
            this.AddString(PreviewStringId.Msg_NotSupportedFont, "This font is not yet supported");
            this.AddString(PreviewStringId.Msg_NotSupportedFontException, "The \"{0}\" cannot be used since this could be an unsupported OpenType font.");
            this.AddString(PreviewStringId.Msg_IncorrectZoomFactor, "The number must be between {0} and {1}.");
            this.AddString(PreviewStringId.Msg_InvalidMeasurement, "This is not a valid measurement.");
            this.AddString(PreviewStringId.Msg_CannotAccessFile, "The process cannot access the file \"{0}\" because it is being used by another process.");
            this.AddString(PreviewStringId.Msg_CannotFindFile, "Cannot perform the specified task. The following library is missing: \"{0}\"");
            this.AddString(PreviewStringId.Msg_FileReadOnly, "File \"{0}\" is set to read-only, try again with a different file name.");
            this.AddString(PreviewStringId.Msg_OpenFileQuestion, "Do you want to open this file?");
            this.AddString(PreviewStringId.Msg_OpenFileQuestionCaption, "Export");
            this.AddString(PreviewStringId.Msg_CantFitBarcodeToControlBounds, "Control's boundaries are too small for the barcode");
            this.AddString(PreviewStringId.Msg_InvalidBarcodeText, "There are invalid characters in the text");
            this.AddString(PreviewStringId.Msg_InvalidBarcodeTextFormat, "Invalid text format");
            this.AddString(PreviewStringId.Msg_InvalidBarcodeData, "Binary data can't be longer than {0} bytes.");
            this.AddString(PreviewStringId.Msg_IncompatibleBarcodeSettings, "Incompatible settings : {0}");
            this.AddString(PreviewStringId.Msg_IncompatibleLogoQRCodeSettings, "Logo size / Module / Error correction level");
            this.AddString(PreviewStringId.Msg_ImageLoadError, "Cannot load the image from the specified file.");
            this.AddString(PreviewStringId.Msg_IgnoredSvgElements, "Some SVG elements in this image are unsupported and will be ignored.\r\nPlease modify the image to avoid these element types: {0}.");
            this.AddString(PreviewStringId.Msg_InvPropName, "Invalid property name");
            this.AddString(PreviewStringId.Msg_Search_Caption, "Search");
            this.AddString(PreviewStringId.Msg_NoDifferentFilesInStream, "A document can't be exported to a stream in the DifferentFiles mode. Use the SingleFile or SingleFilePageByPage mode instead.");
            this.AddString(PreviewStringId.Msg_BigFileToCreate, "The output file is too big. Try to reduce the number of its pages, or split it into several documents.");
            this.AddString(PreviewStringId.Msg_BigFileToCreateJPEG, "The output file is too big to create a JPEG file. Please choose another image format or another export mode.");
            this.AddString(PreviewStringId.Msg_BigBitmapToCreate, "The output file is too big. Please try to reduce the image resolution,\r\nor choose another export mode.");
            this.AddString(PreviewStringId.Msg_XlsMoreThanMaxRows, "The created XLS file is too big for the XLS format, because it contains more than 65,536 rows.\r\nPlease try to use the XLSX format, instead.");
            this.AddString(PreviewStringId.Msg_XlsMoreThanMaxColumns, "The created XLS file is too big for the XLS format, because it contains more than 256 columns.\r\nPlease try to use the XLSX format, instead.");
            this.AddString(PreviewStringId.Msg_XlsxMoreThanMaxRows, "The created XLSX file is too big for the XLSX format, because it contains more than 1,048,576 rows.\r\nPlease try to reduce the amount of rows in your report and export the report to XLSX again.");
            this.AddString(PreviewStringId.Msg_XlsxMoreThanMaxColumns, "The created XLSX file is too big for the XLSX format, because it contains more than 16,384 columns.\r\nPlease try to reduce the amount of columns in your report and export the report to XLSX again.");
            this.AddString(PreviewStringId.Msg_FileDoesNotHavePrnxExtension, "The specified file doesn't have a PRNX extension. Proceed anyway?");
            this.AddString(PreviewStringId.Msg_FileDoesNotContainValidXml, "The specified file doesn't contain valid XML data in the PRNX format. Loading is stopped.");
            this.AddString(PreviewStringId.Msg_GoToNonExistentPage, "There is no page numbered {0} in this document.");
            this.AddString(PreviewStringId.Msg_Caption, "Printing");
            this.AddString(PreviewStringId.Msg_PathTooLong, "The path is too long.\r\nTry a shorter name.");
            this.AddString(PreviewStringId.Msg_CannotLoadDocument, "The specified file cannot be loaded, because it either does not contain valid XML data or exceeds the allowed size.");
            this.AddString(PreviewStringId.Msg_NoParameters, "The specified parameters do not exist: {0}.");
            this.AddString(PreviewStringId.Msg_SeparatorCannotBeEmptyString, "The separator cannot be an empty string.");
            this.AddString(PreviewStringId.Msg_CannotExportToDocx, "The document cannot be exported to DOCX format correctly with the specified settings.\r\nIf possible, avoid intersecting elements in your document, or try to use the '{0}' export mode with the '{1}' option disabled.");
            this.AddString(PreviewStringId.Msg_InvalidatePath, "Cannot find the specified path.");
            this.AddString(PreviewStringId.Msg_FileAlreadyExists, "The output file already exists. Click OK to overwrite.");
            this.AddString(PreviewStringId.Msg_EmptyUsefulPageSizeError, "Page margins are greater than page size.");
            this.AddString(PreviewStringId.Margin_Inch, "Inch");
            this.AddString(PreviewStringId.Margin_Millimeter, "mm");
            this.AddString(PreviewStringId.Margin_Pixel, "px");
            this.AddString(PreviewStringId.Margin_TopMargin, "Top Margin");
            this.AddString(PreviewStringId.Margin_BottomMargin, "Bottom Margin");
            this.AddString(PreviewStringId.Margin_LeftMargin, "Left Margin");
            this.AddString(PreviewStringId.Margin_RightMargin, "Right Margin");
            this.AddString(PreviewStringId.ScrollingInfo_Page, "Page");
            this.AddString(PreviewStringId.PrintDialog_Duplex_Simplex, "None");
            this.AddString(PreviewStringId.PrintDialog_Duplex_Vertical, "Flip on Long Edge");
            this.AddString(PreviewStringId.PrintDialog_Duplex_Horizontal, "Flip on Short Edge");
            this.AddString(PreviewStringId.WMForm_PictureDlg_Title, "Select Picture");
            this.AddString(PreviewStringId.WMForm_ImageStretch, "Stretch");
            this.AddString(PreviewStringId.WMForm_ImageClip, "Clip");
            this.AddString(PreviewStringId.WMForm_ImageZoom, "Zoom");
            this.AddString(PreviewStringId.WMForm_Watermark_Asap, "ASAP");
            this.AddString(PreviewStringId.WMForm_Watermark_Confidential, "CONFIDENTIAL");
            this.AddString(PreviewStringId.WMForm_Watermark_Copy, "COPY");
            this.AddString(PreviewStringId.WMForm_Watermark_DoNotCopy, "DO NOT COPY");
            this.AddString(PreviewStringId.WMForm_Watermark_Draft, "DRAFT");
            this.AddString(PreviewStringId.WMForm_Watermark_Evaluation, "EVALUATION");
            this.AddString(PreviewStringId.WMForm_Watermark_Original, "ORIGINAL");
            this.AddString(PreviewStringId.WMForm_Watermark_Personal, "PERSONAL");
            this.AddString(PreviewStringId.WMForm_Watermark_Sample, "SAMPLE");
            this.AddString(PreviewStringId.WMForm_Watermark_TopSecret, "TOP SECRET");
            this.AddString(PreviewStringId.WMForm_Watermark_Urgent, "URGENT");
            this.AddString(PreviewStringId.WMForm_Direction_Horizontal, "Horizontal");
            this.AddString(PreviewStringId.WMForm_Direction_Vertical, "Vertical");
            this.AddString(PreviewStringId.WMForm_Direction_BackwardDiagonal, "Backward Diagonal");
            this.AddString(PreviewStringId.WMForm_Direction_ForwardDiagonal, "Forward Diagonal");
            this.AddString(PreviewStringId.WMForm_VertAlign_Bottom, "Bottom");
            this.AddString(PreviewStringId.WMForm_VertAlign_Middle, "Middle");
            this.AddString(PreviewStringId.WMForm_VertAlign_Top, "Top");
            this.AddString(PreviewStringId.WMForm_HorzAlign_Left, "Left");
            this.AddString(PreviewStringId.WMForm_HorzAlign_Center, "Center");
            this.AddString(PreviewStringId.WMForm_HorzAlign_Right, "Right");
            this.AddString(PreviewStringId.SaveDlg_Title, "Save As");
            this.AddString(PreviewStringId.SaveDlg_FilterPdf, "PDF Document");
            this.AddString(PreviewStringId.SaveDlg_FilterHtm, "HTML Document");
            this.AddString(PreviewStringId.SaveDlg_FilterMht, "MHT Document");
            this.AddString(PreviewStringId.SaveDlg_FilterRtf, "Rich Text Document");
            this.AddString(PreviewStringId.SaveDlg_FilterDocx, "DOCX Document");
            this.AddString(PreviewStringId.SaveDlg_FilterXls, "XLS Document");
            this.AddString(PreviewStringId.SaveDlg_FilterXlsx, "XLSX Document");
            this.AddString(PreviewStringId.SaveDlg_FilterCsv, "CSV Document");
            this.AddString(PreviewStringId.SaveDlg_FilterTxt, "Text Document");
            this.AddString(PreviewStringId.SaveDlg_FilterNativeFormat, "Native Format");
            this.AddString(PreviewStringId.SaveDlg_FilterXps, "XPS Document");
            this.AddString(PreviewStringId.MenuItem_File, "&File");
            this.AddString(PreviewStringId.MenuItem_View, "&View");
            this.AddString(PreviewStringId.MenuItem_Background, "&Background");
            this.AddString(PreviewStringId.MenuItem_PageSetup, "Page Set&up...");
            this.AddString(PreviewStringId.MenuItem_Print, "&Print...");
            this.AddString(PreviewStringId.MenuItem_PrintDirect, "P&rint");
            this.AddString(PreviewStringId.MenuItem_Export, "&Export To");
            this.AddString(PreviewStringId.MenuItem_Send, "Sen&d As");
            this.AddString(PreviewStringId.MenuItem_Exit, "E&xit");
            this.AddString(PreviewStringId.MenuItem_ViewToolbar, "&Toolbar");
            this.AddString(PreviewStringId.MenuItem_ViewStatusbar, "&Statusbar");
            this.AddString(PreviewStringId.MenuItem_ViewContinuous, "&Continuous");
            this.AddString(PreviewStringId.MenuItem_ViewFacing, "&Facing");
            this.AddString(PreviewStringId.MenuItem_BackgrColor, "&Color...");
            this.AddString(PreviewStringId.MenuItem_Watermark, "&Watermark...");
            this.AddString(PreviewStringId.MenuItem_ZoomPageWidth, "Page Width");
            this.AddString(PreviewStringId.MenuItem_ZoomTextWidth, "Text Width");
            this.AddString(PreviewStringId.MenuItem_ZoomWholePage, "Whole Page");
            this.AddString(PreviewStringId.MenuItem_ZoomTwoPages, "Two Pages");
            this.AddString(PreviewStringId.MenuItem_Copy, "Copy");
            this.AddString(PreviewStringId.MenuItem_PrintSelection, "Print...");
            this.AddString(PreviewStringId.PageInfo_PageNumber, "[Page #]");
            this.AddString(PreviewStringId.PageInfo_PageNumberOfTotal, "[Page # of Pages #]");
            this.AddString(PreviewStringId.PageInfo_PageTotal, "[Pages #]");
            this.AddString(PreviewStringId.PageInfo_PageDate, "[Date Printed]");
            this.AddString(PreviewStringId.PageInfo_PageTime, "[Time Printed]");
            this.AddString(PreviewStringId.PageInfo_PageUserName, "[User Name]");
            this.AddString(PreviewStringId.EMail_From, "From");
            this.AddString(PreviewStringId.BarText_Toolbar, "Toolbar");
            this.AddString(PreviewStringId.BarText_MainMenu, "Main Menu");
            this.AddString(PreviewStringId.BarText_StatusBar, "Status Bar");
            this.AddString(PreviewStringId.ScalePopup_AdjustTo, "Adjust to");
            this.AddString(PreviewStringId.ScalePopup_NormalSize, "% of normal size");
            this.AddString(PreviewStringId.ScalePopup_FitTo, "Fit to");
            this.AddString(PreviewStringId.ScalePopup_PagesWide, "pages wide");
            this.AddString(PreviewStringId.ExportOption_PdfPageRange, "Page range:");
            this.AddString(PreviewStringId.ExportOption_PdfConvertImagesToJpeg, "Convert images to JPEG");
            this.AddString(PreviewStringId.ExportOption_PdfExportEditingFieldsToAcroForms, "Export editing fields to AcroForms");
            this.AddString(PreviewStringId.ExportOption_PdfShowPrintDialogOnOpen, "Show print dialog on open");
            this.AddString(PreviewStringId.ExportOption_PdfNeverEmbeddedFonts, "Don't embed these fonts:");
            this.AddString(PreviewStringId.ExportOption_PdfPasswordSecurityOptions, "Password security:");
            this.AddString(PreviewStringId.ExportOption_PdfSignatureOptions, "Digital signature:");
            this.AddString(PreviewStringId.ExportOption_PdfImageQuality, "Image quality:");
            this.AddString(PreviewStringId.ExportOption_PdfImageQuality_Lowest, "Lowest");
            this.AddString(PreviewStringId.ExportOption_PdfImageQuality_Low, "Low");
            this.AddString(PreviewStringId.ExportOption_PdfImageQuality_Medium, "Medium");
            this.AddString(PreviewStringId.ExportOption_PdfImageQuality_High, "High");
            this.AddString(PreviewStringId.ExportOption_PdfImageQuality_Highest, "Highest");
            this.AddString(PreviewStringId.ExportOption_PdfACompatibility, "PDF/A compatibility:");
            this.AddString(PreviewStringId.ExportOption_PdfACompatibility_None, "None");
            this.AddString(PreviewStringId.ExportOption_PdfACompatibility_PdfA1b, "PDF/A-1b");
            this.AddString(PreviewStringId.ExportOption_PdfACompatibility_PdfA2b, "PDF/A-2b");
            this.AddString(PreviewStringId.ExportOption_PdfACompatibility_PdfA3b, "PDF/A-3b");
            this.AddString(PreviewStringId.ExportOption_PdfDocumentAuthor, "Author:");
            this.AddString(PreviewStringId.ExportOption_PdfDocumentApplication, "Application:");
            this.AddString(PreviewStringId.ExportOption_PdfDocumentTitle, "Title:");
            this.AddString(PreviewStringId.ExportOption_PdfDocumentSubject, "Subject:");
            this.AddString(PreviewStringId.ExportOption_PdfDocumentKeywords, "Keywords:");
            this.AddString(PreviewStringId.ExportOption_PdfPrintingPermissions_None, "None");
            this.AddString(PreviewStringId.ExportOption_PdfPrintingPermissions_LowResolution, "Low Resolution (150 dpi)");
            this.AddString(PreviewStringId.ExportOption_PdfPrintingPermissions_HighResolution, "High Resolution");
            this.AddString(PreviewStringId.ExportOption_PdfChangingPermissions_None, "None");
            this.AddString(PreviewStringId.ExportOption_PdfChangingPermissions_InsertingDeletingRotating, "Inserting, deleting and rotating pages");
            this.AddString(PreviewStringId.ExportOption_PdfChangingPermissions_FillingSigning, "Filling in form fields and signing existing signature fields");
            this.AddString(PreviewStringId.ExportOption_PdfChangingPermissions_CommentingFillingSigning, "Commenting, filling in form fields, and signing existing signature fields");
            this.AddString(PreviewStringId.ExportOption_PdfChangingPermissions_AnyExceptExtractingPages, "Any except extracting pages");
            this.AddString(PreviewStringId.ExportOption_ConfirmOpenPasswordForm_Caption, "Confirm Document Open Password");
            this.AddString(PreviewStringId.ExportOption_ConfirmOpenPasswordForm_Note, "Please confirm the Document Open Password. Be sure to make a note of the password. It will be required to open the document.");
            this.AddString(PreviewStringId.ExportOption_ConfirmOpenPasswordForm_Name, "Document Open Pa&ssword:");
            this.AddString(PreviewStringId.ExportOption_ConfirmPermissionsPasswordForm_Caption, "Confirm Permissions Password");
            this.AddString(PreviewStringId.ExportOption_ConfirmPermissionsPasswordForm_Note, "Please confirm the Permissions Password. Be sure to make a note of the password. You will need it to change these settings in the future.");
            this.AddString(PreviewStringId.ExportOption_ConfirmPermissionsPasswordForm_Name, "&Permissions Password:");
            this.AddString(PreviewStringId.ExportOption_ConfirmationDoesNotMatchForm_Msg, "Confirmation password does not match. Please start over and enter the password again.");
            this.AddString(PreviewStringId.ExportOption_HtmlExportMode, "Export mode:");
            this.AddString(PreviewStringId.ExportOption_HtmlExportMode_SingleFile, "Single file");
            this.AddString(PreviewStringId.ExportOption_HtmlExportMode_SingleFilePageByPage, "Single file page-by-page");
            this.AddString(PreviewStringId.ExportOption_HtmlExportMode_DifferentFiles, "Different files");
            this.AddString(PreviewStringId.ExportOption_HtmlCharacterSet, "Character set:");
            this.AddString(PreviewStringId.ExportOption_HtmlTitle, "Title:");
            this.AddString(PreviewStringId.ExportOption_HtmlRemoveSecondarySymbols, "Remove carriage returns");
            this.AddString(PreviewStringId.ExportOption_HtmlEmbedImagesInHTML, "Embed images in HTML");
            this.AddString(PreviewStringId.ExportOption_HtmlPageRange, "Page range:");
            this.AddString(PreviewStringId.ExportOption_HtmlPageBorderWidth, "Page border width:");
            this.AddString(PreviewStringId.ExportOption_HtmlPageBorderColor, "Page border color:");
            this.AddString(PreviewStringId.ExportOption_HtmlTableLayout, "Table layout");
            this.AddString(PreviewStringId.ExportOption_HtmlExportWatermarks, "Export watermarks");
            this.AddString(PreviewStringId.ExportOption_RtfExportMode, "Export mode:");
            this.AddString(PreviewStringId.ExportOption_RtfExportMode_SingleFile, "Single file");
            this.AddString(PreviewStringId.ExportOption_RtfExportMode_SingleFilePageByPage, "Single file page-by-page");
            this.AddString(PreviewStringId.ExportOption_RtfPageRange, "Page range:");
            this.AddString(PreviewStringId.ExportOption_RtfExportWatermarks, "Export watermarks");
            this.AddString(PreviewStringId.ExportOption_DocxExportMode, "Export mode:");
            this.AddString(PreviewStringId.ExportOption_DocxExportMode_SingleFile, "Single file");
            this.AddString(PreviewStringId.ExportOption_DocxExportMode_SingleFilePageByPage, "Single file page-by-page");
            this.AddString(PreviewStringId.ExportOption_DocxPageRange, "Page range:");
            this.AddString(PreviewStringId.ExportOption_DocxTableLayout, "Table layout");
            this.AddString(PreviewStringId.ExportOption_DocxKeepRowHeight, "Keep row height");
            this.AddString(PreviewStringId.ExportOption_DocxExportWatermarks, "Export watermarks");
            this.AddString(PreviewStringId.ExportOption_TextSeparator, "Text separator:");
            this.AddString(PreviewStringId.ExportOption_TextSeparator_TabAlias, "TAB");
            this.AddString(PreviewStringId.ExportOption_TextEncoding, "Encoding:");
            this.AddString(PreviewStringId.ExportOption_TextQuoteStringsWithSeparators, "Quote strings with separators");
            this.AddString(PreviewStringId.ExportOption_TextExportMode, "Text export mode:");
            this.AddString(PreviewStringId.ExportOption_TextExportMode_Value, "Value");
            this.AddString(PreviewStringId.ExportOption_TextExportMode_Text, "Text");
            this.AddString(PreviewStringId.ExportOption_CsvSeparator_UsingSystem, "(Using System Separator)");
            this.AddString(PreviewStringId.ExportOption_XlsRawDataMode, "Raw data mode");
            this.AddString(PreviewStringId.ExportOption_XlsShowGridLines, "Show grid lines");
            this.AddString(PreviewStringId.ExportOption_XlsExportHyperlinks, "Export hyperlinks");
            this.AddString(PreviewStringId.ExportOption_XlsSheetName, "Sheet name:");
            this.AddString(PreviewStringId.ExportOption_XlsExportMode, "Export mode:");
            this.AddString(PreviewStringId.ExportOption_XlsExportMode_SingleFile, "Single file");
            this.AddString(PreviewStringId.ExportOption_XlsExportMode_SingleFilePageByPage, "Single file page-by-page");
            this.AddString(PreviewStringId.ExportOption_XlsExportMode_DifferentFiles, "Different files");
            this.AddString(PreviewStringId.ExportOption_XlsPageRange, "Page range:");
            this.AddString(PreviewStringId.ExportOption_XlsxExportMode, "Export mode:");
            this.AddString(PreviewStringId.ExportOption_XlsxExportMode_SingleFile, "Single file");
            this.AddString(PreviewStringId.ExportOption_XlsxExportMode_SingleFilePageByPage, "Single file page-by-page");
            this.AddString(PreviewStringId.ExportOption_XlsxExportMode_DifferentFiles, "Different files");
            this.AddString(PreviewStringId.ExportOption_XlsxPageRange, "Page range:");
            this.AddString(PreviewStringId.ExportOption_ImageExportMode, "Export mode:");
            this.AddString(PreviewStringId.ExportOption_ImageExportMode_SingleFile, "Single file");
            this.AddString(PreviewStringId.ExportOption_ImageExportMode_SingleFilePageByPage, "Single file page-by-page");
            this.AddString(PreviewStringId.ExportOption_ImageExportMode_DifferentFiles, "Different files");
            this.AddString(PreviewStringId.ExportOption_ImagePageRange, "Page range:");
            this.AddString(PreviewStringId.ExportOption_ImagePageBorderWidth, "Page border width:");
            this.AddString(PreviewStringId.ExportOption_ImagePageBorderColor, "Page border color:");
            this.AddString(PreviewStringId.ExportOption_ImageFormat, "Image format:");
            this.AddString(PreviewStringId.ExportOption_ImageResolution, "Resolution (dpi):");
            this.AddString(PreviewStringId.ExportOption_NativeFormatCompressed, "Compressed");
            this.AddString(PreviewStringId.ExportOption_XpsPageRange, "Page range:");
            this.AddString(PreviewStringId.ExportOption_XpsCompression, "Compression:");
            this.AddString(PreviewStringId.ExportOption_XpsCompression_NotCompressed, "Not compressed");
            this.AddString(PreviewStringId.ExportOption_XpsCompression_Normal, "Normal");
            this.AddString(PreviewStringId.ExportOption_XpsCompression_Maximum, "Maximum");
            this.AddString(PreviewStringId.ExportOption_XpsCompression_Fast, "Fast");
            this.AddString(PreviewStringId.ExportOption_XpsCompression_SuperFast, "Super fast");
            this.AddString(PreviewStringId.ExportOption_XpsDocumentCreator, "Creator:");
            this.AddString(PreviewStringId.ExportOption_XpsDocumentCategory, "Category:");
            this.AddString(PreviewStringId.ExportOption_XpsDocumentTitle, "Title:");
            this.AddString(PreviewStringId.ExportOption_XpsDocumentSubject, "Subject:");
            this.AddString(PreviewStringId.ExportOption_XpsDocumentKeywords, "Keywords:");
            this.AddString(PreviewStringId.ExportOption_XpsDocumentVersion, "Version:");
            this.AddString(PreviewStringId.ExportOption_XpsDocumentDescription, "Description:");
            this.AddString(PreviewStringId.FolderBrowseDlg_ExportDirectory, "Select a folder to save the exported document to:");
            this.AddString(PreviewStringId.ExportOptionsForm_CaptionPdf, "PDF Export Options");
            this.AddString(PreviewStringId.ExportOptionsForm_CaptionXls, "XLS Export Options");
            this.AddString(PreviewStringId.ExportOptionsForm_CaptionXlsx, "XLSX Export Options");
            this.AddString(PreviewStringId.ExportOptionsForm_CaptionTxt, "Text Export Options");
            this.AddString(PreviewStringId.ExportOptionsForm_CaptionCsv, "CSV Export Options");
            this.AddString(PreviewStringId.ExportOptionsForm_CaptionImage, "Image Export Options");
            this.AddString(PreviewStringId.ExportOptionsForm_CaptionHtml, "HTML Export Options");
            this.AddString(PreviewStringId.ExportOptionsForm_CaptionMht, "MHT Export Options");
            this.AddString(PreviewStringId.ExportOptionsForm_CaptionRtf, "RTF Export Options");
            this.AddString(PreviewStringId.ExportOptionsForm_CaptionDocx, "DOCX Export Options");
            this.AddString(PreviewStringId.ExportOptionsForm_CaptionNativeOptions, "Native Format Options");
            this.AddString(PreviewStringId.ExportOptionsForm_CaptionXps, "XPS Export Options");
            this.AddString(PreviewStringId.RibbonPreview_PageText, "Print Preview");
            this.AddString(PreviewStringId.RibbonPreview_PageGroup_Print, "Print");
            this.AddString(PreviewStringId.RibbonPreview_PageGroup_PageSetup, "Page Setup");
            this.AddString(PreviewStringId.RibbonPreview_PageGroup_Navigation, "Navigation");
            this.AddString(PreviewStringId.RibbonPreview_PageGroup_Zoom, "Zoom");
            this.AddString(PreviewStringId.RibbonPreview_PageGroup_Background, "Page Background");
            this.AddString(PreviewStringId.RibbonPreview_PageGroup_Export, "Export");
            this.AddString(PreviewStringId.RibbonPreview_PageGroup_Document, "Document");
            this.AddString(PreviewStringId.RibbonPreview_PageGroup_Close, "Close");
            this.AddString(PreviewStringId.RibbonPreview_DocumentMap_Caption, "Bookmarks");
            this.AddString(PreviewStringId.RibbonPreview_Parameters_Caption, "Parameters");
            this.AddString(PreviewStringId.RibbonPreview_Find_Caption, "Find");
            this.AddString(PreviewStringId.RibbonPreview_Pointer_Caption, "Pointer");
            this.AddString(PreviewStringId.RibbonPreview_HandTool_Caption, "Hand Tool");
            this.AddString(PreviewStringId.RibbonPreview_Customize_Caption, "Options");
            this.AddString(PreviewStringId.RibbonPreview_Print_Caption, "Print");
            this.AddString(PreviewStringId.RibbonPreview_PrintDirect_Caption, "Quick Print");
            this.AddString(PreviewStringId.RibbonPreview_PageSetup_Caption, "Custom Margins...");
            this.AddString(PreviewStringId.RibbonPreview_EditPageHF_Caption, "Header/Footer");
            this.AddString(PreviewStringId.RibbonPreview_Magnifier_Caption, "Magnifier");
            this.AddString(PreviewStringId.RibbonPreview_ZoomOut_Caption, "Zoom Out");
            this.AddString(PreviewStringId.RibbonPreview_ZoomExact_Caption, "Exact:");
            this.AddString(PreviewStringId.RibbonPreview_ZoomIn_Caption, "Zoom In");
            this.AddString(PreviewStringId.RibbonPreview_ShowFirstPage_Caption, "First Page");
            this.AddString(PreviewStringId.RibbonPreview_ShowPrevPage_Caption, "Previous Page");
            this.AddString(PreviewStringId.RibbonPreview_ShowNextPage_Caption, "Next  Page ");
            this.AddString(PreviewStringId.RibbonPreview_ShowLastPage_Caption, "Last  Page ");
            this.AddString(PreviewStringId.RibbonPreview_MultiplePages_Caption, "Many Pages");
            this.AddString(PreviewStringId.RibbonPreview_FillBackground_Caption, "Page Color");
            this.AddString(PreviewStringId.RibbonPreview_Watermark_Caption, "Watermark");
            this.AddString(PreviewStringId.RibbonPreview_ExportFile_Caption, "Export To");
            this.AddString(PreviewStringId.RibbonPreview_SendFile_Caption, "E-Mail As");
            this.AddString(PreviewStringId.RibbonPreview_ClosePreview_Caption, "Close");
            this.AddString(PreviewStringId.RibbonPreview_Scale_Caption, "Scale");
            this.AddString(PreviewStringId.RibbonPreview_PageOrientation_Caption, "Orientation");
            this.AddString(PreviewStringId.RibbonPreview_PaperSize_Caption, "Size");
            this.AddString(PreviewStringId.RibbonPreview_PageMargins_Caption, "Margins");
            this.AddString(PreviewStringId.RibbonPreview_Zoom_Caption, "Zoom");
            this.AddString(PreviewStringId.RibbonPreview_Save_Caption, "Save");
            this.AddString(PreviewStringId.RibbonPreview_Open_Caption, "Open");
            this.AddString(PreviewStringId.RibbonPreview_Thumbnails_Caption, "Thumbnails");
            this.AddString(PreviewStringId.RibbonPreview_HighlightEditingFields_Caption, "Editing Fields");
            this.AddString(PreviewStringId.RibbonPreview_DocumentMap_STipTitle, "Document Map");
            this.AddString(PreviewStringId.RibbonPreview_Parameters_STipTitle, "Parameters");
            this.AddString(PreviewStringId.RibbonPreview_Find_STipTitle, "Find");
            this.AddString(PreviewStringId.RibbonPreview_Pointer_STipTitle, "Mouse Pointer");
            this.AddString(PreviewStringId.RibbonPreview_HandTool_STipTitle, "Hand Tool");
            this.AddString(PreviewStringId.RibbonPreview_Customize_STipTitle, "Options");
            this.AddString(PreviewStringId.RibbonPreview_Print_STipTitle, "Print (Ctrl+P)");
            this.AddString(PreviewStringId.RibbonPreview_PrintDirect_STipTitle, "Quick Print");
            this.AddString(PreviewStringId.RibbonPreview_PageSetup_STipTitle, "Page Setup");
            this.AddString(PreviewStringId.RibbonPreview_EditPageHF_STipTitle, "Header and Footer");
            this.AddString(PreviewStringId.RibbonPreview_Magnifier_STipTitle, "Magnifier");
            this.AddString(PreviewStringId.RibbonPreview_ZoomOut_STipTitle, "Zoom Out");
            this.AddString(PreviewStringId.RibbonPreview_ZoomIn_STipTitle, "Zoom In");
            this.AddString(PreviewStringId.RibbonPreview_ShowFirstPage_STipTitle, "First Page (Home)");
            this.AddString(PreviewStringId.RibbonPreview_ShowPrevPage_STipTitle, "Previous Page (Left Arrow)");
            this.AddString(PreviewStringId.RibbonPreview_ShowNextPage_STipTitle, "Next Page (Right Arrow)");
            this.AddString(PreviewStringId.RibbonPreview_ShowLastPage_STipTitle, "Last Page (End)");
            this.AddString(PreviewStringId.RibbonPreview_MultiplePages_STipTitle, "View Many Pages");
            this.AddString(PreviewStringId.RibbonPreview_FillBackground_STipTitle, "Background Color");
            this.AddString(PreviewStringId.RibbonPreview_Watermark_STipTitle, "Watermark");
            this.AddString(PreviewStringId.RibbonPreview_ExportFile_STipTitle, "Export To...");
            this.AddString(PreviewStringId.RibbonPreview_SendFile_STipTitle, "E-Mail As...");
            this.AddString(PreviewStringId.RibbonPreview_ClosePreview_STipTitle, "Close Print Preview");
            this.AddString(PreviewStringId.RibbonPreview_Scale_STipTitle, "Scale");
            this.AddString(PreviewStringId.RibbonPreview_PageOrientation_STipTitle, "Page Orientation");
            this.AddString(PreviewStringId.RibbonPreview_PaperSize_STipTitle, "Page Size");
            this.AddString(PreviewStringId.RibbonPreview_PageMargins_STipTitle, "Page Margins");
            this.AddString(PreviewStringId.RibbonPreview_Zoom_STipTitle, "Zoom");
            this.AddString(PreviewStringId.RibbonPreview_PageGroup_PageSetup_STipTitle, "Page Setup");
            this.AddString(PreviewStringId.RibbonPreview_Save_STipTitle, "Save (Ctrl + S)");
            this.AddString(PreviewStringId.RibbonPreview_Open_STipTitle, "Open (Ctrl + O)");
            this.AddString(PreviewStringId.RibbonPreview_Thumbnails_STipTitle, "Thumbnails");
            this.AddString(PreviewStringId.RibbonPreview_HighlightEditingFields_STipTitle, "Highlight Editing Fields");
            this.AddString(PreviewStringId.RibbonPreview_DocumentMap_STipContent, "Open the Document Map, which allows you to navigate through a structural view of the document.");
            this.AddString(PreviewStringId.RibbonPreview_Parameters_STipContent, "Open the Parameters pane, which allows you to enter values for report parameters.");
            this.AddString(PreviewStringId.RibbonPreview_Find_STipContent, "Show the Find dialog to find text in the document.");
            this.AddString(PreviewStringId.RibbonPreview_Pointer_STipContent, "Show the mouse pointer.");
            this.AddString(PreviewStringId.RibbonPreview_HandTool_STipContent, "Invoke the Hand tool to manually scroll through pages.");
            this.AddString(PreviewStringId.RibbonPreview_Customize_STipContent, "Open the Print Options dialog, in which you can change printing options.");
            this.AddString(PreviewStringId.RibbonPreview_Print_STipContent, "Select a printer, number of copies and other printing options before printing.");
            this.AddString(PreviewStringId.RibbonPreview_PrintDirect_STipContent, "Send the document directly to the default printer without making changes.");
            this.AddString(PreviewStringId.RibbonPreview_PageSetup_STipContent, "Show the Page Setup dialog.");
            this.AddString(PreviewStringId.RibbonPreview_EditPageHF_STipContent, "Edit the header and footer of the document.");
            this.AddString(PreviewStringId.RibbonPreview_Magnifier_STipContent, "Invoke the Magnifier tool.\r\n\r\nClicking once on a document zooms it so that a single page becomes entirely visible, while clicking another time zooms it to 100% of the normal size.");
            this.AddString(PreviewStringId.RibbonPreview_ZoomOut_STipContent, "Zoom out to see more of the page at a reduced size.");
            this.AddString(PreviewStringId.RibbonPreview_ZoomIn_STipContent, "Zoom in to get a close-up view of the document.");
            this.AddString(PreviewStringId.RibbonPreview_ShowFirstPage_STipContent, "Navigate to the first page of the document.");
            this.AddString(PreviewStringId.RibbonPreview_ShowPrevPage_STipContent, "Navigate to the previous page of the document.");
            this.AddString(PreviewStringId.RibbonPreview_ShowNextPage_STipContent, "Navigate to the next page of the document.");
            this.AddString(PreviewStringId.RibbonPreview_ShowLastPage_STipContent, "Navigate to the last page of the document.");
            this.AddString(PreviewStringId.RibbonPreview_MultiplePages_STipContent, "Choose the page layout to arrange the document pages in preview.");
            this.AddString(PreviewStringId.RibbonPreview_FillBackground_STipContent, "Choose a color for the background of the document pages.");
            this.AddString(PreviewStringId.RibbonPreview_Watermark_STipContent, "Insert ghosted text or image behind the content of a page.\r\n\r\nThis is often used to indicate that a document is to be treated specially.");
            this.AddString(PreviewStringId.RibbonPreview_ExportFile_STipContent, "Export the current document in one of the available formats, and save it to the file on a disk.");
            this.AddString(PreviewStringId.RibbonPreview_SendFile_STipContent, "Export the current document in one of the available formats, and attach it to the e-mail.");
            this.AddString(PreviewStringId.RibbonPreview_ClosePreview_STipContent, "Close Print Preview of the document.");
            this.AddString(PreviewStringId.RibbonPreview_Scale_STipContent, "Stretch or shrink the printed output to a percentage of its actual size.");
            this.AddString(PreviewStringId.RibbonPreview_PageOrientation_STipContent, "Switch the pages between portrait and landscape layouts.");
            this.AddString(PreviewStringId.RibbonPreview_PaperSize_STipContent, "Choose the paper size of the document.");
            this.AddString(PreviewStringId.RibbonPreview_PageMargins_STipContent, "Select the margin sizes for the entire document.\r\n\r\nTo apply specific margin sizes to the document, click Custom Margins.");
            this.AddString(PreviewStringId.RibbonPreview_Zoom_STipContent, "Change the zoom level of the document preview.");
            this.AddString(PreviewStringId.RibbonPreview_PageGroup_PageSetup_STipContent, "Show the Page Setup dialog.");
            this.AddString(PreviewStringId.RibbonPreview_Save_STipContent, "Save the document.");
            this.AddString(PreviewStringId.RibbonPreview_Open_STipContent, "Open a document.");
            this.AddString(PreviewStringId.RibbonPreview_Thumbnails_STipContent, "Open the Thumbnails, which allows you to navigate through the document.");
            this.AddString(PreviewStringId.RibbonPreview_HighlightEditingFields_STipContent, "Highlight all editing fields to quickly discover which of the document elements are editable.");
            this.AddString(PreviewStringId.RibbonPreview_ExportPdf_Caption, "PDF File");
            this.AddString(PreviewStringId.RibbonPreview_ExportHtm_Caption, "HTML File");
            this.AddString(PreviewStringId.RibbonPreview_ExportMht_Caption, "MHT File");
            this.AddString(PreviewStringId.RibbonPreview_ExportRtf_Caption, "RTF File");
            this.AddString(PreviewStringId.RibbonPreview_ExportDocx_Caption, "DOCX File");
            this.AddString(PreviewStringId.RibbonPreview_ExportXls_Caption, "XLS File");
            this.AddString(PreviewStringId.RibbonPreview_ExportXlsx_Caption, "XLSX File");
            this.AddString(PreviewStringId.RibbonPreview_ExportCsv_Caption, "CSV File");
            this.AddString(PreviewStringId.RibbonPreview_ExportTxt_Caption, "Text File");
            this.AddString(PreviewStringId.RibbonPreview_ExportGraphic_Caption, "Image File");
            this.AddString(PreviewStringId.RibbonPreview_ExportXps_Caption, "XPS File");
            this.AddString(PreviewStringId.RibbonPreview_SendPdf_Caption, "PDF File");
            this.AddString(PreviewStringId.RibbonPreview_SendMht_Caption, "MHT File");
            this.AddString(PreviewStringId.RibbonPreview_SendRtf_Caption, "RTF File");
            this.AddString(PreviewStringId.RibbonPreview_SendDocx_Caption, "DOCX File");
            this.AddString(PreviewStringId.RibbonPreview_SendXls_Caption, "XLS File");
            this.AddString(PreviewStringId.RibbonPreview_SendXlsx_Caption, "XLSX File");
            this.AddString(PreviewStringId.RibbonPreview_SendCsv_Caption, "CSV File");
            this.AddString(PreviewStringId.RibbonPreview_SendTxt_Caption, "Text File");
            this.AddString(PreviewStringId.RibbonPreview_SendGraphic_Caption, "Image File");
            this.AddString(PreviewStringId.RibbonPreview_SendXps_Caption, "XPS File");
            this.AddString(PreviewStringId.RibbonPreview_ExportPdf_Description, "Adobe Portable Document Format");
            this.AddString(PreviewStringId.RibbonPreview_ExportHtm_Description, "Web Page");
            this.AddString(PreviewStringId.RibbonPreview_ExportTxt_Description, "Plain Text");
            this.AddString(PreviewStringId.RibbonPreview_ExportCsv_Description, "Comma-Separated Values Text");
            this.AddString(PreviewStringId.RibbonPreview_ExportMht_Description, "Single File Web Page");
            this.AddString(PreviewStringId.RibbonPreview_ExportXls_Description, "Microsoft Excel 2000-2003 Workbook");
            this.AddString(PreviewStringId.RibbonPreview_ExportXlsx_Description, "Microsoft Excel 2007 Workbook");
            this.AddString(PreviewStringId.RibbonPreview_ExportRtf_Description, "Rich Text Format");
            this.AddString(PreviewStringId.RibbonPreview_ExportDocx_Description, "Microsoft Word 2007 Document");
            this.AddString(PreviewStringId.RibbonPreview_ExportGraphic_Description, "BMP, GIF, JPEG, PNG, TIFF, EMF, WMF");
            this.AddString(PreviewStringId.RibbonPreview_ExportXps_Description, "XPS");
            this.AddString(PreviewStringId.RibbonPreview_SendPdf_Description, "Adobe Portable Document Format");
            this.AddString(PreviewStringId.RibbonPreview_SendTxt_Description, "Plain Text");
            this.AddString(PreviewStringId.RibbonPreview_SendCsv_Description, "Comma-Separated Values Text");
            this.AddString(PreviewStringId.RibbonPreview_SendMht_Description, "Single File Web Page");
            this.AddString(PreviewStringId.RibbonPreview_SendXls_Description, "Microsoft Excel 2000-2003 Workbook");
            this.AddString(PreviewStringId.RibbonPreview_SendXlsx_Description, "Microsoft Excel 2007 Workbook");
            this.AddString(PreviewStringId.RibbonPreview_SendRtf_Description, "Rich Text Format");
            this.AddString(PreviewStringId.RibbonPreview_SendDocx_Description, "Microsoft Word 2007 Document");
            this.AddString(PreviewStringId.RibbonPreview_SendGraphic_Description, "BMP, GIF, JPEG, PNG, TIFF, EMF, WMF");
            this.AddString(PreviewStringId.RibbonPreview_SendXps_Description, "XPS");
            this.AddString(PreviewStringId.RibbonPreview_ExportPdf_STipTitle, "Export to PDF");
            this.AddString(PreviewStringId.RibbonPreview_ExportHtm_STipTitle, "Export to HTML");
            this.AddString(PreviewStringId.RibbonPreview_ExportTxt_STipTitle, "Export to Text");
            this.AddString(PreviewStringId.RibbonPreview_ExportCsv_STipTitle, "Export to CSV");
            this.AddString(PreviewStringId.RibbonPreview_ExportMht_STipTitle, "Export to MHT");
            this.AddString(PreviewStringId.RibbonPreview_ExportXls_STipTitle, "Export to XLS");
            this.AddString(PreviewStringId.RibbonPreview_ExportXlsx_STipTitle, "Export to XLSX");
            this.AddString(PreviewStringId.RibbonPreview_ExportRtf_STipTitle, "Export to RTF");
            this.AddString(PreviewStringId.RibbonPreview_ExportDocx_STipTitle, "Export to DOCX");
            this.AddString(PreviewStringId.RibbonPreview_ExportGraphic_STipTitle, "Export to Image");
            this.AddString(PreviewStringId.RibbonPreview_SendPdf_STipTitle, "E-Mail As PDF");
            this.AddString(PreviewStringId.RibbonPreview_SendTxt_STipTitle, "E-Mail As Text");
            this.AddString(PreviewStringId.RibbonPreview_SendCsv_STipTitle, "E-Mail As CSV");
            this.AddString(PreviewStringId.RibbonPreview_SendMht_STipTitle, "E-Mail As MHT");
            this.AddString(PreviewStringId.RibbonPreview_SendXls_STipTitle, "E-Mail As XLS");
            this.AddString(PreviewStringId.RibbonPreview_SendXlsx_STipTitle, "E-Mail As XLSX");
            this.AddString(PreviewStringId.RibbonPreview_SendRtf_STipTitle, "E-Mail As RTF");
            this.AddString(PreviewStringId.RibbonPreview_SendDocx_STipTitle, "E-Mail As DOCX");
            this.AddString(PreviewStringId.RibbonPreview_SendGraphic_STipTitle, "E-Mail As Image");
            this.AddString(PreviewStringId.RibbonPreview_ExportPdf_STipContent, "Export the document to PDF and save it to the file on a disk.");
            this.AddString(PreviewStringId.RibbonPreview_ExportHtm_STipContent, "Export the document to HTML and save it to the file on a disk.");
            this.AddString(PreviewStringId.RibbonPreview_ExportTxt_STipContent, "Export the document to Text and save it to the file on a disk.");
            this.AddString(PreviewStringId.RibbonPreview_ExportCsv_STipContent, "Export the document to CSV and save it to the file on a disk.");
            this.AddString(PreviewStringId.RibbonPreview_ExportMht_STipContent, "Export the document to MHT and save it to the file on a disk.");
            this.AddString(PreviewStringId.RibbonPreview_ExportXls_STipContent, "Export the document to XLS and save it to the file on a disk.");
            this.AddString(PreviewStringId.RibbonPreview_ExportXlsx_STipContent, "Export the document to XLSX and save it to the file on a disk.");
            this.AddString(PreviewStringId.RibbonPreview_ExportRtf_STipContent, "Export the document to RTF and save it to the file on a disk.");
            this.AddString(PreviewStringId.RibbonPreview_ExportDocx_STipContent, "Export the document to DOCX and save it to the file on a disk.");
            this.AddString(PreviewStringId.RibbonPreview_ExportGraphic_STipContent, "Export the document to Image and save it to the file on a disk.");
            this.AddString(PreviewStringId.RibbonPreview_SendPdf_STipContent, "Export the document to PDF and attach it to the e-mail.");
            this.AddString(PreviewStringId.RibbonPreview_SendTxt_STipContent, "Export the document to Text and attach it to the e-mail.");
            this.AddString(PreviewStringId.RibbonPreview_SendCsv_STipContent, "Export the document to CSV and attach it to the e-mail.");
            this.AddString(PreviewStringId.RibbonPreview_SendMht_STipContent, "Export the document to MHT and attach it to the e-mail.");
            this.AddString(PreviewStringId.RibbonPreview_SendXls_STipContent, "Export the document to XLS and attach it to the e-mail.");
            this.AddString(PreviewStringId.RibbonPreview_SendXlsx_STipContent, "Export the document to XLSX and attach it to the e-mail.");
            this.AddString(PreviewStringId.RibbonPreview_SendRtf_STipContent, "Export the document to RTF and attach it to the e-mail.");
            this.AddString(PreviewStringId.RibbonPreview_SendDocx_STipContent, "Export the document to DOCX and attach it to the e-mail.");
            this.AddString(PreviewStringId.RibbonPreview_SendGraphic_STipContent, "Export the document to Image and attach it to the e-mail.");
            this.AddString(PreviewStringId.RibbonPreview_GalleryItem_PageOrientationPortrait_Caption, "Portrait");
            this.AddString(PreviewStringId.RibbonPreview_GalleryItem_PageOrientationLandscape_Caption, "Landscape");
            this.AddString(PreviewStringId.RibbonPreview_GalleryItem_PageMarginsNormal_Caption, "Normal");
            this.AddString(PreviewStringId.RibbonPreview_GalleryItem_PageMarginsNarrow_Caption, "Narrow");
            this.AddString(PreviewStringId.RibbonPreview_GalleryItem_PageMarginsModerate_Caption, "Moderate");
            this.AddString(PreviewStringId.RibbonPreview_GalleryItem_PageMarginsWide_Caption, "Wide");
            this.AddString(PreviewStringId.RibbonPreview_GalleryItem_PageOrientationPortrait_Description, "");
            this.AddString(PreviewStringId.RibbonPreview_GalleryItem_PageOrientationLandscape_Description, "");
            this.AddString(PreviewStringId.RibbonPreview_GalleryItem_PageMarginsNormal_Description, "Normal");
            this.AddString(PreviewStringId.RibbonPreview_GalleryItem_PageMarginsNarrow_Description, "Narrow");
            this.AddString(PreviewStringId.RibbonPreview_GalleryItem_PageMarginsModerate_Description, "Moderate");
            this.AddString(PreviewStringId.RibbonPreview_GalleryItem_PageMarginsWide_Description, "Wide");
            this.AddString(PreviewStringId.RibbonPreview_GalleryItem_PageMargins_Description, "Top:\t\t{0}\t\tBottom:\t\t{1}\r\nLeft:\t\t {2}\t\tRight:\t\t   {3}");
            this.AddString(PreviewStringId.RibbonPreview_GalleryItem_PaperSize_Description, "{0} x {1}");
            this.AddString(PreviewStringId.OpenFileDialog_Filter, "Preview Document Files (*{0})|*{0}|All Files (*.*)|*.*");
            this.AddString(PreviewStringId.OpenFileDialog_Title, "Open");
            this.AddString(PreviewStringId.ExportOption_PdfPasswordSecurityOptions_DocumentOpenPassword, "Document Open Password");
            this.AddString(PreviewStringId.ExportOption_PdfPasswordSecurityOptions_Permissions, "Permissions");
            this.AddString(PreviewStringId.ExportOption_PdfPasswordSecurityOptions_None, "(none)");
            this.AddString(PreviewStringId.ParametersRequest_Submit, "Submit");
            this.AddString(PreviewStringId.ParametersRequest_Reset, "Reset");
            this.AddString(PreviewStringId.ParametersRequest_Caption, "Parameters");
            this.AddString(PreviewStringId.ParametersRequest_NullValuePrompt, "(none)");
            this.AddString(PreviewStringId.ParametersRequest_AllMultiValuesFormat, "{0} selected (All)");
            this.AddString(PreviewStringId.ParametersRequest_SelectedMultiValuesFormat, "{0} selected");
            this.AddString(PreviewStringId.NoneString, "(none)");
            this.AddString(PreviewStringId.WatermarkTypePicture, "(Picture)");
            this.AddString(PreviewStringId.WatermarkTypeText, "(Text)");
            this.AddString(PreviewStringId.ParameterLookUpSettingsNoLookUp, "No Look-Up");
            this.AddString(PreviewStringId.ParameterRangeSettingsNoRange, "No Range");
            this.AddString(PreviewStringId.ExportOption_PdfSignatureOptions_Certificate, "Certificate");
            this.AddString(PreviewStringId.ExportOption_PdfSignatureOptions_Reason, "Reason");
            this.AddString(PreviewStringId.ExportOption_PdfSignatureOptions_Location, "Location");
            this.AddString(PreviewStringId.ExportOption_PdfSignatureOptions_ContactInfo, "Contact Info");
            this.AddString(PreviewStringId.ExportOption_PdfSignatureOptions_None, "(none)");
            this.AddString(PreviewStringId.ExportOption_PdfSignature_EmptyCertificate, "None");
            this.AddString(PreviewStringId.ExportOption_PdfSignature_Issuer, "Issuer: ");
            this.AddString(PreviewStringId.ExportOption_PdfSignature_ValidRange, "Valid From: {0:d} to {1:d}");
            this.AddString(PreviewStringId.NetworkPrinterFormat, "{0} on {1}");
            this.AddString(PreviewStringId.PrinterStatus_Busy, "The printer is busy.");
            this.AddString(PreviewStringId.PrinterStatus_DoorOpen, "The printer door is open.");
            this.AddString(PreviewStringId.PrinterStatus_DriverUpdateNeeded, "The printer driver needs to be updated.");
            this.AddString(PreviewStringId.PrinterStatus_Error, "Error");
            this.AddString(PreviewStringId.PrinterStatus_Initializing, "Initializing the Preview...");
            this.AddString(PreviewStringId.PrinterStatus_IOActive, "The printer's input/output is active.");
            this.AddString(PreviewStringId.PrinterStatus_ManualFeed, "The manual feed is enabled.");
            this.AddString(PreviewStringId.PrinterStatus_NotAvailable, "The printer is not available.");
            this.AddString(PreviewStringId.PrinterStatus_NoToner, "The printer has no toner.");
            this.AddString(PreviewStringId.PrinterStatus_Offline, "The printer is offline.");
            this.AddString(PreviewStringId.PrinterStatus_OutOfMemory, "The printer is out of memory.");
            this.AddString(PreviewStringId.PrinterStatus_OutputBinFull, "The output bin is full.");
            this.AddString(PreviewStringId.PrinterStatus_PagePunt, "A page punt has occurred.");
            this.AddString(PreviewStringId.PrinterStatus_PaperJam, "The paper has jammed.");
            this.AddString(PreviewStringId.PrinterStatus_PaperOut, "The printer is out of paper.");
            this.AddString(PreviewStringId.PrinterStatus_PaperProblem, "A paper-related problem has occurred.");
            this.AddString(PreviewStringId.PrinterStatus_Paused, "The printer is paused.");
            this.AddString(PreviewStringId.PrinterStatus_PendingDeletion, "Print task deletion is pending.");
            this.AddString(PreviewStringId.PrinterStatus_PowerSave, "The power save mode is on.");
            this.AddString(PreviewStringId.PrinterStatus_Printing, "Printing...");
            this.AddString(PreviewStringId.PrinterStatus_Processing, "Processing...");
            this.AddString(PreviewStringId.PrinterStatus_Ready, "The printer is ready.");
            this.AddString(PreviewStringId.PrinterStatus_ServerOffline, "The server is offline.");
            this.AddString(PreviewStringId.PrinterStatus_ServerUnknown, "The server is unknown.");
            this.AddString(PreviewStringId.PrinterStatus_TonerLow, "The toner is low.");
            this.AddString(PreviewStringId.PrinterStatus_UserIntervention, "A user intervention has occurred.");
            this.AddString(PreviewStringId.PrinterStatus_Waiting, "Waiting...");
            this.AddString(PreviewStringId.PrinterStatus_WarmingUp, "The printer is warming up.");
            this.AddString(PreviewStringId.EditingFieldEditors_Integer, "Integer");
            this.AddString(PreviewStringId.EditingFieldEditors_IntegerPositive, "Integer Positive");
            this.AddString(PreviewStringId.EditingFieldEditors_FixedPoint, "Fixed-Point");
            this.AddString(PreviewStringId.EditingFieldEditors_FixedPointPositive, "Fixed-Point Positive");
            this.AddString(PreviewStringId.EditingFieldEditors_Date, "Date");
            this.AddString(PreviewStringId.EditingFieldEditors_OnlyLetters, "Only Letters");
            this.AddString(PreviewStringId.EditingFieldEditors_OnlyUppercaseLetters, "Only Uppercase Letters");
            this.AddString(PreviewStringId.EditingFieldEditors_OnlyLowercaseLetters, "Only Lowercase Letters");
            this.AddString(PreviewStringId.EditingFieldEditors_OnlyLatinLetters, "Only Latin Letters");
            this.AddString(PreviewStringId.EditingFieldEditors_Image, "Image");
            this.AddString(PreviewStringId.EditingFieldEditors_Signature, "Signature");
            this.AddString(PreviewStringId.EditingFieldEditors_ImageAndSignature, "Image and Signature");
            this.AddString(PreviewStringId.EditingFieldEditorCategories_Numeric, "Numeric");
            this.AddString(PreviewStringId.EditingFieldEditorCategories_DateTime, "Date-Time");
            this.AddString(PreviewStringId.EditingFieldEditorCategories_Letters, "Letters");
            this.AddString(PreviewStringId.ImageEditingFieldEditor_LoadImage, "Load Image");
            this.AddString(PreviewStringId.ImageEditingFieldEditor_ChooseImage, "Choose Image");
            this.AddString(PreviewStringId.ImageEditingFieldEditor_SizeModeAndAlignment, "Size Mode And Alignment");
            this.AddString(PreviewStringId.ImageEditingFieldEditor_BrushOptions, "Brush Options");
            this.AddString(PreviewStringId.ImageEditingFieldEditor_Reset, "Reset");
            this.AddString(PreviewStringId.ImageEditingFieldEditor_Clear, "Clear");
            this.AddString(PreviewStringId.ImageEditingFieldEditor_SizeMode, "Size Mode");
            this.AddString(PreviewStringId.ImageEditingFieldEditor_Alignment, "Alignment");
            this.AddString(PreviewStringId.ImageEditingFieldEditor_BrushSize, "Brush Size");
            this.AddString(PreviewStringId.ImageEditingFieldEditor_BrushColor, "Brush Color");
            this.AddString(PreviewStringId.DateRangeParameterEditor_Today, "Today");
            this.AddString(PreviewStringId.DateRangeParameterEditor_Yesterday, "Yesterday");
            this.AddString(PreviewStringId.DateRangeParameterEditor_CurrentWeek, "Current Week");
            this.AddString(PreviewStringId.DateRangeParameterEditor_LastWeek, "Last Week");
            this.AddString(PreviewStringId.DateRangeParameterEditor_PreviousWeek, "Previous Week");
            this.AddString(PreviewStringId.DateRangeParameterEditor_Last7Days, "Last 7 Days");
            this.AddString(PreviewStringId.DateRangeParameterEditor_CurrentMonth, "Current Month");
            this.AddString(PreviewStringId.DateRangeParameterEditor_LastMonth, "Last Month");
            this.AddString(PreviewStringId.DateRangeParameterEditor_PreviousMonth, "Previous Month");
            this.AddString(PreviewStringId.DateRangeParameterEditor_CurrentQuarter, "Current Quarter");
            this.AddString(PreviewStringId.DateRangeParameterEditor_PreviousQuarter, "Previous Quarter");
            this.AddString(PreviewStringId.DateRangeParameterEditor_CurrentYear, "Current Year");
            this.AddString(PreviewStringId.DateRangeParameterEditor_LastYear, "Last Year");
            this.AddString(PreviewStringId.DateRangeParameterEditor_PreviousYear, "Previous Year");
        }

        public static XtraLocalizer<PreviewStringId> CreateDefaultLocalizer() => 
            new PreviewResLocalizer();

        public override XtraLocalizer<PreviewStringId> CreateResXLocalizer() => 
            new PreviewResLocalizer();

        public static string GetString(PreviewStringId id) => 
            Active.GetLocalizedString(id);

        protected override void PopulateStringTable()
        {
            this.AddStrings();
        }

        public static XtraLocalizer<PreviewStringId> Active
        {
            get => 
                XtraLocalizer<PreviewStringId>.Active;
            set => 
                XtraLocalizer<PreviewStringId>.Active = value;
        }
    }
}

