namespace DevExpress.XtraPrinting.Localization
{
    using System;
    using System.ComponentModel;

    public enum PreviewStringId
    {
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You shouldn't use the 'EmptyString' member"), DXHelpExclude(true)]
        EmptyString = 0,
        Button_Cancel = 1,
        Button_Ok = 2,
        Button_Help = 3,
        Button_Apply = 4,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'PreviewForm_Caption' member"), DXHelpExclude(true)]
        PPF_Preview_Caption = 5,
        PreviewForm_Caption = 6,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'TB_TTip_Customize' member"), DXHelpExclude(true)]
        TB_CustomizeBtn_ToolTip = 7,
        TB_TTip_Customize = 8,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'TB_TTip_Print' member"), DXHelpExclude(true)]
        TB_PrintBtn_ToolTip = 9,
        TB_TTip_Print = 10,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'TB_TTip_PrintDirect' member"), DXHelpExclude(true)]
        TB_PrintDirectBtn_ToolTip = 11,
        TB_TTip_PrintDirect = 12,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'TB_TTip_PageSetup' member"), DXHelpExclude(true)]
        TB_PageSetupBtn_ToolTip = 13,
        TB_TTip_PageSetup = 14,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'TB_TTip_Magnifier' member"), DXHelpExclude(true)]
        TB_MagnifierBtn_ToolTip = 15,
        TB_TTip_Magnifier = 0x10,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'TB_TTip_ZoomIn' member"), DXHelpExclude(true)]
        TB_ZoomInBtn_ToolTip = 0x11,
        TB_TTip_ZoomIn = 0x12,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'TB_TTip_ZoomOut' member"), DXHelpExclude(true)]
        TB_ZoomOutBtn_ToolTip = 0x13,
        TB_TTip_ZoomOut = 20,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'TB_TTip_Zoom' member"), DXHelpExclude(true)]
        TB_ZoomBtn_ToolTip = 0x15,
        TB_TTip_Zoom = 0x16,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'TB_TTip_Search' member"), DXHelpExclude(true)]
        TB_SearchBtn_ToolTip = 0x17,
        TB_TTip_Search = 0x18,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'TB_TTip_FirstPage' member"), DXHelpExclude(true)]
        TB_FirstPageBtn_ToolTip = 0x19,
        TB_TTip_FirstPage = 0x1a,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'TB_TTip_PreviousPage' member"), DXHelpExclude(true)]
        TB_PreviousPageBtn_ToolTip = 0x1b,
        TB_TTip_PreviousPage = 0x1c,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'TB_TTip_NextPage' member"), DXHelpExclude(true)]
        TB_NextPageBtn_ToolTip = 0x1d,
        TB_TTip_NextPage = 30,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'TB_TTip_LastPage' member"), DXHelpExclude(true)]
        TB_LastPageBtn_ToolTip = 0x1f,
        TB_TTip_LastPage = 0x20,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'TB_TTip_MultiplePages' member"), DXHelpExclude(true)]
        TB_MultiplePagesBtn_ToolTip = 0x21,
        TB_TTip_MultiplePages = 0x22,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'TB_TTip_Backgr' member"), DXHelpExclude(true)]
        TB_BackGroundBtn_ToolTip = 0x23,
        TB_TTip_Backgr = 0x24,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'TB_TTip_Close' member"), DXHelpExclude(true)]
        TB_ClosePreviewBtn_ToolTip = 0x25,
        TB_TTip_Close = 0x26,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'TB_TTip_EditPageHF' member"), DXHelpExclude(true)]
        TB_EditPageHFBtn_ToolTip = 0x27,
        TB_TTip_EditPageHF = 40,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'TB_TTip_HandTool' member"), DXHelpExclude(true)]
        TB_HandToolBtn_ToolTip = 0x29,
        TB_TTip_HandTool = 0x2a,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'TB_TTip_Export' member"), DXHelpExclude(true)]
        TB_ExportBtn_ToolTip = 0x2b,
        TB_TTip_Export = 0x2c,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'TB_TTip_Send' member"), DXHelpExclude(true)]
        TB_SendBtn_ToolTip = 0x2d,
        TB_TTip_Send = 0x2e,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'TB_TTip_Map' member"), DXHelpExclude(true)]
        TB_DocMap_ToolTip = 0x2f,
        TB_TTip_Map = 0x30,
        TB_TTip_Thumbnails = 0x31,
        TB_TTip_HighlightEditingFields = 50,
        TB_TTip_Parameters = 0x33,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'TB_TTip_Watermark' member"), DXHelpExclude(true)]
        TB_Watermark_ToolTip = 0x34,
        TB_TTip_Watermark = 0x35,
        TB_TTip_Scale = 0x36,
        TB_TTip_Open = 0x37,
        TB_TTip_Save = 0x38,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'MenuItem_PdfDocument' member"), DXHelpExclude(true)]
        barExport_PDF_Document = 0x39,
        MenuItem_PdfDocument = 0x3a,
        MenuItem_PageLayout = 0x3b,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'MenuItem_TxtDocument' member"), DXHelpExclude(true)]
        barExport_Text_Document = 60,
        MenuItem_TxtDocument = 0x3d,
        MenuItem_GraphicDocument = 0x3e,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'MenuItem_CsvDocument' member"), DXHelpExclude(true)]
        barExport_CSV_Document = 0x3f,
        MenuItem_CsvDocument = 0x40,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'MenuItem_MhtDocument' member"), DXHelpExclude(true)]
        barExport_MHT_Document = 0x41,
        MenuItem_MhtDocument = 0x42,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'MenuItem_XlsDocument' member"), DXHelpExclude(true)]
        barExport_Excel_Document = 0x43,
        MenuItem_XlsDocument = 0x44,
        MenuItem_XlsxDocument = 0x45,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'MenuItem_RtfDocument' member"), DXHelpExclude(true)]
        barExport_RichTextDocument = 70,
        MenuItem_RtfDocument = 0x47,
        MenuItem_DocxDocument = 0x48,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'MenuItem_HtmDocument' member"), DXHelpExclude(true)]
        barExport_HTMLDocument = 0x49,
        MenuItem_HtmDocument = 0x4a,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'SaveDlg_FilterBmp' member"), DXHelpExclude(true)]
        barExport_BMP = 0x4b,
        SaveDlg_FilterBmp = 0x4c,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'SaveDlg_FilterGif' member"), DXHelpExclude(true)]
        barExport_GIF = 0x4d,
        SaveDlg_FilterGif = 0x4e,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'SaveDlg_FilterJpeg' member"), DXHelpExclude(true)]
        barExport_JPEG = 0x4f,
        SaveDlg_FilterJpeg = 80,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'SaveDlg_FilterPng' member"), DXHelpExclude(true)]
        barExport_PNG = 0x51,
        SaveDlg_FilterPng = 0x52,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'SaveDlg_FilterTiff' member"), DXHelpExclude(true)]
        barExport_TIFF = 0x53,
        SaveDlg_FilterTiff = 0x54,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'SaveDlg_FilterEmf' member"), DXHelpExclude(true)]
        barExport_EMF = 0x55,
        SaveDlg_FilterEmf = 0x56,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'SaveDlg_FilterWmf' member"), DXHelpExclude(true)]
        barExport_WMF = 0x57,
        SaveDlg_FilterWmf = 0x58,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'SB_PageOfPages' member"), DXHelpExclude(true)]
        SB_TotalPageNo = 0x59,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'SB_PageOfPages' member"), DXHelpExclude(true)]
        SB_CurrentPageNo = 90,
        SB_PageOfPages = 0x5b,
        SB_ZoomFactor = 0x5c,
        SB_PageNone = 0x5d,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'SB_PageInfo' member"), DXHelpExclude(true)]
        SB_PageInfo_OF = 0x5e,
        SB_PageInfo = 0x5f,
        SB_PageOfPagesHint = 0x60,
        SB_TTip_Stop = 0x61,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("For localization you should localize the HeaderFooterForm.resx file"), DXHelpExclude(true)]
        PCE_PageContentEditor_Caption = 0x62,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("For localization you should localize the HeaderFooterForm.resx file"), DXHelpExclude(true)]
        PCE_PageNumber_ToolTip = 0x63,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("For localization you should localize the HeaderFooterForm.resx file"), DXHelpExclude(true)]
        PCE_PageOfPages_ToolTip = 100,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("For localization you should localize the HeaderFooterForm.resx file"), DXHelpExclude(true)]
        PCE_DatePrinted_ToolTip = 0x65,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("For localization you should localize the HeaderFooterForm.resx file"), DXHelpExclude(true)]
        PCE_TimePrinted_ToolTip = 0x66,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("For localization you should localize the HeaderFooterForm.resx file"), DXHelpExclude(true)]
        PCE_UserName_ToolTip = 0x67,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("For localization you should localize the HeaderFooterForm.resx file"), DXHelpExclude(true)]
        PCE_Image_ToolTip = 0x68,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("For localization you should localize the HeaderFooterForm.resx file"), DXHelpExclude(true)]
        PCE_FontButton = 0x69,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("For localization you should localize the HeaderFooterForm.resx file"), DXHelpExclude(true)]
        PCE_FooterLabel = 0x6a,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("For localization you should localize the HeaderFooterForm.resx file"), DXHelpExclude(true)]
        PCE_HeaderLabel = 0x6b,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("For localization you should localize the HeaderFooterForm.resx file"), DXHelpExclude(true)]
        PCE_AlignTops_ToolTip = 0x6c,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("For localization you should localize the HeaderFooterForm.resx file"), DXHelpExclude(true)]
        PCE_AlignMiddles_ToolTip = 0x6d,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("For localization you should localize the HeaderFooterForm.resx file"), DXHelpExclude(true)]
        PCE_AlignBottoms_ToolTip = 110,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'MPForm_Lbl_Pages' member"), DXHelpExclude(true)]
        MPE_PagesLabel = 0x6f,
        MPForm_Lbl_Pages = 0x70,
        WaitForm_Caption = 0x71,
        Msg_ErrorTitle = 0x72,
        Msg_EmptyDocument = 0x73,
        Msg_CreatingDocument = 0x74,
        Msg_WaitingForParameterValues = 0x75,
        Msg_ExportingDocument = 0x76,
        Msg_UnavailableNetPrinter = 0x77,
        Msg_NeedPrinter = 120,
        Msg_WrongPrinter = 0x79,
        Msg_WrongPrinting = 0x7a,
        Msg_WrongPageSettings = 0x7b,
        Msg_CustomDrawWarning = 0x7c,
        Msg_PageMarginsWarning = 0x7d,
        Msg_IncorrectPageRange = 0x7e,
        Msg_FontInvalidNumber = 0x7f,
        Msg_NotSupportedFont = 0x80,
        Msg_NotSupportedFontException = 0x81,
        Msg_IncorrectZoomFactor = 130,
        Msg_InvalidMeasurement = 0x83,
        Msg_CannotAccessFile = 0x84,
        Msg_CannotFindFile = 0x85,
        Msg_FileReadOnly = 0x86,
        Msg_OpenFileQuestion = 0x87,
        Msg_OpenFileQuestionCaption = 0x88,
        Msg_CantFitBarcodeToControlBounds = 0x89,
        Msg_InvalidBarcodeText = 0x8a,
        Msg_InvalidBarcodeTextFormat = 0x8b,
        Msg_InvalidBarcodeData = 140,
        Msg_IncompatibleBarcodeSettings = 0x8d,
        Msg_IncompatibleLogoQRCodeSettings = 0x8e,
        Msg_ImageLoadError = 0x8f,
        Msg_IgnoredSvgElements = 0x90,
        Msg_InvPropName = 0x91,
        Msg_Search_Caption = 0x92,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete, DXHelpExclude(true)]
        Msg_SearchDialogFinishedSearching = 0x93,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete, DXHelpExclude(true)]
        Msg_SearchDialogTotalFound = 0x94,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete, DXHelpExclude(true)]
        Msg_SearchDialogReady = 0x95,
        Msg_NoDifferentFilesInStream = 150,
        Msg_BigFileToCreate = 0x97,
        Msg_BigFileToCreateJPEG = 0x98,
        Msg_BigBitmapToCreate = 0x99,
        Msg_XlsMoreThanMaxRows = 0x9a,
        Msg_XlsMoreThanMaxColumns = 0x9b,
        Msg_XlsxMoreThanMaxRows = 0x9c,
        Msg_XlsxMoreThanMaxColumns = 0x9d,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'Msg_FileDoesNotHavePrnxExtension' member"), DXHelpExclude(true)]
        Msg_FileDosntHavePrnxExtention = 0x9e,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'Msg_FileDoesNotHavePrnxExtension' member"), DXHelpExclude(true)]
        Msg_FileDoesNotHavePrnxExtention = 0x9f,
        Msg_FileDoesNotHavePrnxExtension = 160,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'Msg_FileDoesNotContainValidXml' member"), DXHelpExclude(true)]
        Msg_FileDosntContainValidXml = 0xa1,
        Msg_FileDoesNotContainValidXml = 0xa2,
        Msg_GoToNonExistentPage = 0xa3,
        Msg_Caption = 0xa4,
        Msg_PathTooLong = 0xa5,
        Msg_CannotLoadDocument = 0xa6,
        Msg_NoParameters = 0xa7,
        Msg_SeparatorCannotBeEmptyString = 0xa8,
        Msg_CannotExportToDocx = 0xa9,
        Msg_InvalidatePath = 170,
        Msg_FileAlreadyExists = 0xab,
        Msg_EmptyUsefulPageSizeError = 0xac,
        Margin_Inch = 0xad,
        Margin_Millimeter = 0xae,
        Margin_Pixel = 0xaf,
        Margin_TopMargin = 0xb0,
        Margin_BottomMargin = 0xb1,
        Margin_LeftMargin = 0xb2,
        Margin_RightMargin = 0xb3,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("Use the corresponding value of the DevExpress.XtraPrinting.Shape.Native.ShapeId enumeration (from the PropertyNamesRes.resx file of the DevExpress.Printing.Core assemby) instead"), DXHelpExclude(true)]
        Shapes_Rectangle = 180,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("Use the corresponding value of the DevExpress.XtraPrinting.Shape.Native.ShapeId enumeration (from the PropertyNamesRes.resx file of the DevExpress.Printing.Core assemby) instead"), DXHelpExclude(true)]
        Shapes_Ellipse = 0xb5,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("Use the corresponding value of the DevExpress.XtraPrinting.Shape.Native.ShapeId enumeration (from the PropertyNamesRes.resx file of the DevExpress.Printing.Core assemby) instead"), DXHelpExclude(true)]
        Shapes_Arrow = 0xb6,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("Use the corresponding value of the DevExpress.XtraPrinting.Shape.Native.ShapeId enumeration (from the PropertyNamesRes.resx file of the DevExpress.Printing.Core assemby) instead"), DXHelpExclude(true)]
        Shapes_TopArrow = 0xb7,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("Use the corresponding value of the DevExpress.XtraPrinting.Shape.Native.ShapeId enumeration (from the PropertyNamesRes.resx file of the DevExpress.Printing.Core assemby) instead"), DXHelpExclude(true)]
        Shapes_BottomArrow = 0xb8,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("Use the corresponding value of the DevExpress.XtraPrinting.Shape.Native.ShapeId enumeration (from the PropertyNamesRes.resx file of the DevExpress.Printing.Core assemby) instead"), DXHelpExclude(true)]
        Shapes_LeftArrow = 0xb9,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("Use the corresponding value of the DevExpress.XtraPrinting.Shape.Native.ShapeId enumeration (from the PropertyNamesRes.resx file of the DevExpress.Printing.Core assemby) instead"), DXHelpExclude(true)]
        Shapes_RightArrow = 0xba,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("Use the corresponding value of the DevExpress.XtraPrinting.Shape.Native.ShapeId enumeration (from the PropertyNamesRes.resx file of the DevExpress.Printing.Core assemby) instead"), DXHelpExclude(true)]
        Shapes_Polygon = 0xbb,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("Use the corresponding value of the DevExpress.XtraPrinting.Shape.Native.ShapeId enumeration (from the PropertyNamesRes.resx file of the DevExpress.Printing.Core assemby) instead"), DXHelpExclude(true)]
        Shapes_Triangle = 0xbc,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("Use the corresponding value of the DevExpress.XtraPrinting.Shape.Native.ShapeId enumeration (from the PropertyNamesRes.resx file of the DevExpress.Printing.Core assemby) instead"), DXHelpExclude(true)]
        Shapes_Square = 0xbd,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("Use the corresponding value of the DevExpress.XtraPrinting.Shape.Native.ShapeId enumeration (from the PropertyNamesRes.resx file of the DevExpress.Printing.Core assemby) instead"), DXHelpExclude(true)]
        Shapes_Pentagon = 190,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("Use the corresponding value of the DevExpress.XtraPrinting.Shape.Native.ShapeId enumeration (from the PropertyNamesRes.resx file of the DevExpress.Printing.Core assemby) instead"), DXHelpExclude(true)]
        Shapes_Hexagon = 0xbf,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("Use the corresponding value of the DevExpress.XtraPrinting.Shape.Native.ShapeId enumeration (from the PropertyNamesRes.resx file of the DevExpress.Printing.Core assemby) instead"), DXHelpExclude(true)]
        Shapes_Octagon = 0xc0,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("Use the corresponding value of the DevExpress.XtraPrinting.Shape.Native.ShapeId enumeration (from the PropertyNamesRes.resx file of the DevExpress.Printing.Core assemby) instead"), DXHelpExclude(true)]
        Shapes_Star = 0xc1,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("Use the corresponding value of the DevExpress.XtraPrinting.Shape.Native.ShapeId enumeration (from the PropertyNamesRes.resx file of the DevExpress.Printing.Core assemby) instead"), DXHelpExclude(true)]
        Shapes_ThreePointStar = 0xc2,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("Use the corresponding value of the DevExpress.XtraPrinting.Shape.Native.ShapeId enumeration (from the PropertyNamesRes.resx file of the DevExpress.Printing.Core assemby) instead"), DXHelpExclude(true)]
        Shapes_FourPointStar = 0xc3,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("Use the corresponding value of the DevExpress.XtraPrinting.Shape.Native.ShapeId enumeration (from the PropertyNamesRes.resx file of the DevExpress.Printing.Core assemby) instead"), DXHelpExclude(true)]
        Shapes_FivePointStar = 0xc4,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("Use the corresponding value of the DevExpress.XtraPrinting.Shape.Native.ShapeId enumeration (from the PropertyNamesRes.resx file of the DevExpress.Printing.Core assemby) instead"), DXHelpExclude(true)]
        Shapes_SixPointStar = 0xc5,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("Use the corresponding value of the DevExpress.XtraPrinting.Shape.Native.ShapeId enumeration (from the PropertyNamesRes.resx file of the DevExpress.Printing.Core assemby) instead"), DXHelpExclude(true)]
        Shapes_EightPointStar = 0xc6,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("Use the corresponding value of the DevExpress.XtraPrinting.Shape.Native.ShapeId enumeration (from the PropertyNamesRes.resx file of the DevExpress.Printing.Core assemby) instead"), DXHelpExclude(true)]
        Shapes_Line = 0xc7,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("Use the corresponding value of the DevExpress.XtraPrinting.Shape.Native.ShapeId enumeration (from the PropertyNamesRes.resx file of the DevExpress.Printing.Core assemby) instead"), DXHelpExclude(true)]
        Shapes_SlantLine = 200,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("Use the corresponding value of the DevExpress.XtraPrinting.Shape.Native.ShapeId enumeration (from the PropertyNamesRes.resx file of the DevExpress.Printing.Core assemby) instead"), DXHelpExclude(true)]
        Shapes_BackslantLine = 0xc9,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("Use the corresponding value of the DevExpress.XtraPrinting.Shape.Native.ShapeId enumeration (from the PropertyNamesRes.resx file of the DevExpress.Printing.Core assemby) instead"), DXHelpExclude(true)]
        Shapes_HorizontalLine = 0xca,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("Use the corresponding value of the DevExpress.XtraPrinting.Shape.Native.ShapeId enumeration (from the PropertyNamesRes.resx file of the DevExpress.Printing.Core assemby) instead"), DXHelpExclude(true)]
        Shapes_VerticalLine = 0xcb,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("Use the corresponding value of the DevExpress.XtraPrinting.Shape.Native.ShapeId enumeration (from the PropertyNamesRes.resx file of the DevExpress.Printing.Core assemby) instead"), DXHelpExclude(true)]
        Shapes_Cross = 0xcc,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("Use the corresponding value of the DevExpress.XtraPrinting.Shape.Native.ShapeId enumeration (from the PropertyNamesRes.resx file of the DevExpress.Printing.Core assemby) instead"), DXHelpExclude(true)]
        Shapes_Brace = 0xcd,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("Use the corresponding value of the DevExpress.XtraPrinting.Shape.Native.ShapeId enumeration (from the PropertyNamesRes.resx file of the DevExpress.Printing.Core assemby) instead"), DXHelpExclude(true)]
        Shapes_Bracket = 0xce,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'ScrollingInfo_Page' member"), DXHelpExclude(true)]
        Page_Scroll = 0xcf,
        ScrollingInfo_Page = 0xd0,
        PrintDialog_Duplex_Simplex = 0xd1,
        PrintDialog_Duplex_Vertical = 210,
        PrintDialog_Duplex_Horizontal = 0xd3,
        WMForm_PictureDlg_Title = 0xd4,
        WMForm_ImageStretch = 0xd5,
        WMForm_ImageClip = 0xd6,
        WMForm_ImageZoom = 0xd7,
        WMForm_Watermark_Asap = 0xd8,
        WMForm_Watermark_Confidential = 0xd9,
        WMForm_Watermark_Copy = 0xda,
        WMForm_Watermark_DoNotCopy = 0xdb,
        WMForm_Watermark_Draft = 220,
        WMForm_Watermark_Evaluation = 0xdd,
        WMForm_Watermark_Original = 0xde,
        WMForm_Watermark_Personal = 0xdf,
        WMForm_Watermark_Sample = 0xe0,
        WMForm_Watermark_TopSecret = 0xe1,
        WMForm_Watermark_Urgent = 0xe2,
        WMForm_Direction_Horizontal = 0xe3,
        WMForm_Direction_Vertical = 0xe4,
        WMForm_Direction_BackwardDiagonal = 0xe5,
        WMForm_Direction_ForwardDiagonal = 230,
        WMForm_VertAlign_Bottom = 0xe7,
        WMForm_VertAlign_Middle = 0xe8,
        WMForm_VertAlign_Top = 0xe9,
        WMForm_HorzAlign_Left = 0xea,
        WMForm_HorzAlign_Center = 0xeb,
        WMForm_HorzAlign_Right = 0xec,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("For localization use the DevExpress .NET Localization Service."), DXHelpExclude(true)]
        WMForm_ZOrderRgrItem_InFront = 0xed,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("For localization use the DevExpress .NET Localization Service."), DXHelpExclude(true)]
        WMForm_ZOrderRgrItem_Behind = 0xee,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("For localization use the DevExpress .NET Localization Service."), DXHelpExclude(true)]
        WMForm_PageRangeRgrItem_All = 0xef,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("For localization use the DevExpress .NET Localization Service."), DXHelpExclude(true)]
        WMForm_PageRangeRgrItem_Pages = 240,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'SaveDlg_Title' member"), DXHelpExclude(true)]
        dlgSaveAs = 0xf1,
        SaveDlg_Title = 0xf2,
        SaveDlg_FilterPdf = 0xf3,
        SaveDlg_FilterHtm = 0xf4,
        SaveDlg_FilterMht = 0xf5,
        SaveDlg_FilterRtf = 0xf6,
        SaveDlg_FilterDocx = 0xf7,
        SaveDlg_FilterXls = 0xf8,
        SaveDlg_FilterXlsx = 0xf9,
        SaveDlg_FilterCsv = 250,
        SaveDlg_FilterTxt = 0xfb,
        SaveDlg_FilterNativeFormat = 0xfc,
        SaveDlg_FilterXps = 0xfd,
        MenuItem_File = 0xfe,
        MenuItem_View = 0xff,
        MenuItem_Background = 0x100,
        MenuItem_PageSetup = 0x101,
        MenuItem_Print = 0x102,
        MenuItem_PrintDirect = 0x103,
        MenuItem_Export = 260,
        MenuItem_Send = 0x105,
        MenuItem_Exit = 0x106,
        MenuItem_ViewToolbar = 0x107,
        MenuItem_ViewStatusbar = 0x108,
        MenuItem_ViewContinuous = 0x109,
        MenuItem_ViewFacing = 0x10a,
        MenuItem_BackgrColor = 0x10b,
        MenuItem_Watermark = 0x10c,
        MenuItem_ZoomPageWidth = 0x10d,
        MenuItem_ZoomTextWidth = 270,
        MenuItem_ZoomWholePage = 0x10f,
        MenuItem_ZoomTwoPages = 0x110,
        MenuItem_Copy = 0x111,
        MenuItem_PrintSelection = 0x112,
        PageInfo_PageNumber = 0x113,
        PageInfo_PageNumberOfTotal = 0x114,
        PageInfo_PageTotal = 0x115,
        PageInfo_PageDate = 0x116,
        PageInfo_PageTime = 0x117,
        PageInfo_PageUserName = 280,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("You should use the 'EMail_From' member"), DXHelpExclude(true)]
        dlgSendFrom = 0x119,
        EMail_From = 0x11a,
        BarText_Toolbar = 0x11b,
        BarText_MainMenu = 0x11c,
        BarText_StatusBar = 0x11d,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete, DXHelpExclude(true)]
        ScalePopup_GroupText = 0x11e,
        ScalePopup_AdjustTo = 0x11f,
        ScalePopup_NormalSize = 0x120,
        ScalePopup_FitTo = 0x121,
        ScalePopup_PagesWide = 290,
        ExportOption_PdfPageRange = 0x123,
        ExportOption_PdfConvertImagesToJpeg = 0x124,
        ExportOption_PdfExportEditingFieldsToAcroForms = 0x125,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("This member has become obsolete."), DXHelpExclude(true)]
        ExportOption_PdfCompressed = 0x126,
        ExportOption_PdfShowPrintDialogOnOpen = 0x127,
        ExportOption_PdfNeverEmbeddedFonts = 0x128,
        ExportOption_PdfPasswordSecurityOptions = 0x129,
        ExportOption_PdfSignatureOptions = 0x12a,
        ExportOption_PdfImageQuality = 0x12b,
        ExportOption_PdfImageQuality_Lowest = 300,
        ExportOption_PdfImageQuality_Low = 0x12d,
        ExportOption_PdfImageQuality_Medium = 0x12e,
        ExportOption_PdfImageQuality_High = 0x12f,
        ExportOption_PdfImageQuality_Highest = 0x130,
        ExportOption_PdfACompatibility = 0x131,
        ExportOption_PdfACompatibility_None = 0x132,
        ExportOption_PdfACompatibility_PdfA1b = 0x133,
        ExportOption_PdfACompatibility_PdfA2b = 0x134,
        ExportOption_PdfACompatibility_PdfA3b = 0x135,
        ExportOption_PdfDocumentAuthor = 310,
        ExportOption_PdfDocumentApplication = 0x137,
        ExportOption_PdfDocumentTitle = 0x138,
        ExportOption_PdfDocumentSubject = 0x139,
        ExportOption_PdfDocumentKeywords = 0x13a,
        ExportOption_PdfPrintingPermissions_None = 0x13b,
        ExportOption_PdfPrintingPermissions_LowResolution = 0x13c,
        ExportOption_PdfPrintingPermissions_HighResolution = 0x13d,
        ExportOption_PdfChangingPermissions_None = 0x13e,
        ExportOption_PdfChangingPermissions_InsertingDeletingRotating = 0x13f,
        ExportOption_PdfChangingPermissions_FillingSigning = 320,
        ExportOption_PdfChangingPermissions_CommentingFillingSigning = 0x141,
        ExportOption_PdfChangingPermissions_AnyExceptExtractingPages = 0x142,
        ExportOption_ConfirmOpenPasswordForm_Caption = 0x143,
        ExportOption_ConfirmOpenPasswordForm_Note = 0x144,
        ExportOption_ConfirmOpenPasswordForm_Name = 0x145,
        ExportOption_ConfirmPermissionsPasswordForm_Caption = 0x146,
        ExportOption_ConfirmPermissionsPasswordForm_Note = 0x147,
        ExportOption_ConfirmPermissionsPasswordForm_Name = 0x148,
        ExportOption_ConfirmationDoesNotMatchForm_Msg = 0x149,
        ExportOption_HtmlExportMode = 330,
        ExportOption_HtmlExportMode_SingleFile = 0x14b,
        ExportOption_HtmlExportMode_SingleFilePageByPage = 0x14c,
        ExportOption_HtmlExportMode_DifferentFiles = 0x14d,
        ExportOption_HtmlCharacterSet = 0x14e,
        ExportOption_HtmlTitle = 0x14f,
        ExportOption_HtmlRemoveSecondarySymbols = 0x150,
        ExportOption_HtmlEmbedImagesInHTML = 0x151,
        ExportOption_HtmlPageRange = 0x152,
        ExportOption_HtmlPageBorderWidth = 0x153,
        ExportOption_HtmlPageBorderColor = 340,
        ExportOption_HtmlTableLayout = 0x155,
        ExportOption_HtmlExportWatermarks = 0x156,
        ExportOption_RtfExportMode = 0x157,
        ExportOption_RtfExportMode_SingleFile = 0x158,
        ExportOption_RtfExportMode_SingleFilePageByPage = 0x159,
        ExportOption_RtfPageRange = 0x15a,
        ExportOption_RtfExportWatermarks = 0x15b,
        ExportOption_DocxExportMode = 0x15c,
        ExportOption_DocxExportMode_SingleFile = 0x15d,
        ExportOption_DocxExportMode_SingleFilePageByPage = 350,
        ExportOption_DocxPageRange = 0x15f,
        ExportOption_DocxTableLayout = 0x160,
        ExportOption_DocxKeepRowHeight = 0x161,
        ExportOption_DocxExportWatermarks = 0x162,
        ExportOption_TextSeparator = 0x163,
        ExportOption_TextSeparator_TabAlias = 0x164,
        ExportOption_TextEncoding = 0x165,
        ExportOption_TextQuoteStringsWithSeparators = 0x166,
        ExportOption_TextExportMode = 0x167,
        ExportOption_TextExportMode_Value = 360,
        ExportOption_TextExportMode_Text = 0x169,
        ExportOption_CsvSeparator_UsingSystem = 0x16a,
        ExportOption_XlsRawDataMode = 0x16b,
        ExportOption_XlsShowGridLines = 0x16c,
        [EditorBrowsable(EditorBrowsableState.Never), Obsolete("This member has become obsolete."), DXHelpExclude(true)]
        ExportOption_XlsUseNativeFormat = 0x16d,
        ExportOption_XlsExportHyperlinks = 0x16e,
        ExportOption_XlsSheetName = 0x16f,
        ExportOption_XlsExportMode = 0x170,
        ExportOption_XlsExportMode_SingleFile = 0x171,
        ExportOption_XlsExportMode_SingleFilePageByPage = 370,
        ExportOption_XlsExportMode_DifferentFiles = 0x173,
        ExportOption_XlsPageRange = 0x174,
        ExportOption_XlsxExportMode = 0x175,
        ExportOption_XlsxExportMode_SingleFile = 0x176,
        ExportOption_XlsxExportMode_SingleFilePageByPage = 0x177,
        ExportOption_XlsxExportMode_DifferentFiles = 0x178,
        ExportOption_XlsxPageRange = 0x179,
        ExportOption_ImageExportMode = 0x17a,
        ExportOption_ImageExportMode_SingleFile = 0x17b,
        ExportOption_ImageExportMode_SingleFilePageByPage = 380,
        ExportOption_ImageExportMode_DifferentFiles = 0x17d,
        ExportOption_ImagePageRange = 0x17e,
        ExportOption_ImagePageBorderWidth = 0x17f,
        ExportOption_ImagePageBorderColor = 0x180,
        ExportOption_ImageFormat = 0x181,
        ExportOption_ImageResolution = 0x182,
        ExportOption_NativeFormatCompressed = 0x183,
        ExportOption_XpsPageRange = 0x184,
        ExportOption_XpsCompression = 0x185,
        ExportOption_XpsCompression_NotCompressed = 390,
        ExportOption_XpsCompression_Normal = 0x187,
        ExportOption_XpsCompression_Maximum = 0x188,
        ExportOption_XpsCompression_Fast = 0x189,
        ExportOption_XpsCompression_SuperFast = 0x18a,
        ExportOption_XpsDocumentCreator = 0x18b,
        ExportOption_XpsDocumentCategory = 0x18c,
        ExportOption_XpsDocumentTitle = 0x18d,
        ExportOption_XpsDocumentSubject = 0x18e,
        ExportOption_XpsDocumentKeywords = 0x18f,
        ExportOption_XpsDocumentVersion = 400,
        ExportOption_XpsDocumentDescription = 0x191,
        FolderBrowseDlg_ExportDirectory = 0x192,
        ExportOptionsForm_CaptionPdf = 0x193,
        ExportOptionsForm_CaptionXls = 0x194,
        ExportOptionsForm_CaptionXlsx = 0x195,
        ExportOptionsForm_CaptionTxt = 0x196,
        ExportOptionsForm_CaptionCsv = 0x197,
        ExportOptionsForm_CaptionImage = 0x198,
        ExportOptionsForm_CaptionHtml = 0x199,
        ExportOptionsForm_CaptionMht = 410,
        ExportOptionsForm_CaptionRtf = 0x19b,
        ExportOptionsForm_CaptionDocx = 0x19c,
        ExportOptionsForm_CaptionNativeOptions = 0x19d,
        ExportOptionsForm_CaptionXps = 0x19e,
        RibbonPreview_PageText = 0x19f,
        RibbonPreview_PageGroup_Print = 0x1a0,
        RibbonPreview_PageGroup_PageSetup = 0x1a1,
        RibbonPreview_PageGroup_Navigation = 0x1a2,
        RibbonPreview_PageGroup_Zoom = 0x1a3,
        RibbonPreview_PageGroup_Background = 420,
        RibbonPreview_PageGroup_Export = 0x1a5,
        RibbonPreview_PageGroup_Document = 0x1a6,
        RibbonPreview_PageGroup_Close = 0x1a7,
        RibbonPreview_DocumentMap_Caption = 0x1a8,
        RibbonPreview_Parameters_Caption = 0x1a9,
        RibbonPreview_Find_Caption = 0x1aa,
        RibbonPreview_Pointer_Caption = 0x1ab,
        RibbonPreview_HandTool_Caption = 0x1ac,
        RibbonPreview_Customize_Caption = 0x1ad,
        RibbonPreview_Print_Caption = 430,
        RibbonPreview_PrintDirect_Caption = 0x1af,
        RibbonPreview_PageSetup_Caption = 0x1b0,
        RibbonPreview_EditPageHF_Caption = 0x1b1,
        RibbonPreview_Magnifier_Caption = 0x1b2,
        RibbonPreview_ZoomOut_Caption = 0x1b3,
        RibbonPreview_ZoomExact_Caption = 0x1b4,
        RibbonPreview_ZoomIn_Caption = 0x1b5,
        RibbonPreview_ShowFirstPage_Caption = 0x1b6,
        RibbonPreview_ShowPrevPage_Caption = 0x1b7,
        RibbonPreview_ShowNextPage_Caption = 440,
        RibbonPreview_ShowLastPage_Caption = 0x1b9,
        RibbonPreview_MultiplePages_Caption = 0x1ba,
        RibbonPreview_FillBackground_Caption = 0x1bb,
        RibbonPreview_Watermark_Caption = 0x1bc,
        RibbonPreview_ExportFile_Caption = 0x1bd,
        RibbonPreview_SendFile_Caption = 0x1be,
        RibbonPreview_ClosePreview_Caption = 0x1bf,
        RibbonPreview_Scale_Caption = 0x1c0,
        RibbonPreview_PageOrientation_Caption = 0x1c1,
        RibbonPreview_PaperSize_Caption = 450,
        RibbonPreview_PageMargins_Caption = 0x1c3,
        RibbonPreview_Zoom_Caption = 0x1c4,
        RibbonPreview_Save_Caption = 0x1c5,
        RibbonPreview_Open_Caption = 0x1c6,
        RibbonPreview_Thumbnails_Caption = 0x1c7,
        RibbonPreview_HighlightEditingFields_Caption = 0x1c8,
        RibbonPreview_DocumentMap_STipTitle = 0x1c9,
        RibbonPreview_Parameters_STipTitle = 0x1ca,
        RibbonPreview_Find_STipTitle = 0x1cb,
        RibbonPreview_Pointer_STipTitle = 460,
        RibbonPreview_HandTool_STipTitle = 0x1cd,
        RibbonPreview_Customize_STipTitle = 0x1ce,
        RibbonPreview_Print_STipTitle = 0x1cf,
        RibbonPreview_PrintDirect_STipTitle = 0x1d0,
        RibbonPreview_PageSetup_STipTitle = 0x1d1,
        RibbonPreview_EditPageHF_STipTitle = 0x1d2,
        RibbonPreview_Magnifier_STipTitle = 0x1d3,
        RibbonPreview_ZoomOut_STipTitle = 0x1d4,
        RibbonPreview_ZoomIn_STipTitle = 0x1d5,
        RibbonPreview_ShowFirstPage_STipTitle = 470,
        RibbonPreview_ShowPrevPage_STipTitle = 0x1d7,
        RibbonPreview_ShowNextPage_STipTitle = 0x1d8,
        RibbonPreview_ShowLastPage_STipTitle = 0x1d9,
        RibbonPreview_MultiplePages_STipTitle = 0x1da,
        RibbonPreview_FillBackground_STipTitle = 0x1db,
        RibbonPreview_Watermark_STipTitle = 0x1dc,
        RibbonPreview_ExportFile_STipTitle = 0x1dd,
        RibbonPreview_SendFile_STipTitle = 0x1de,
        RibbonPreview_ClosePreview_STipTitle = 0x1df,
        RibbonPreview_Scale_STipTitle = 480,
        RibbonPreview_PageOrientation_STipTitle = 0x1e1,
        RibbonPreview_PaperSize_STipTitle = 0x1e2,
        RibbonPreview_PageMargins_STipTitle = 0x1e3,
        RibbonPreview_Zoom_STipTitle = 0x1e4,
        RibbonPreview_PageGroup_PageSetup_STipTitle = 0x1e5,
        RibbonPreview_Save_STipTitle = 0x1e6,
        RibbonPreview_Open_STipTitle = 0x1e7,
        RibbonPreview_Thumbnails_STipTitle = 0x1e8,
        RibbonPreview_HighlightEditingFields_STipTitle = 0x1e9,
        RibbonPreview_DocumentMap_STipContent = 490,
        RibbonPreview_Parameters_STipContent = 0x1eb,
        RibbonPreview_Find_STipContent = 0x1ec,
        RibbonPreview_Pointer_STipContent = 0x1ed,
        RibbonPreview_HandTool_STipContent = 0x1ee,
        RibbonPreview_Customize_STipContent = 0x1ef,
        RibbonPreview_Print_STipContent = 0x1f0,
        RibbonPreview_PrintDirect_STipContent = 0x1f1,
        RibbonPreview_PageSetup_STipContent = 0x1f2,
        RibbonPreview_EditPageHF_STipContent = 0x1f3,
        RibbonPreview_Magnifier_STipContent = 500,
        RibbonPreview_ZoomOut_STipContent = 0x1f5,
        RibbonPreview_ZoomIn_STipContent = 0x1f6,
        RibbonPreview_ShowFirstPage_STipContent = 0x1f7,
        RibbonPreview_ShowPrevPage_STipContent = 0x1f8,
        RibbonPreview_ShowNextPage_STipContent = 0x1f9,
        RibbonPreview_ShowLastPage_STipContent = 0x1fa,
        RibbonPreview_MultiplePages_STipContent = 0x1fb,
        RibbonPreview_FillBackground_STipContent = 0x1fc,
        RibbonPreview_Watermark_STipContent = 0x1fd,
        RibbonPreview_ExportFile_STipContent = 510,
        RibbonPreview_SendFile_STipContent = 0x1ff,
        RibbonPreview_ClosePreview_STipContent = 0x200,
        RibbonPreview_Scale_STipContent = 0x201,
        RibbonPreview_PageOrientation_STipContent = 0x202,
        RibbonPreview_PaperSize_STipContent = 0x203,
        RibbonPreview_PageMargins_STipContent = 0x204,
        RibbonPreview_Zoom_STipContent = 0x205,
        RibbonPreview_PageGroup_PageSetup_STipContent = 0x206,
        RibbonPreview_Save_STipContent = 0x207,
        RibbonPreview_Open_STipContent = 520,
        RibbonPreview_Thumbnails_STipContent = 0x209,
        RibbonPreview_HighlightEditingFields_STipContent = 0x20a,
        RibbonPreview_ExportPdf_Caption = 0x20b,
        RibbonPreview_ExportHtm_Caption = 0x20c,
        RibbonPreview_ExportMht_Caption = 0x20d,
        RibbonPreview_ExportRtf_Caption = 0x20e,
        RibbonPreview_ExportDocx_Caption = 0x20f,
        RibbonPreview_ExportXls_Caption = 0x210,
        RibbonPreview_ExportXlsx_Caption = 0x211,
        RibbonPreview_ExportCsv_Caption = 530,
        RibbonPreview_ExportTxt_Caption = 0x213,
        RibbonPreview_ExportGraphic_Caption = 0x214,
        RibbonPreview_ExportXps_Caption = 0x215,
        RibbonPreview_SendPdf_Caption = 0x216,
        RibbonPreview_SendMht_Caption = 0x217,
        RibbonPreview_SendRtf_Caption = 0x218,
        RibbonPreview_SendDocx_Caption = 0x219,
        RibbonPreview_SendXls_Caption = 0x21a,
        RibbonPreview_SendXlsx_Caption = 0x21b,
        RibbonPreview_SendCsv_Caption = 540,
        RibbonPreview_SendTxt_Caption = 0x21d,
        RibbonPreview_SendGraphic_Caption = 0x21e,
        RibbonPreview_SendXps_Caption = 0x21f,
        RibbonPreview_ExportPdf_Description = 0x220,
        RibbonPreview_ExportHtm_Description = 0x221,
        RibbonPreview_ExportTxt_Description = 0x222,
        RibbonPreview_ExportCsv_Description = 0x223,
        RibbonPreview_ExportMht_Description = 0x224,
        RibbonPreview_ExportXls_Description = 0x225,
        RibbonPreview_ExportXlsx_Description = 550,
        RibbonPreview_ExportRtf_Description = 0x227,
        RibbonPreview_ExportDocx_Description = 0x228,
        RibbonPreview_ExportGraphic_Description = 0x229,
        RibbonPreview_ExportXps_Description = 0x22a,
        RibbonPreview_SendPdf_Description = 0x22b,
        RibbonPreview_SendTxt_Description = 0x22c,
        RibbonPreview_SendCsv_Description = 0x22d,
        RibbonPreview_SendMht_Description = 0x22e,
        RibbonPreview_SendXls_Description = 0x22f,
        RibbonPreview_SendXlsx_Description = 560,
        RibbonPreview_SendRtf_Description = 0x231,
        RibbonPreview_SendDocx_Description = 0x232,
        RibbonPreview_SendGraphic_Description = 0x233,
        RibbonPreview_SendXps_Description = 0x234,
        RibbonPreview_ExportPdf_STipTitle = 0x235,
        RibbonPreview_ExportHtm_STipTitle = 0x236,
        RibbonPreview_ExportTxt_STipTitle = 0x237,
        RibbonPreview_ExportCsv_STipTitle = 0x238,
        RibbonPreview_ExportMht_STipTitle = 0x239,
        RibbonPreview_ExportXls_STipTitle = 570,
        RibbonPreview_ExportXlsx_STipTitle = 0x23b,
        RibbonPreview_ExportRtf_STipTitle = 0x23c,
        RibbonPreview_ExportDocx_STipTitle = 0x23d,
        RibbonPreview_ExportGraphic_STipTitle = 0x23e,
        RibbonPreview_SendPdf_STipTitle = 0x23f,
        RibbonPreview_SendTxt_STipTitle = 0x240,
        RibbonPreview_SendCsv_STipTitle = 0x241,
        RibbonPreview_SendMht_STipTitle = 0x242,
        RibbonPreview_SendXls_STipTitle = 0x243,
        RibbonPreview_SendXlsx_STipTitle = 580,
        RibbonPreview_SendRtf_STipTitle = 0x245,
        RibbonPreview_SendDocx_STipTitle = 0x246,
        RibbonPreview_SendGraphic_STipTitle = 0x247,
        RibbonPreview_ExportPdf_STipContent = 0x248,
        RibbonPreview_ExportHtm_STipContent = 0x249,
        RibbonPreview_ExportTxt_STipContent = 0x24a,
        RibbonPreview_ExportCsv_STipContent = 0x24b,
        RibbonPreview_ExportMht_STipContent = 0x24c,
        RibbonPreview_ExportXls_STipContent = 0x24d,
        RibbonPreview_ExportXlsx_STipContent = 590,
        RibbonPreview_ExportRtf_STipContent = 0x24f,
        RibbonPreview_ExportDocx_STipContent = 0x250,
        RibbonPreview_ExportGraphic_STipContent = 0x251,
        RibbonPreview_SendPdf_STipContent = 0x252,
        RibbonPreview_SendTxt_STipContent = 0x253,
        RibbonPreview_SendCsv_STipContent = 0x254,
        RibbonPreview_SendMht_STipContent = 0x255,
        RibbonPreview_SendXls_STipContent = 0x256,
        RibbonPreview_SendXlsx_STipContent = 0x257,
        RibbonPreview_SendRtf_STipContent = 600,
        RibbonPreview_SendDocx_STipContent = 0x259,
        RibbonPreview_SendGraphic_STipContent = 0x25a,
        RibbonPreview_GalleryItem_PageOrientationPortrait_Caption = 0x25b,
        RibbonPreview_GalleryItem_PageOrientationLandscape_Caption = 0x25c,
        RibbonPreview_GalleryItem_PageMarginsNormal_Caption = 0x25d,
        RibbonPreview_GalleryItem_PageMarginsNarrow_Caption = 0x25e,
        RibbonPreview_GalleryItem_PageMarginsModerate_Caption = 0x25f,
        RibbonPreview_GalleryItem_PageMarginsWide_Caption = 0x260,
        RibbonPreview_GalleryItem_PageOrientationPortrait_Description = 0x261,
        RibbonPreview_GalleryItem_PageOrientationLandscape_Description = 610,
        RibbonPreview_GalleryItem_PageMarginsNormal_Description = 0x263,
        RibbonPreview_GalleryItem_PageMarginsNarrow_Description = 0x264,
        RibbonPreview_GalleryItem_PageMarginsModerate_Description = 0x265,
        RibbonPreview_GalleryItem_PageMarginsWide_Description = 0x266,
        RibbonPreview_GalleryItem_PageMargins_Description = 0x267,
        RibbonPreview_GalleryItem_PaperSize_Description = 0x268,
        OpenFileDialog_Filter = 0x269,
        OpenFileDialog_Title = 0x26a,
        ExportOption_PdfPasswordSecurityOptions_DocumentOpenPassword = 0x26b,
        ExportOption_PdfPasswordSecurityOptions_Permissions = 620,
        ExportOption_PdfPasswordSecurityOptions_None = 0x26d,
        ParametersRequest_Submit = 0x26e,
        ParametersRequest_Reset = 0x26f,
        ParametersRequest_Caption = 0x270,
        ParametersRequest_NullValuePrompt = 0x271,
        ParametersRequest_AllMultiValuesFormat = 0x272,
        ParametersRequest_SelectedMultiValuesFormat = 0x273,
        NoneString = 0x274,
        WatermarkTypePicture = 0x275,
        WatermarkTypeText = 630,
        ParameterLookUpSettingsNoLookUp = 0x277,
        ParameterRangeSettingsNoRange = 0x278,
        ExportOption_PdfSignatureOptions_Certificate = 0x279,
        ExportOption_PdfSignatureOptions_Reason = 0x27a,
        ExportOption_PdfSignatureOptions_Location = 0x27b,
        ExportOption_PdfSignatureOptions_ContactInfo = 0x27c,
        ExportOption_PdfSignatureOptions_None = 0x27d,
        ExportOption_PdfSignature_EmptyCertificate = 0x27e,
        ExportOption_PdfSignature_Issuer = 0x27f,
        ExportOption_PdfSignature_ValidRange = 640,
        NetworkPrinterFormat = 0x281,
        PrinterStatus_Busy = 0x282,
        PrinterStatus_DoorOpen = 0x283,
        PrinterStatus_DriverUpdateNeeded = 0x284,
        PrinterStatus_Error = 0x285,
        PrinterStatus_Initializing = 0x286,
        PrinterStatus_IOActive = 0x287,
        PrinterStatus_ManualFeed = 0x288,
        PrinterStatus_NotAvailable = 0x289,
        PrinterStatus_NoToner = 650,
        PrinterStatus_Offline = 0x28b,
        PrinterStatus_OutOfMemory = 0x28c,
        PrinterStatus_OutputBinFull = 0x28d,
        PrinterStatus_PagePunt = 0x28e,
        PrinterStatus_PaperJam = 0x28f,
        PrinterStatus_PaperOut = 0x290,
        PrinterStatus_PaperProblem = 0x291,
        PrinterStatus_Paused = 0x292,
        PrinterStatus_PendingDeletion = 0x293,
        PrinterStatus_PowerSave = 660,
        PrinterStatus_Printing = 0x295,
        PrinterStatus_Processing = 0x296,
        PrinterStatus_Ready = 0x297,
        PrinterStatus_ServerOffline = 0x298,
        PrinterStatus_ServerUnknown = 0x299,
        PrinterStatus_TonerLow = 0x29a,
        PrinterStatus_UserIntervention = 0x29b,
        PrinterStatus_Waiting = 0x29c,
        PrinterStatus_WarmingUp = 0x29d,
        EditingFieldEditors_Integer = 670,
        EditingFieldEditors_IntegerPositive = 0x29f,
        EditingFieldEditors_FixedPoint = 0x2a0,
        EditingFieldEditors_FixedPointPositive = 0x2a1,
        EditingFieldEditors_Date = 0x2a2,
        EditingFieldEditors_OnlyLetters = 0x2a3,
        EditingFieldEditors_OnlyUppercaseLetters = 0x2a4,
        EditingFieldEditors_OnlyLowercaseLetters = 0x2a5,
        EditingFieldEditors_OnlyLatinLetters = 0x2a6,
        EditingFieldEditors_Image = 0x2a7,
        EditingFieldEditors_Signature = 680,
        EditingFieldEditors_ImageAndSignature = 0x2a9,
        EditingFieldEditorCategories_Numeric = 0x2aa,
        EditingFieldEditorCategories_DateTime = 0x2ab,
        EditingFieldEditorCategories_Letters = 0x2ac,
        ImageEditingFieldEditor_LoadImage = 0x2ad,
        ImageEditingFieldEditor_ChooseImage = 0x2ae,
        ImageEditingFieldEditor_SizeModeAndAlignment = 0x2af,
        ImageEditingFieldEditor_BrushOptions = 0x2b0,
        ImageEditingFieldEditor_Reset = 0x2b1,
        ImageEditingFieldEditor_Clear = 690,
        ImageEditingFieldEditor_SizeMode = 0x2b3,
        ImageEditingFieldEditor_Alignment = 0x2b4,
        ImageEditingFieldEditor_BrushSize = 0x2b5,
        ImageEditingFieldEditor_BrushColor = 0x2b6,
        DateRangeParameterEditor_Today = 0x2b7,
        DateRangeParameterEditor_Yesterday = 0x2b8,
        DateRangeParameterEditor_CurrentWeek = 0x2b9,
        DateRangeParameterEditor_LastWeek = 0x2ba,
        DateRangeParameterEditor_PreviousWeek = 0x2bb,
        DateRangeParameterEditor_Last7Days = 700,
        DateRangeParameterEditor_CurrentMonth = 0x2bd,
        DateRangeParameterEditor_LastMonth = 0x2be,
        DateRangeParameterEditor_PreviousMonth = 0x2bf,
        DateRangeParameterEditor_CurrentQuarter = 0x2c0,
        DateRangeParameterEditor_PreviousQuarter = 0x2c1,
        DateRangeParameterEditor_CurrentYear = 0x2c2,
        DateRangeParameterEditor_LastYear = 0x2c3,
        DateRangeParameterEditor_PreviousYear = 0x2c4
    }
}

