namespace DevExpress.Xpf.LayoutControl
{
    using System;
    using System.Runtime.CompilerServices;

    public class DataLayoutControlAutoGeneratedGroupEventArgs : EventArgs
    {
        public DataLayoutControlAutoGeneratedGroupEventArgs(LayoutGroup group)
        {
            this.Group = group;
        }

        public LayoutGroup Group { get; private set; }
    }
}

