namespace DMEWorks.Core
{
    using System;
    using System.Collections.Generic;

    public class TableName
    {
        public const string tbl_ability_eligibility_payer = "tbl_ability_eligibility_payer";
        public const string tbl_ability_eligibility_request = "tbl_ability_eligibility_request";
        public const string tbl_authorizationtype = "tbl_authorizationtype";
        public const string tbl_batch = "tbl_batch";
        public const string tbl_billingtype = "tbl_billingtype";
        public const string tbl_cmnform = "tbl_cmnform";
        public const string tbl_cmnform_0102a = "tbl_cmnform_0102a";
        public const string tbl_cmnform_0102b = "tbl_cmnform_0102b";
        public const string tbl_cmnform_0203a = "tbl_cmnform_0203a";
        public const string tbl_cmnform_0203b = "tbl_cmnform_0203b";
        public const string tbl_cmnform_0302 = "tbl_cmnform_0302";
        public const string tbl_cmnform_0403b = "tbl_cmnform_0403b";
        public const string tbl_cmnform_0403c = "tbl_cmnform_0403c";
        public const string tbl_cmnform_0602b = "tbl_cmnform_0602b";
        public const string tbl_cmnform_0702a = "tbl_cmnform_0702a";
        public const string tbl_cmnform_0702b = "tbl_cmnform_0702b";
        public const string tbl_cmnform_0902 = "tbl_cmnform_0902";
        public const string tbl_cmnform_1002a = "tbl_cmnform_1002a";
        public const string tbl_cmnform_1002b = "tbl_cmnform_1002b";
        public const string tbl_cmnform_4842 = "tbl_cmnform_4842";
        public const string tbl_cmnform_details = "tbl_cmnform_details";
        public const string tbl_cmnform_drorder = "tbl_cmnform_drorder";
        public const string tbl_cmnform_uro = "tbl_cmnform_uro";
        public const string tbl_company = "tbl_company";
        public const string tbl_compliance = "tbl_compliance";
        public const string tbl_compliance_items = "tbl_compliance_items";
        public const string tbl_compliance_notes = "tbl_compliance_notes";
        public const string tbl_crystalreport = "tbl_crystalreport";
        public const string tbl_customer = "tbl_customer";
        public const string tbl_customer_insurance = "tbl_customer_insurance";
        public const string tbl_customer_notes = "tbl_customer_notes";
        public const string tbl_customerclass = "tbl_customerclass";
        public const string tbl_customertype = "tbl_customertype";
        public const string tbl_denial = "tbl_denial";
        public const string tbl_doctor = "tbl_doctor";
        public const string tbl_doctortype = "tbl_doctortype";
        public const string tbl_eligibilityrequest = "tbl_eligibilityrequest";
        public const string tbl_facility = "tbl_facility";
        public const string tbl_hao = "tbl_hao";
        public const string tbl_icd9 = "tbl_icd9";
        public const string tbl_icd10 = "tbl_icd10";
        public const string tbl_image = "tbl_image";
        public const string tbl_insurancecompany = "tbl_insurancecompany";
        public const string tbl_insurancecompanygroup = "tbl_insurancecompanygroup";
        public const string tbl_insurancecompanytype = "tbl_insurancecompanytype";
        public const string tbl_insurancetype = "tbl_insurancetype";
        public const string tbl_inventory = "tbl_inventory";
        public const string tbl_inventory_transaction = "tbl_inventory_transaction";
        public const string tbl_inventory_transaction_type = "tbl_inventory_transaction_type";
        public const string tbl_inventoryitem = "tbl_inventoryitem";
        public const string tbl_inventorycode = "tbl_inventorycode";
        public const string tbl_invoice = "tbl_invoice";
        public const string tbl_invoicedetails = "tbl_invoicedetails";
        public const string tbl_invoicenotes = "tbl_invoicenotes";
        public const string tbl_invoiceform = "tbl_invoiceform";
        public const string tbl_invoice_transaction = "tbl_invoice_transaction";
        public const string tbl_invoice_transactiontype = "tbl_invoice_transactiontype";
        public const string tbl_kit = "tbl_kit";
        public const string tbl_kitdetails = "tbl_kitdetails";
        public const string tbl_legalrep = "tbl_legalrep";
        public const string tbl_location = "tbl_location";
        public const string tbl_manufacturer = "tbl_manufacturer";
        public const string tbl_medicalconditions = "tbl_medicalconditions";
        public const string tbl_object = "tbl_object";
        public const string tbl_order = "tbl_order";
        public const string tbl_orderdetails = "tbl_orderdetails";
        public const string tbl_payment = "tbl_payment";
        public const string tbl_paymentplan = "tbl_paymentplan";
        public const string tbl_permissions = "tbl_permissions";
        public const string tbl_postype = "tbl_postype";
        public const string tbl_predefinedtext = "tbl_predefinedtext";
        public const string tbl_predefinedtext_compliancenotes = "tbl_predefinedtext_compliancenotes";
        public const string tbl_predefinedtext_customernotes = "tbl_predefinedtext_customernotes";
        public const string tbl_predefinedtext_invoicenotes = "tbl_predefinedtext_invoicenotes";
        public const string tbl_pricecode = "tbl_pricecode";
        public const string tbl_pricecode_item = "tbl_pricecode_item";
        public const string tbl_producttype = "tbl_producttype";
        public const string tbl_provider = "tbl_provider";
        public const string tbl_providernumbertype = "tbl_providernumbertype";
        public const string tbl_purchaseorder = "tbl_purchaseorder";
        public const string tbl_purchaseorderdetails = "tbl_purchaseorderdetails";
        public const string tbl_referral = "tbl_referral";
        public const string tbl_referraltype = "tbl_referraltype";
        public const string tbl_relationship = "tbl_relationship";
        public const string tbl_salesrep = "tbl_salesrep";
        public const string tbl_serial = "tbl_serial";
        public const string tbl_serial_maintenance = "tbl_serial_maintenance";
        public const string tbl_serial_transaction = "tbl_serial_transaction";
        public const string tbl_serial_transaction_type = "tbl_serial_transaction_type";
        public const string tbl_sessions = "tbl_sessions";
        public const string tbl_shippingmethod = "tbl_shippingmethod";
        public const string tbl_signaturetype = "tbl_signaturetype";
        public const string tbl_survey = "tbl_survey";
        public const string tbl_taxrate = "tbl_taxrate";
        public const string tbl_user = "tbl_user";
        public const string tbl_user_location = "tbl_user_location";
        public const string tbl_variables = "tbl_variables";
        public const string tbl_vendor = "tbl_vendor";
        public const string tbl_warehouse = "tbl_warehouse";
        public const string tbl_zipcode = "tbl_zipcode";
        public const string tbl_upsshipping_billingoption = "tbl_upsshipping_billingoption";
        public const string tbl_upsshipping_freightclass = "tbl_upsshipping_freightclass";
        public const string tbl_upsshipping_packagingtype = "tbl_upsshipping_packagingtype";
        private static readonly Dictionary<string, string> constants;

        static TableName()
        {
            string[] textArray1 = new string[0x67];
            textArray1[0] = "tbl_ability_eligibility_payer";
            textArray1[1] = "tbl_ability_eligibility_request";
            textArray1[2] = "tbl_authorizationtype";
            textArray1[3] = "tbl_batch";
            textArray1[4] = "tbl_billingtype";
            textArray1[5] = "tbl_cmnform";
            textArray1[6] = "tbl_cmnform_0102a";
            textArray1[7] = "tbl_cmnform_0102b";
            textArray1[8] = "tbl_cmnform_0203a";
            textArray1[9] = "tbl_cmnform_0203b";
            textArray1[10] = "tbl_cmnform_0302";
            textArray1[11] = "tbl_cmnform_0403b";
            textArray1[12] = "tbl_cmnform_0403c";
            textArray1[13] = "tbl_cmnform_0602b";
            textArray1[14] = "tbl_cmnform_0702a";
            textArray1[15] = "tbl_cmnform_0702b";
            textArray1[0x10] = "tbl_cmnform_0902";
            textArray1[0x11] = "tbl_cmnform_1002a";
            textArray1[0x12] = "tbl_cmnform_1002b";
            textArray1[0x13] = "tbl_cmnform_4842";
            textArray1[20] = "tbl_cmnform_details";
            textArray1[0x15] = "tbl_cmnform_drorder";
            textArray1[0x16] = "tbl_cmnform_uro";
            textArray1[0x17] = "tbl_company";
            textArray1[0x18] = "tbl_compliance";
            textArray1[0x19] = "tbl_compliance_items";
            textArray1[0x1a] = "tbl_compliance_notes";
            textArray1[0x1b] = "tbl_crystalreport";
            textArray1[0x1c] = "tbl_customer";
            textArray1[0x1d] = "tbl_customer_insurance";
            textArray1[30] = "tbl_customer_notes";
            textArray1[0x1f] = "tbl_customerclass";
            textArray1[0x20] = "tbl_customertype";
            textArray1[0x21] = "tbl_denial";
            textArray1[0x22] = "tbl_doctor";
            textArray1[0x23] = "tbl_doctortype";
            textArray1[0x24] = "tbl_eligibilityrequest";
            textArray1[0x25] = "tbl_facility";
            textArray1[0x26] = "tbl_hao";
            textArray1[0x27] = "tbl_icd9";
            textArray1[40] = "tbl_icd10";
            textArray1[0x29] = "tbl_image";
            textArray1[0x2a] = "tbl_insurancecompany";
            textArray1[0x2b] = "tbl_insurancecompanygroup";
            textArray1[0x2c] = "tbl_insurancecompanytype";
            textArray1[0x2d] = "tbl_insurancetype";
            textArray1[0x2e] = "tbl_inventory";
            textArray1[0x2f] = "tbl_inventory_transaction";
            textArray1[0x30] = "tbl_inventory_transaction_type";
            textArray1[0x31] = "tbl_inventoryitem";
            textArray1[50] = "tbl_inventorycode";
            textArray1[0x33] = "tbl_invoice";
            textArray1[0x34] = "tbl_invoicedetails";
            textArray1[0x35] = "tbl_invoicenotes";
            textArray1[0x36] = "tbl_invoiceform";
            textArray1[0x37] = "tbl_invoice_transaction";
            textArray1[0x38] = "tbl_invoice_transactiontype";
            textArray1[0x39] = "tbl_kit";
            textArray1[0x3a] = "tbl_kitdetails";
            textArray1[0x3b] = "tbl_legalrep";
            textArray1[60] = "tbl_location";
            textArray1[0x3d] = "tbl_manufacturer";
            textArray1[0x3e] = "tbl_medicalconditions";
            textArray1[0x3f] = "tbl_object";
            textArray1[0x40] = "tbl_order";
            textArray1[0x41] = "tbl_orderdetails";
            textArray1[0x42] = "tbl_payment";
            textArray1[0x43] = "tbl_paymentplan";
            textArray1[0x44] = "tbl_permissions";
            textArray1[0x45] = "tbl_postype";
            textArray1[70] = "tbl_predefinedtext";
            textArray1[0x47] = "tbl_predefinedtext_compliancenotes";
            textArray1[0x48] = "tbl_predefinedtext_customernotes";
            textArray1[0x49] = "tbl_predefinedtext_invoicenotes";
            textArray1[0x4a] = "tbl_pricecode";
            textArray1[0x4b] = "tbl_pricecode_item";
            textArray1[0x4c] = "tbl_producttype";
            textArray1[0x4d] = "tbl_provider";
            textArray1[0x4e] = "tbl_providernumbertype";
            textArray1[0x4f] = "tbl_purchaseorder";
            textArray1[80] = "tbl_purchaseorderdetails";
            textArray1[0x51] = "tbl_referral";
            textArray1[0x52] = "tbl_referraltype";
            textArray1[0x53] = "tbl_relationship";
            textArray1[0x54] = "tbl_salesrep";
            textArray1[0x55] = "tbl_serial";
            textArray1[0x56] = "tbl_serial_maintenance";
            textArray1[0x57] = "tbl_serial_transaction";
            textArray1[0x58] = "tbl_serial_transaction_type";
            textArray1[0x59] = "tbl_sessions";
            textArray1[90] = "tbl_shippingmethod";
            textArray1[0x5b] = "tbl_signaturetype";
            textArray1[0x5c] = "tbl_survey";
            textArray1[0x5d] = "tbl_taxrate";
            textArray1[0x5e] = "tbl_user";
            textArray1[0x5f] = "tbl_user_location";
            textArray1[0x60] = "tbl_variables";
            textArray1[0x61] = "tbl_vendor";
            textArray1[0x62] = "tbl_warehouse";
            textArray1[0x63] = "tbl_zipcode";
            textArray1[100] = "tbl_upsshipping_billingoption";
            textArray1[0x65] = "tbl_upsshipping_freightclass";
            textArray1[0x66] = "tbl_upsshipping_packagingtype";
            Dictionary<string, string> dictionary = new Dictionary<string, string>(StringComparer.InvariantCultureIgnoreCase);
            foreach (string str in textArray1)
            {
                dictionary.Add(str, str);
            }
            constants = dictionary;
        }

        public static string Normalize(string tableName)
        {
            string str;
            if (tableName == null)
            {
                throw new ArgumentNullException("tableName");
            }
            return (!constants.TryGetValue(tableName, out str) ? tableName : str);
        }
    }
}

