namespace DevExpress.Mvvm.Native
{
    using System;

    public interface IApplicationJumpTaskInfoInternal : IApplicationJumpItemInfoInternal
    {
        void Execute();
        void SetAutoGeneratedCommandId(string commandID);

        bool IsInitialized { get; }
    }
}

