namespace DevExpress.Xpf.Editors
{
    using DevExpress.Utils.Localization;
    using DevExpress.Utils.Localization.Internal;
    using DevExpress.Xpf.Core;
    using System;

    public class EditorLocalizer : DXLocalizer<EditorStringId>
    {
        static EditorLocalizer()
        {
            SetActiveLocalizerProvider(new DefaultActiveLocalizerProvider<EditorStringId>(CreateDefaultLocalizer()));
        }

        public static XtraLocalizer<EditorStringId> CreateDefaultLocalizer() => 
            new EditorResXLocalizer();

        public override XtraLocalizer<EditorStringId> CreateResXLocalizer() => 
            new EditorResXLocalizer();

        public static string GetString(EditorStringId id) => 
            Active.GetLocalizedString(id);

        public static string GetString(string id) => 
            Active.GetLocalizedString((EditorStringId) Enum.Parse(typeof(EditorStringId), id, false));

        protected override void PopulateStringTable()
        {
            this.AddString(EditorStringId.OutOfRange, "Value is out of range");
            this.AddString(EditorStringId.MaskIncomplete, "Mask incomplete");
            this.AddString(EditorStringId.SelectAll, "(Select All)");
            this.AddString(EditorStringId.EmptyItem, "(None)");
            this.AddString(EditorStringId.OK, "OK");
            this.AddString(EditorStringId.Cancel, "Cancel");
            this.AddString(EditorStringId.Clear, "Clear");
            this.AddString(EditorStringId.Apply, "Apply");
            this.AddString(EditorStringId.Yes, "Yes");
            this.AddString(EditorStringId.No, "No");
            this.AddString(EditorStringId.Open, "Open");
            this.AddString(EditorStringId.Save, "Save");
            this.AddString(EditorStringId.Today, "Today");
            this.AddString(EditorStringId.Cut, "Cut");
            this.AddString(EditorStringId.Copy, "Copy");
            this.AddString(EditorStringId.Paste, "Paste");
            this.AddString(EditorStringId.CaptionError, "Error");
            this.AddString(EditorStringId.SetNullValue, "Clear");
            this.AddString(EditorStringId.CalculatorButtonMC, "MC");
            this.AddString(EditorStringId.CalculatorButtonMR, "MR");
            this.AddString(EditorStringId.CalculatorButtonMS, "MS");
            this.AddString(EditorStringId.CalculatorButtonMAdd, "M+");
            this.AddString(EditorStringId.CalculatorButtonMSub, "M-");
            this.AddString(EditorStringId.CalculatorButtonBack, "←");
            this.AddString(EditorStringId.CalculatorButtonCancel, "CE");
            this.AddString(EditorStringId.CalculatorButtonClear, "C");
            this.AddString(EditorStringId.CalculatorButtonZero, "0");
            this.AddString(EditorStringId.CalculatorButtonOne, "1");
            this.AddString(EditorStringId.CalculatorButtonTwo, "2");
            this.AddString(EditorStringId.CalculatorButtonThree, "3");
            this.AddString(EditorStringId.CalculatorButtonFour, "4");
            this.AddString(EditorStringId.CalculatorButtonFive, "5");
            this.AddString(EditorStringId.CalculatorButtonSix, "6");
            this.AddString(EditorStringId.CalculatorButtonSeven, "7");
            this.AddString(EditorStringId.CalculatorButtonEight, "8");
            this.AddString(EditorStringId.CalculatorButtonNine, "9");
            this.AddString(EditorStringId.CalculatorButtonSign, "\x00b1");
            this.AddString(EditorStringId.CalculatorButtonAdd, "+");
            this.AddString(EditorStringId.CalculatorButtonSub, "-");
            this.AddString(EditorStringId.CalculatorButtonMul, "*");
            this.AddString(EditorStringId.CalculatorButtonDiv, "/");
            this.AddString(EditorStringId.CalculatorButtonFract, "1/x");
            this.AddString(EditorStringId.CalculatorButtonPercent, "%");
            this.AddString(EditorStringId.CalculatorButtonSqrt, "√");
            this.AddString(EditorStringId.CalculatorButtonEqual, "=");
            this.AddString(EditorStringId.CalculatorDivisionByZeroError, "Cannot divide by zero");
            this.AddString(EditorStringId.CalculatorError, "Error");
            this.AddString(EditorStringId.CalculatorInvalidInputError, "Invalid input");
            this.AddString(EditorStringId.FilterCriteriaToStringFunctionIsNullOrEmpty, "Is null or empty");
            this.AddString(EditorStringId.FilterCriteriaToStringFunctionStartsWith, "Starts with");
            this.AddString(EditorStringId.FilterCriteriaToStringFunctionEndsWith, "Ends with");
            this.AddString(EditorStringId.FilterCriteriaToStringFunctionContains, "Contains");
            this.AddString(EditorStringId.FilterCriteriaToStringBetween, "Between");
            this.AddString(EditorStringId.FilterCriteriaToStringBetweenDates, "Between dates");
            this.AddString(EditorStringId.FilterCriteriaToStringIn, "In");
            this.AddString(EditorStringId.FilterCriteriaToStringIsOnDates, "Is on dates");
            this.AddString(EditorStringId.FilterCriteriaToStringIsNotNull, "Is Not Null");
            this.AddString(EditorStringId.FilterCriteriaToStringNotLike, "Not Like");
            this.AddString(EditorStringId.FilterCriteriaToStringTopItems, "In Top {0} Items");
            this.AddString(EditorStringId.FilterCriteriaToStringBottomItems, "In Bottom {0} Items");
            this.AddString(EditorStringId.FilterCriteriaToStringTopPercent, "In Top {0}%");
            this.AddString(EditorStringId.FilterCriteriaToStringBottomPercent, "In Bottom {0}%");
            this.AddString(EditorStringId.FilterCriteriaToStringAboveAverage, "Above Average");
            this.AddString(EditorStringId.FilterCriteriaToStringBelowAverage, "Below Average");
            this.AddString(EditorStringId.FilterCriteriaToStringUnique, "Is Unique");
            this.AddString(EditorStringId.FilterCriteriaToStringDuplicate, "Is Duplicate");
            this.AddString(EditorStringId.TopBottomValueTypeItems, "Items");
            this.AddString(EditorStringId.TopBottomValueTypePercent, "Percent");
            this.AddString(EditorStringId.FilterCriteriaToStringBinaryOperatorBitwiseAnd, "&");
            this.AddString(EditorStringId.FilterCriteriaToStringBinaryOperatorBitwiseOr, "|");
            this.AddString(EditorStringId.FilterCriteriaToStringBinaryOperatorBitwiseXor, "^");
            this.AddString(EditorStringId.FilterCriteriaToStringBinaryOperatorDivide, "/");
            this.AddString(EditorStringId.FilterCriteriaToStringBinaryOperatorEqual, "=");
            this.AddString(EditorStringId.FilterCriteriaToStringBinaryOperatorGreater, ">");
            this.AddString(EditorStringId.FilterCriteriaToStringBinaryOperatorGreaterOrEqual, ">=");
            this.AddString(EditorStringId.FilterCriteriaToStringBinaryOperatorLess, "<");
            this.AddString(EditorStringId.FilterCriteriaToStringBinaryOperatorLessOrEqual, "<=");
            this.AddString(EditorStringId.FilterCriteriaToStringBinaryOperatorLike, "Like");
            this.AddString(EditorStringId.FilterCriteriaToStringBinaryOperatorMinus, "-");
            this.AddString(EditorStringId.FilterCriteriaToStringBinaryOperatorModulo, "%");
            this.AddString(EditorStringId.FilterCriteriaToStringBinaryOperatorMultiply, "*");
            this.AddString(EditorStringId.FilterCriteriaToStringBinaryOperatorNotEqual, "<>");
            this.AddString(EditorStringId.FilterCriteriaToStringBinaryOperatorPlus, "+");
            this.AddString(EditorStringId.FilterCriteriaToStringUnaryOperatorBitwiseNot, "~");
            this.AddString(EditorStringId.FilterCriteriaToStringUnaryOperatorIsNull, "Is Null");
            this.AddString(EditorStringId.FilterCriteriaToStringUnaryOperatorMinus, "-");
            this.AddString(EditorStringId.FilterCriteriaToStringUnaryOperatorNot, "Not");
            this.AddString(EditorStringId.FilterCriteriaToStringUnaryOperatorPlus, "+");
            this.AddString(EditorStringId.FilterCriteriaToStringGroupOperatorAnd, "And");
            this.AddString(EditorStringId.FilterCriteriaToStringGroupOperatorOr, "Or");
            this.AddString(EditorStringId.FilterCriteriaInvalidExpression, "The specified expression contains invalid symbols (line {0}, character {1}).");
            this.AddString(EditorStringId.FilterCriteriaInvalidExpressionEx, "The specified expression is invalid.");
            this.AddString(EditorStringId.ExpressionEditor_FunctionsSearch_NullText, "Enter text to search...");
            this.AddString(EditorStringId.ExpressionEditor_FunctionType_AllItems, "(All)");
            this.AddString(EditorStringId.ExpressionEditor_FunctionType_AggregateItems, "Aggregate");
            this.AddString(EditorStringId.ExpressionEditor_FunctionType_DateTimeItems, "Date-time");
            this.AddString(EditorStringId.ExpressionEditor_FunctionType_LogicalItems, "Logical");
            this.AddString(EditorStringId.ExpressionEditor_FunctionType_MathItems, "Math");
            this.AddString(EditorStringId.ExpressionEditor_FunctionType_StringItems, "String");
            this.AddString(EditorStringId.ExpressionEditor_Functions_Text, "Functions");
            this.AddString(EditorStringId.ExpressionEditor_Operators_Text, "Operators");
            this.AddString(EditorStringId.ExpressionEditor_Parameters_Text, "Parameters");
            this.AddString(EditorStringId.ExpressionEditor_Variables_Text, "Variables");
            this.AddString(EditorStringId.ExpressionEditor_Fields_Text, "Fields");
            this.AddString(EditorStringId.ExpressionEditor_Constants_Text, "Constants");
            this.AddString(EditorStringId.ExpressionEditor_Abs_Description, "Abs(Value)\r\nReturns the absolute, positive value of the given numeric expression.");
            this.AddString(EditorStringId.ExpressionEditor_Acos_Description, "Acos(Value)\r\nReturns the arccosine of a number (the angle, in radians, whose cosine is the given float expression).");
            this.AddString(EditorStringId.ExpressionEditor_AddDays_Description, "AddDays(DateTime, DaysCount)\r\nReturns a date-time value that is the specified number of days away from the specified DateTime.");
            this.AddString(EditorStringId.ExpressionEditor_AddHours_Description, "AddHours(DateTime, HoursCount)\r\nReturns a date-time value that is the specified number of hours away from the specified DateTime.");
            this.AddString(EditorStringId.ExpressionEditor_AddMilliSeconds_Description, "AddMilliSeconds(DateTime, MilliSecondsCount)\r\nReturns a date-time value that is the specified number of milliseconds away from the specified DateTime.");
            this.AddString(EditorStringId.ExpressionEditor_AddMinutes_Description, "AddMinutes(DateTime, MinutesCount)\r\nReturns a date-time value that is the specified number of minutes away from the specified DateTime.");
            this.AddString(EditorStringId.ExpressionEditor_AddMonths_Description, "AddMonths(DateTime, MonthsCount)\r\nReturns a date-time value that is the specified number of months away from the specified DateTime.");
            this.AddString(EditorStringId.ExpressionEditor_AddSeconds_Description, "AddSeconds(DateTime, SecondsCount)\r\nReturns a date-time value that is the specified number of seconds away from the specified DateTime.");
            this.AddString(EditorStringId.ExpressionEditor_AddTicks_Description, "AddTicks(DateTime, TicksCount)\r\nReturns a date-time value that is the specified number of ticks away from the specified DateTime.");
            this.AddString(EditorStringId.ExpressionEditor_AddTimeSpan_Description, "AddTimeSpan(DateTime, TimeSpan)\r\nReturns a date-time value that is away from the specified DateTime for the given TimeSpan.");
            this.AddString(EditorStringId.ExpressionEditor_AddYears_Description, "AddYears(DateTime, YearsCount)\r\nReturns a date-time value that is the specified number of years away from the specieid DateTime.");
            this.AddString(EditorStringId.ExpressionEditor_Ascii_Description, "Ascii(String)\r\nReturns the ASCII code value of the leftmost character in a character expression.");
            this.AddString(EditorStringId.ExpressionEditor_Asin_Description, "Asin(Value)\r\nReturns the arcsine of a number (the angle, in radians, whose sine is the given float expression).");
            this.AddString(EditorStringId.ExpressionEditor_Atn_Description, "Atn(Value)\r\nReturns the arctangent of a number (the angle, in radians, whose tangent is the given float expression).");
            this.AddString(EditorStringId.ExpressionEditor_Atn2_Description, "Atn2(Value1, Value2)\r\nReturns the angle whose tangent is the quotient of two specified numbers, in radians.");
            this.AddString(EditorStringId.ExpressionEditor_BigMul_Description, "BigMul(Value1, Value2)\r\nReturns an Int64 containing the full product of two specified 32-bit numbers.");
            this.AddString(EditorStringId.ExpressionEditor_Ceiling_Description, "Ceiling(Value)\r\nReturns the smallest integer that is greater than or equal to the given numeric expression.");
            this.AddString(EditorStringId.ExpressionEditor_Char_Description, "Char(Number)\r\nConverts an integerASCIICode to a character.");
            this.AddString(EditorStringId.ExpressionEditor_CharIndex_Description, "CharIndex(String1, String2)\r\nReturns the starting position of String1 within String2, beginning from the zero character position to the end of a string.");
            this.AddString(EditorStringId.ExpressionEditor_CharIndex3Param_Description, "CharIndex(String1, String2, StartLocation)\r\nReturns the starting position of String1 within String2, beginning from the StartLocation character position to the end of a string.");
            this.AddString(EditorStringId.ExpressionEditor_Concat_Description, "Concat(String1, ... , StringN)\r\nReturns a string value containing the concatenation of the current string with any additional strings.");
            this.AddString(EditorStringId.ExpressionEditor_Cos_Description, "Cos(Value)\r\nReturns the cosine of the angle defined in radians.");
            this.AddString(EditorStringId.ExpressionEditor_Cosh_Description, "Cosh(Value)\r\nReturns the hyperbolic cosine of the angle defined in radians.");
            this.AddString(EditorStringId.ExpressionEditor_DateDiffDay_Description, "DateDiffDay(startDate, endDate)\r\nReturns the number of day boundaries between two non-nullable dates.");
            this.AddString(EditorStringId.ExpressionEditor_DateDiffHour_Description, "DateDiffHour(startDate, endDate)\r\nReturns the number of hour boundaries between two non-nullable dates.");
            this.AddString(EditorStringId.ExpressionEditor_DateDiffMilliSecond_Description, "DateDiffMilliSecond(startDate, endDate)\r\nReturns the number of millisecond boundaries between two non-nullable dates.");
            this.AddString(EditorStringId.ExpressionEditor_DateDiffMinute_Description, "DateDiffMinute(startDate, endDate)\r\nReturns the number of minute boundaries between two non-nullable dates.");
            this.AddString(EditorStringId.ExpressionEditor_DateDiffMonth_Description, "DateDiffMonth(startDate, endDate)\r\nReturns the number of month boundaries between two non-nullable dates.");
            this.AddString(EditorStringId.ExpressionEditor_DateDiffSecond_Description, "DateDiffSecond(startDate, endDate)\r\nReturns the number of second boundaries between two non-nullable dates.");
            this.AddString(EditorStringId.ExpressionEditor_DateDiffTick_Description, "DateDiffTick(startDate, endDate)\r\nReturns the number of tick boundaries between two non-nullable dates.");
            this.AddString(EditorStringId.ExpressionEditor_DateDiffYear_Description, "DateDiffYear(startDate, endDate)\r\nReturns the number of year boundaries between two non-nullable dates.");
            this.AddString(EditorStringId.ExpressionEditor_Exp_Description, "Exp(Value)\r\nReturns the exponential value of the given float expression.");
            this.AddString(EditorStringId.ExpressionEditor_Floor_Description, "Floor(Value)\r\nReturns the largest integer less than or equal to the given numeric expression.");
            this.AddString(EditorStringId.ExpressionEditor_GetDate_Description, "GetDate(DateTime)\r\nExtracts a date from the defined DateTime.");
            this.AddString(EditorStringId.ExpressionEditor_GetDay_Description, "GetDay(DateTime)\r\nExtracts a day from the defined DateTime.");
            this.AddString(EditorStringId.ExpressionEditor_GetDayOfWeek_Description, "GetDayOfWeek(DateTime)\r\nExtracts a day of the week from the defined DateTime.");
            this.AddString(EditorStringId.ExpressionEditor_GetDayOfYear_Description, "GetDayOfYear(DateTime)\r\nExtracts a day of the year from the defined DateTime.");
            this.AddString(EditorStringId.ExpressionEditor_GetHour_Description, "GetHour(DateTime)\r\nExtracts an hour from the defined DateTime.");
            this.AddString(EditorStringId.ExpressionEditor_GetMilliSecond_Description, "GetMilliSecond(DateTime)\r\nExtracts milliseconds from the defined DateTime.");
            this.AddString(EditorStringId.ExpressionEditor_GetMinute_Description, "GetMinute(DateTime)\r\nExtracts minutes from the defined DateTime.");
            this.AddString(EditorStringId.ExpressionEditor_GetMonth_Description, "GetMonth(DateTime)\r\nExtracts a month from the defined DateTime.");
            this.AddString(EditorStringId.ExpressionEditor_GetSecond_Description, "GetSecond(DateTime)\r\nExtracts seconds from the defined DateTime.");
            this.AddString(EditorStringId.ExpressionEditor_GetTimeOfDay_Description, "GetTimeOfDay(DateTime)\r\nExtracts the time of the day from the defined DateTime, in ticks.");
            this.AddString(EditorStringId.ExpressionEditor_GetYear_Description, "GetYear(DateTime)\r\nExtracts a year from the defined DateTime.");
            this.AddString(EditorStringId.ExpressionEditor_Iif_Description, "Iif(Expression, TruePart, FalsePart)\r\nReturns either TruePart or FalsePart, depending on the evaluation of the Boolean Expression.");
            this.AddString(EditorStringId.ExpressionEditor_Insert_Description, "Insert(String1, StartPosition, String2)\r\nInserts String2 into String1 at the position specified by StartPositon");
            this.AddString(EditorStringId.ExpressionEditor_IsNull_Description, "IsNull(Value)\r\nReturns True if the specified Value is NULL.");
            this.AddString(EditorStringId.ExpressionEditor_IsNullOrEmpty_Description, "IsNullOrEmpty(String)\r\nReturns True if the specified String object is NULL or an empty string; otherwise, False is returned.");
            this.AddString(EditorStringId.ExpressionEditor_Len_Description, "Len(Value)\r\nReturns an integer containing either the number of characters in a string or the nominal number of bytes required to store a variable.");
            this.AddString(EditorStringId.ExpressionEditor_Log_Description, "Log(Value)\r\nReturns the natural logarithm of a specified number.");
            this.AddString(EditorStringId.ExpressionEditor_Log2Param_Description, "Log(Value, Base)\r\nReturns the logarithm of a specified number in a specified Base.");
            this.AddString(EditorStringId.ExpressionEditor_Log10_Description, "Log10(Value)\r\nReturns the base 10 logarithm of a specified number.");
            this.AddString(EditorStringId.ExpressionEditor_Lower_Description, "Lower(String)\r\nReturns the String in lowercase.");
            this.AddString(EditorStringId.ExpressionEditor_Now_Description, "Now()\r\nReturns the current system date and time.");
            this.AddString(EditorStringId.ExpressionEditor_PadLeft_Description, "PadLeft(String, Length)\r\nLeft-aligns characters in the defined string, padding its left side with white space characters up to a specified total length.");
            this.AddString(EditorStringId.ExpressionEditor_PadLeft3Param_Description, "PadLeft(String, Length, Char)\r\nLeft-aligns characters in the defined string, padding its left side with the specified Char up to a specified total length.");
            this.AddString(EditorStringId.ExpressionEditor_PadRight_Description, "PadRight(String, Length)\r\nRight-aligns characters in the defined string, padding its left side with white space characters up to a specified total length.");
            this.AddString(EditorStringId.ExpressionEditor_PadRight3Param_Description, "PadRight(String, Length, Char)\r\nRight-aligns characters in the defined string, padding its left side with the specified Char up to a specified total length.");
            this.AddString(EditorStringId.ExpressionEditor_Power_Description, "Power(Value, Power)\r\nReturns a specified number raised to a specified power.");
            this.AddString(EditorStringId.ExpressionEditor_Remove2Param_Description, "Remove(String, StartPosition)\r\nDeletes all characters from this instance, beginning at a specified position.");
            this.AddString(EditorStringId.ExpressionEditor_Remove3Param_Description, "Remove(String, StartPosition, Length)\r\nDeletes a specified number of characters from this instance, beginning at a specified position.");
            this.AddString(EditorStringId.ExpressionEditor_Replace_Description, "Replace(String, SubString2, String3)\r\nReturns a copy of String1, in which SubString2 has been replaced with String3.");
            this.AddString(EditorStringId.ExpressionEditor_Reverse_Description, "Reverse(String)\r\nReverses the order of elements within a string.");
            this.AddString(EditorStringId.ExpressionEditor_Rnd_Description, "Rnd()\r\nReturns a random number that is less than 1, but greater than or equal to zero.");
            this.AddString(EditorStringId.ExpressionEditor_Round_Description, "Round(Value)\r\nRounds the given value to the nearest integer.");
            this.AddString(EditorStringId.ExpressionEditor_Round2Param_Description, "Round(Value, Precision)\r\nRounds the given value to the nearest integer, or to a specified number of decimal places.");
            this.AddString(EditorStringId.ExpressionEditor_Sign_Description, "Sign(Value)\r\nReturns the positive (+1), zero (0), or negative (-1) sign of the given expression.");
            this.AddString(EditorStringId.ExpressionEditor_Sin_Description, "Sin(Value)\r\nReturns the sine of the angle, defined in radians.");
            this.AddString(EditorStringId.ExpressionEditor_Sinh_Description, "Sinh(Value)\r\nReturns the hyperbolic sine of the angle defined in radians.");
            this.AddString(EditorStringId.ExpressionEditor_Sqr_Description, "Sqr(Value)\r\nReturns the square root of a given number.");
            this.AddString(EditorStringId.ExpressionEditor_Substring3param_Description, "Substring(String, StartPosition, Length)\r\nRetrieves a substring from String. The substring starts at StartPosition and has the specified Length.");
            this.AddString(EditorStringId.ExpressionEditor_Substring2param_Description, "Substring(String, StartPosition)\r\nRetrieves a substring from String. The substring starts at StartPosition.");
            this.AddString(EditorStringId.ExpressionEditor_Tan_Description, "Tan(Value)\r\nReturns the tangent of the angle defined in radians.");
            this.AddString(EditorStringId.ExpressionEditor_Tanh_Description, "Tanh(Value)\r\nReturns the hyperbolic tangent of the angle defined in radians.");
            this.AddString(EditorStringId.ExpressionEditor_Today_Description, "Today()\r\nReturns the current date. Regardless of the actual time, this function returns midnight of the current date.");
            this.AddString(EditorStringId.ExpressionEditor_ToInt_Description, "ToInt(Value)\r\nConverts Value to an equivalent 32-bit signed integer.");
            this.AddString(EditorStringId.ExpressionEditor_ToLong_Description, "ToLong(Value)\r\nConverts Value to an equivalent 64-bit signed integer.");
            this.AddString(EditorStringId.ExpressionEditor_ToFloat_Description, "ToFloat(Value)\r\nConverts Value to an equivalent 32-bit single-precision floating-point number.");
            this.AddString(EditorStringId.ExpressionEditor_ToDouble_Description, "ToDouble(Value)\r\nConverts Value to an equivalent 64-bit double-precision floating-point number.");
            this.AddString(EditorStringId.ExpressionEditor_ToDecimal_Description, "ToDecimal(Value)\r\nConverts Value to an equivalent decimal number.");
            this.AddString(EditorStringId.ExpressionEditor_ToStr_Description, "ToStr(Value)\r\nReturns a string representation of an object.");
            this.AddString(EditorStringId.ExpressionEditor_Trim_Description, "Trim(String)\r\nRemoves all leading and trailing SPACE characters from String.");
            this.AddString(EditorStringId.ExpressionEditor_Upper_Description, "Upper(String)\r\nReturns String in uppercase.");
            this.AddString(EditorStringId.ExpressionEditor_UtcNow_Description, "UtcNow()\r\nReturns the current system date and time, expressed as Coordinated Universal Time (UTC).");
            this.AddString(EditorStringId.ExpressionEditor_LocalDateTimeDayAfterTomorrow_Description, "LocalDateTimeDayAfterTomorrow()\r\nReturns a date-time value corresponding to the day after Tomorrow.");
            this.AddString(EditorStringId.ExpressionEditor_LocalDateTimeLastWeek_Description, "LocalDateTimeLastWeek()\r\nReturns a date-time value corresponding to the first day of the previous week.");
            this.AddString(EditorStringId.ExpressionEditor_LocalDateTimeNextMonth_Description, "LocalDateTimeNextMonth()\r\nReturns a date-time value corresponding to the first day of next month.");
            this.AddString(EditorStringId.ExpressionEditor_LocalDateTimeNextWeek_Description, "LocalDateTimeNextWeek()\r\nReturns a date-time value corresponding to the first day of the following week.");
            this.AddString(EditorStringId.ExpressionEditor_LocalDateTimeNextYear_Description, "LocalDateTimeNextYear()\r\nReturns a date-time value corresponding to the first day of the following year.");
            this.AddString(EditorStringId.ExpressionEditor_LocalDateTimeNow_Description, "LocalDateTimeNow()\r\nReturns a date-time value corresponding to the current moment in time.");
            this.AddString(EditorStringId.ExpressionEditor_LocalDateTimeThisMonth_Description, "LocalDateTimeThisMonth()\r\nReturns a date-time value corresponding to the first day of the current month.");
            this.AddString(EditorStringId.ExpressionEditor_LocalDateTimeThisWeek_Description, "LocalDateTimeThisWeek()\r\nReturns a date-time value corresponding to the first day of the current week.");
            this.AddString(EditorStringId.ExpressionEditor_LocalDateTimeThisYear_Description, "LocalDateTimeThisYear()\r\nReturns a date-time value corresponding to the first day of the current year.");
            this.AddString(EditorStringId.ExpressionEditor_LocalDateTimeToday_Description, "LocalDateTimeToday()\r\nReturns a date-time value corresponding to Today.");
            this.AddString(EditorStringId.ExpressionEditor_LocalDateTimeTomorrow_Description, "LocalDateTimeTomorrow()\r\nReturns a date-time value corresponding to Tomorrow.");
            this.AddString(EditorStringId.ExpressionEditor_LocalDateTimeTwoWeeksAway_Description, "LocalDateTimeTwoWeeksAway()\r\nReturns a date-time value corresponding to the first day of the week that is after next week.");
            this.AddString(EditorStringId.ExpressionEditor_LocalDateTimeYesterday_Description, "LocalDateTimeYesterday()\r\nReturns a date-time value corresponding to Yesterday.");
            this.AddString(EditorStringId.ExpressionEditor_Plus_Description, "Adds the value of one numeric expression to another, or concatenates two strings.");
            this.AddString(EditorStringId.ExpressionEditor_Minus_Description, "Finds the difference between two numbers.");
            this.AddString(EditorStringId.ExpressionEditor_Multiply_Description, "Multiplies the value of two expressions.");
            this.AddString(EditorStringId.ExpressionEditor_Divide_Description, "Divides the first operand by the second.");
            this.AddString(EditorStringId.ExpressionEditor_Modulo_Description, "Returns the remainder (modulus) obtained by dividing one numeric expression into another.");
            this.AddString(EditorStringId.ExpressionEditor_BitwiseOr_Description, "Compares each bit of its first operand to the corresponding bit of its second operand. If either bit is 1, the corresponding result bit is set to 1. Otherwise, the corresponding result bit is set to 0.");
            this.AddString(EditorStringId.ExpressionEditor_BitwiseAnd_Description, "Performs a bitwise logical AND operation between two integer values.");
            this.AddString(EditorStringId.ExpressionEditor_BitwiseXor_Description, "Performs a logical exclusion on two Boolean expressions, or a bitwise exclusion on two numeric expressions.");
            this.AddString(EditorStringId.ExpressionEditor_Equal_Description, "Returns true if both operands have the same value; otherwise, it returns false.");
            this.AddString(EditorStringId.ExpressionEditor_NotEqual_Description, "Returns true if the operands do not have the same value; otherwise, it returns false.");
            this.AddString(EditorStringId.ExpressionEditor_Less_Description, "Less than operator. Used to compare expressions.");
            this.AddString(EditorStringId.ExpressionEditor_LessOrEqual_Description, "Less than or equal to operator. Used to compare expressions.");
            this.AddString(EditorStringId.ExpressionEditor_GreaterOrEqual_Description, "Greater than or equal to operator. Used to compare expressions.");
            this.AddString(EditorStringId.ExpressionEditor_Greater_Description, "Greater than operator. Used to compare expressions.");
            this.AddString(EditorStringId.ExpressionEditor_In_Description, "In (,,,)\r\nTests for the existence of a property in an object.");
            this.AddString(EditorStringId.ExpressionEditor_Like_Description, "Compares a string against a pattern. If the value of the string matches the pattern, result is true. If the string does not match the pattern, result is false. If both string and pattern are empty strings, the result is true.");
            this.AddString(EditorStringId.ExpressionEditor_Between_Description, "Between (,)\r\nSpecifies a range to test. Returns true if a value is greater than or equal to the first operand and less than or equal to the second operand.");
            this.AddString(EditorStringId.ExpressionEditor_And_Description, "Performs a logical conjunction on two expressions.");
            this.AddString(EditorStringId.ExpressionEditor_Or_Description, "Performs a logical disjunction on two Boolean expressions.");
            this.AddString(EditorStringId.ExpressionEditor_Not_Description, "Performs logical negation on an expression.");
            this.AddString(EditorStringId.ExpressionEditor_Max_Description, "Max(Value1, Value2)\r\nReturns the maximum value from the specified values.");
            this.AddString(EditorStringId.ExpressionEditor_Min_Description, "Min(Value1, Value2)\r\nReturns the minimum value from the specified values.");
            this.AddString(EditorStringId.ExpressionEditor_StartsWith_Description, "StartsWith(String, StartString)\r\nReturns True if the beginning of String matches StartString; otherwise, False is returned.");
            this.AddString(EditorStringId.ExpressionEditor_EndsWith_Description, "EndsWith(String, EndString)\r\nReturns True if the end of String matches EndString; otherwise, False is returned.");
            this.AddString(EditorStringId.ExpressionEditor_Contains_Description, "Contains(String, SubString)\r\nReturns True if SubString occurs within String; otherwise, False is returned.");
            this.AddString(EditorStringId.ExpressionEditor_IsThisYear_Description, "IsThisYear(DateTime)\r\nReturns True if the specified date falls within the current year.");
            this.AddString(EditorStringId.ExpressionEditor_IsThisMonth_Description, "IsThisMonth(DateTime)\r\nReturns True if the specified date falls within the current month.");
            this.AddString(EditorStringId.ExpressionEditor_IsThisWeek_Description, "IsThisWeek(DateTime)\r\nReturns True if the specified date falls within the current week.");
            this.AddString(EditorStringId.ExpressionEditor_LocalDateTimeLastMonth_Description, "LocalDateTimeLastMonth()\r\nReturns a date-time value corresponding to the first day of the previous month.");
            this.AddString(EditorStringId.ExpressionEditor_LocalDateTimeLastYear_Description, "LocalDateTimeLastYear()\r\nReturns a date-time value corresponding to the first day of the previous year.");
            this.AddString(EditorStringId.ExpressionEditor_LocalDateTimeTwoMonthsAway_Description, "LocalDateTimeTwoMonthsAway()\r\nReturns a date-time value corresponding to the first day of the month after next.");
            this.AddString(EditorStringId.ExpressionEditor_LocalDateTimeTwoYearsAway_Description, "LocalDateTimeTwoYearsAway()\r\nReturns a date-time value corresponding to the first day of the year after next.");
            this.AddString(EditorStringId.ExpressionEditor_LocalDateTimeYearBeforeToday_Description, "LocalDateTimeYearBeforeToday()\r\nReturns a date-time value corresponding to the day one year ago.");
            this.AddString(EditorStringId.ExpressionEditor_IsLastMonth_Description, "IsLastMonth(DateTime)\r\nReturns True if the specified date falls within the previous month.");
            this.AddString(EditorStringId.ExpressionEditor_IsLastYear_Description, "IsLastYear(DateTime)\r\nReturns True if the specified date falls within the previous year.");
            this.AddString(EditorStringId.ExpressionEditor_IsNextMonth_Description, "IsNextMonth(DateTime)\r\nReturns True if the specified date falls within the next month.");
            this.AddString(EditorStringId.ExpressionEditor_IsNextYear_Description, "IsNextYear(DateTime)\r\nReturns True if the specified date falls within the next year.");
            this.AddString(EditorStringId.ExpressionEditor_IsYearToDate_Description, "IsYearToDate(DateTime)\r\nReturns True if the specified date falls within the year-to-date period (starting from the first day of the current year and continuing up to the current date).");
            this.AddString(EditorStringId.ExpressionEditor_IsJanuary_Description, "IsJanuary(DateTime)\r\nReturns True if the specified date falls within January.");
            this.AddString(EditorStringId.ExpressionEditor_IsFebruary_Description, "IsFebruary(DateTime)\r\nReturns True if the specified date falls within February.");
            this.AddString(EditorStringId.ExpressionEditor_IsMarch_Description, "IsMarch(DateTime)\r\nReturns True if the specified date falls within March.");
            this.AddString(EditorStringId.ExpressionEditor_IsApril_Description, "IsApril(DateTime)\r\nReturns True if the specified date falls within April.");
            this.AddString(EditorStringId.ExpressionEditor_IsMay_Description, "IsMay(DateTime)\r\nReturns True if the specified date falls within May.");
            this.AddString(EditorStringId.ExpressionEditor_IsJune_Description, "IsJune(DateTime)\r\nReturns True if the specified date falls within June.");
            this.AddString(EditorStringId.ExpressionEditor_IsJuly_Description, "IsJuly(DateTime)\r\nReturns True if the specified date falls within July.");
            this.AddString(EditorStringId.ExpressionEditor_IsAugust_Description, "IsAugust(DateTime)\r\nReturns True if the specified date falls within August.");
            this.AddString(EditorStringId.ExpressionEditor_IsSeptember_Description, "IsSeptember(DateTime)\r\nReturns True if the specified date falls within September.");
            this.AddString(EditorStringId.ExpressionEditor_IsOctober_Description, "IsOctober(DateTime)\r\nReturns True if the specified date falls within October.");
            this.AddString(EditorStringId.ExpressionEditor_IsNovember_Description, "IsNovember(DateTime)\r\nReturns True if the specified date falls within November.");
            this.AddString(EditorStringId.ExpressionEditor_IsDecember_Description, "IsDecember(DateTime)\r\nReturns True if the specified date falls within December.");
            this.AddString(EditorStringId.ExpressionEditor_IsSameDay_Description, "IsSameDay(DateTime, DateTime)\r\nReturns True if the specified date-time values fall within the same day.");
            this.AddString(EditorStringId.ExpressionEditor_GridFields_Description_Prefix, "Field Information\r\nCaption: {1}\r\nThe type of this field is: {2}");
            this.AddString(EditorStringId.ExpressionEditor_Fields_Description_Prefix, "The type of this field is: {0}");
            this.AddString(EditorStringId.ExpressionEditor_Parameters_Description_Prefix, "The type of this parameter is: {0}");
            this.AddString(EditorStringId.ExpressionEditor_True_Description, "Represents the Boolean True value.");
            this.AddString(EditorStringId.ExpressionEditor_False_Description, "Represents the Boolean False value.");
            this.AddString(EditorStringId.ExpressionEditor_Null_Description, "Represents a null reference, one that does not refer to any object.");
            this.AddString(EditorStringId.ExpressionEditor_Title, "Expression Editor");
            this.AddString(EditorStringId.ExpressionEditor_AvgAggregate_Description, "Avg(Value)\r\nEvaluates the average of the values in the collection.");
            this.AddString(EditorStringId.ExpressionEditor_CountAggregate_Description, "Count()\r\nReturns the number of objects in a collection.");
            this.AddString(EditorStringId.ExpressionEditor_ExistsAggregate_Description, "Exists()\r\nDetermines whether the object exists in the collection.");
            this.AddString(EditorStringId.ExpressionEditor_MaxAggregate_Description, "Max(Value)\r\nReturns the maximum expression value in a collection.");
            this.AddString(EditorStringId.ExpressionEditor_MinAggregate_Description, "Min(Value)\r\nReturns the minimum expression value in a collection.");
            this.AddString(EditorStringId.ExpressionEditor_SumAggregate_Description, "Sum(Value)\r\nReturns the sum of all the expression values in the collection.");
            this.AddString(EditorStringId.ExpressionEditor_SingleAggregate_Description, "Single()\r\nReturns a single object from the collection.");
            this.AddString(EditorStringId.ExpressionEditor_RowCount_Description, "Returns the total amount of data rows in a datasource.");
            this.AddString(EditorStringId.ExpressionEditor_CurrentRowIndex_Description, "Returns the index of the current data row in a datasource. Note that this index is zero-based.");
            this.AddString(EditorStringId.FilterGroupAnd, "And");
            this.AddString(EditorStringId.FilterGroupOr, "Or");
            this.AddString(EditorStringId.FilterGroupNotAnd, "NotAnd");
            this.AddString(EditorStringId.FilterGroupNotOr, "NotOr");
            this.AddString(EditorStringId.FilterGroupNotAndMenuCaption, "Not And");
            this.AddString(EditorStringId.FilterGroupNotOrMenuCaption, "Not Or");
            this.AddString(EditorStringId.FilterGroupAddCondition, "Add Condition");
            this.AddString(EditorStringId.FilterGroupAddGroup, "Add Group");
            this.AddString(EditorStringId.FilterGroupAddCustomExpression, "Add Custom Expression");
            this.AddString(EditorStringId.FilterGroupRemoveGroup, "Remove Group");
            this.AddString(EditorStringId.FilterGroupClearAll, "Clear All");
            this.AddString(EditorStringId.FilterEmptyValueText, "<enter a value>");
            this.AddString(EditorStringId.FilterEmptyPropertyText, "<select a property>");
            this.AddString(EditorStringId.FilterEmptyParameterText, "<select a parameter>");
            this.AddString(EditorStringId.FilterExpressionEmptyValueText, "Enter an expression");
            this.AddString(EditorStringId.FilterRulesEmptyValueText, "Enter a value...");
            this.AddString(EditorStringId.FilterNoPropertiesFoundText, "No Properties Found");
            this.AddString(EditorStringId.FilterClauseAnyOf, "Is any of");
            this.AddString(EditorStringId.FilterClauseBeginsWith, "Begins with");
            this.AddString(EditorStringId.FilterClauseBetween, "Is between");
            this.AddString(EditorStringId.FilterClauseBetweenAnd, "and");
            this.AddString(EditorStringId.FilterClauseContains, "Contains");
            this.AddString(EditorStringId.FilterClauseEndsWith, "Ends with");
            this.AddString(EditorStringId.FilterClauseEquals, "Equals");
            this.AddString(EditorStringId.FilterClauseGreater, "Is greater than");
            this.AddString(EditorStringId.FilterClauseGreaterOrEqual, "Is greater than or equal to");
            this.AddString(EditorStringId.FilterClauseIsNull, "Is null");
            this.AddString(EditorStringId.FilterClauseIsNotNull, "Is not null");
            this.AddString(EditorStringId.FilterClauseLess, "Is less than");
            this.AddString(EditorStringId.FilterClauseLessOrEqual, "Is less than or equal to");
            this.AddString(EditorStringId.FilterClauseLike, "Is like");
            this.AddString(EditorStringId.FilterClauseNoneOf, "Is none of");
            this.AddString(EditorStringId.FilterClauseNotBetween, "Is not between");
            this.AddString(EditorStringId.FilterClauseDoesNotContain, "Does not contain");
            this.AddString(EditorStringId.FilterClauseDoesNotEqual, "Does not equal");
            this.AddString(EditorStringId.FilterClauseNotLike, "Is not like");
            this.AddString(EditorStringId.FilterClauseIsNullOrEmpty, "Is blank");
            this.AddString(EditorStringId.FilterClauseIsNotNullOrEmpty, "Is not blank");
            this.AddString(EditorStringId.FilterClauseIsOn, "Is on");
            this.AddString(EditorStringId.FilterClauseIsNotOn, "Is not on");
            this.AddString(EditorStringId.FilterClauseBetweenDates, "Is between dates");
            this.AddString(EditorStringId.FilterClauseIsOnDates, "Is on dates");
            this.AddString(EditorStringId.FilterClauseIsOnAnyOfTheFollowing, "Is on any of the following");
            this.AddString(EditorStringId.FilterClauseIsBeyondThisYear, "Is Beyond This Year");
            this.AddString(EditorStringId.FilterClauseIsLaterThisYear, "Is Later This Year");
            this.AddString(EditorStringId.FilterClauseIsLaterThisMonth, "Is Later This Month");
            this.AddString(EditorStringId.FilterClauseIsNextWeek, "Is Next Week");
            this.AddString(EditorStringId.FilterClauseIsLaterThisWeek, "Is Later This Week");
            this.AddString(EditorStringId.FilterClauseIsTomorrow, "Is Tomorrow");
            this.AddString(EditorStringId.FilterClauseIsToday, "Is Today");
            this.AddString(EditorStringId.FilterClauseIsYesterday, "Is Yesterday");
            this.AddString(EditorStringId.FilterClauseIsEarlierThisWeek, "Is Earlier This Week");
            this.AddString(EditorStringId.FilterClauseIsLastWeek, "Is Last Week");
            this.AddString(EditorStringId.FilterClauseIsEarlierThisMonth, "Is Earlier This Month");
            this.AddString(EditorStringId.FilterClauseIsEarlierThisYear, "Is Earlier This Year");
            this.AddString(EditorStringId.FilterClauseIsPriorThisYear, "Is Prior This Year");
            this.AddString(EditorStringId.FilterClauseIsJanuary, "Is January");
            this.AddString(EditorStringId.FilterClauseIsFebruary, "Is February");
            this.AddString(EditorStringId.FilterClauseIsMarch, "Is March");
            this.AddString(EditorStringId.FilterClauseIsApril, "Is April");
            this.AddString(EditorStringId.FilterClauseIsMay, "Is May");
            this.AddString(EditorStringId.FilterClauseIsJune, "Is June");
            this.AddString(EditorStringId.FilterClauseIsJuly, "Is July");
            this.AddString(EditorStringId.FilterClauseIsAugust, "Is August");
            this.AddString(EditorStringId.FilterClauseIsSeptember, "Is September");
            this.AddString(EditorStringId.FilterClauseIsOctober, "Is October");
            this.AddString(EditorStringId.FilterClauseIsNovember, "Is November");
            this.AddString(EditorStringId.FilterClauseIsDecember, "Is December");
            this.AddString(EditorStringId.FilterClauseLocalDateTimeThisYear, "This year");
            this.AddString(EditorStringId.FilterClauseLocalDateTimeThisMonth, "This month");
            this.AddString(EditorStringId.FilterClauseLocalDateTimeLastWeek, "Last week");
            this.AddString(EditorStringId.FilterClauseLocalDateTimeThisWeek, "This week");
            this.AddString(EditorStringId.FilterClauseLocalDateTimeYesterday, "Yesterday");
            this.AddString(EditorStringId.FilterClauseLocalDateTimeToday, "Today");
            this.AddString(EditorStringId.FilterClauseLocalDateTimeNow, "Now");
            this.AddString(EditorStringId.FilterClauseLocalDateTimeTomorrow, "Tomorrow");
            this.AddString(EditorStringId.FilterClauseLocalDateTimeDayAfterTomorrow, "Day after tomorrow");
            this.AddString(EditorStringId.FilterClauseLocalDateTimeNextWeek, "Next week");
            this.AddString(EditorStringId.FilterClauseLocalDateTimeTwoWeeksAway, "Two weeks away");
            this.AddString(EditorStringId.FilterClauseLocalDateTimeNextMonth, "Next month");
            this.AddString(EditorStringId.FilterClauseLocalDateTimeNextYear, "Next year");
            this.AddString(EditorStringId.FilterDateTimeOperatorMenuCaption, "DateTime operators");
            this.AddString(EditorStringId.FilterClauseIsOutlookIntervalBeyondThisYear, "Beyond This Year");
            this.AddString(EditorStringId.FilterClauseIsOutlookIntervalLaterThisYear, "Later This Year");
            this.AddString(EditorStringId.FilterClauseIsOutlookIntervalLaterThisMonth, "Later This Month");
            this.AddString(EditorStringId.FilterClauseIsOutlookIntervalNextWeek, "Next Week");
            this.AddString(EditorStringId.FilterClauseIsOutlookIntervalLaterThisWeek, "Later This Week");
            this.AddString(EditorStringId.FilterClauseIsOutlookIntervalTomorrow, "Tomorrow");
            this.AddString(EditorStringId.FilterClauseIsOutlookIntervalToday, "Today");
            this.AddString(EditorStringId.FilterClauseIsOutlookIntervalYesterday, "Yesterday");
            this.AddString(EditorStringId.FilterClauseIsOutlookIntervalEarlierThisWeek, "Earlier This Week");
            this.AddString(EditorStringId.FilterClauseIsOutlookIntervalLastWeek, "Last Week");
            this.AddString(EditorStringId.FilterClauseIsOutlookIntervalEarlierThisMonth, "Earlier This Month");
            this.AddString(EditorStringId.FilterClauseIsOutlookIntervalEarlierThisYear, "Earlier This Year");
            this.AddString(EditorStringId.FilterClauseIsOutlookIntervalPriorThisYear, "Prior This Year");
            this.AddString(EditorStringId.DateIntervalsMenuCaption, "Date intervals");
            this.AddString(EditorStringId.FilterEditorChecked, "Checked");
            this.AddString(EditorStringId.FilterEditorUnchecked, "Unchecked");
            this.AddString(EditorStringId.FilterToolTipNodeAction, "Actions");
            this.AddString(EditorStringId.FilterToolTipNodeAdd, "Adds a new condition to this group");
            this.AddString(EditorStringId.FilterToolTipNodeRemove, "Removes this condition");
            this.AddString(EditorStringId.FilterToolTipValueType, "Compare with a value / another field's value");
            this.AddString(EditorStringId.FilterToolTipElementAdd, "Adds a new item to the list");
            this.AddString(EditorStringId.FilterToolTipElementEdit, "Edits this condition in the Expression Editor");
            this.AddString(EditorStringId.FilterToolTipKeysAdd, "(Use the Insert or Add key)");
            this.AddString(EditorStringId.FilterToolTipKeysRemove, "(Use the Delete or Subtract key)");
            this.AddString(EditorStringId.FilterElementClauseFrom, "From");
            this.AddString(EditorStringId.FilterElementClauseTo, "To");
            this.AddString(EditorStringId.FilterElementFilterRules, "Filter Rules");
            this.AddString(EditorStringId.FilterElementFilterValues, "Filter Values");
            this.AddString(EditorStringId.FilterElementAllItem, "(All)");
            this.AddString(EditorStringId.FilterElementBlanksItem, "(Blanks)");
            this.AddString(EditorStringId.FilterElementEmptyItem, "(Empty)");
            this.AddString(EditorStringId.FilterElementRadioAllItem, "(All)");
            this.AddString(EditorStringId.FilterElementDateRangeFrom, "From");
            this.AddString(EditorStringId.FilterElementDateRangeTo, "To");
            this.AddString(EditorStringId.FilterValuesSortModeNoSort, "Sort: Value");
            this.AddString(EditorStringId.FilterValuesSortModeAvailableFirst, "Sort: Availability");
            this.AddString(EditorStringId.FilterValuesSortModePopularFirst, "Sort: Quantity");
            this.AddString(EditorStringId.PredefinedFilters, "Predefined filters");
            this.AddString(EditorStringId.FormatConditionFilters, "Format condition filters");
            this.AddString(EditorStringId.PredefinedFormatConditionTop, "Top N");
            this.AddString(EditorStringId.PredefinedFormatConditionBottom, "Bottom N");
            this.AddString(EditorStringId.PredefinedFormatConditionAboveAverage, "Above Average");
            this.AddString(EditorStringId.PredefinedFormatConditionBelowAverage, "Below Average");
            this.AddString(EditorStringId.PredefinedFormatConditionUnique, "Unique");
            this.AddString(EditorStringId.PredefinedFormatConditionDuplicate, "Duplicate");
            this.AddString(EditorStringId.FilterOperandValue, "Value");
            this.AddString(EditorStringId.FilterOperandProperty, "Property");
            this.AddString(EditorStringId.FilterOperandParameter, "Parameter");
            this.AddString(EditorStringId.FilterPanelEditFilter, "Edit Filter");
            this.AddString(EditorStringId.FilterPanelClearFilter, "Clear Filter");
            this.AddString(EditorStringId.FilterPanelEnableFilter, "Enable Filter");
            this.AddString(EditorStringId.FilterPanelDisableFilter, "Disable Filter");
            this.AddString(EditorStringId.ColorEdit_AutomaticButtonCaption, "Automatic");
            this.AddString(EditorStringId.ColorEdit_NoColorButtonCaption, "No Color");
            this.AddString(EditorStringId.ColorEdit_MoreColorsButtonCaption, "More Colors...");
            this.AddString(EditorStringId.ColorEdit_RecentColorsCaption, "Recent Colors");
            this.AddString(EditorStringId.ColorEdit_ColorChooserWindowTitle, "Colors");
            this.AddString(EditorStringId.ColorEdit_ColorChooserWindowTitle, "Colors");
            this.AddString(EditorStringId.ColorEdit_ThemeColorsCaption, "Theme Colors");
            this.AddString(EditorStringId.ColorEdit_StandardColorsCaption, "Standard Colors");
            this.AddString(EditorStringId.ColorEdit_DefaultColors_Black, "Black");
            this.AddString(EditorStringId.ColorEdit_DefaultColors_White, "White");
            this.AddString(EditorStringId.ColorEdit_DefaultColors_DarkRed, "DarkRed");
            this.AddString(EditorStringId.ColorEdit_DefaultColors_Red, "Red");
            this.AddString(EditorStringId.ColorEdit_DefaultColors_Orange, "Orange");
            this.AddString(EditorStringId.ColorEdit_DefaultColors_Yellow, "Yellow");
            this.AddString(EditorStringId.ColorEdit_DefaultColors_LightGreen, "LightGreen");
            this.AddString(EditorStringId.ColorEdit_DefaultColors_Green, "Green");
            this.AddString(EditorStringId.ColorEdit_DefaultColors_LightBlue, "LightBlue");
            this.AddString(EditorStringId.ColorEdit_DefaultColors_Blue, "Blue");
            this.AddString(EditorStringId.ColorEdit_DefaultColors_DarkBlue, "DarkBlue");
            this.AddString(EditorStringId.ColorEdit_DefaultColors_Purple, "Purple");
            this.AddString(EditorStringId.ImageEdit_OpenFileFilter, "Image Files(*.BMP;*.JPG;*.GIF;*.PNG)|*.BMP;*.JPG;*.GIF;*.PNG|All files (*.*)|*.*");
            this.AddString(EditorStringId.ImageEdit_OpenFileFilter_SL, "Image Files(*.JPG;*.PNG)|*.JPG;*.PNG|All files (*.*)|*.*");
            this.AddString(EditorStringId.ImageEdit_SaveFileFilter, "PNG(*.png)|*.png|BMP(*.bmp)|*.BMP|JPG(*.jpg)|*.jpg|GIF(*.gif)|*.gif");
            this.AddString(EditorStringId.ImageEdit_InvalidFormatMessage, "Wrong image format");
            this.AddString(EditorStringId.PasswordBoxEditToolTipHeader, "Caps Lock is On");
            this.AddString(EditorStringId.PasswordBoxEditToolTipContent, $"Enabling Caps Lock may result in entering password incorrectly.{Environment.NewLine}Disable Caps Lock before entering your password.");
            this.AddString(EditorStringId.CantModifySelectedDates, "Can only change SelectedDates collection in multiple selection mode. Use FocusedDate in single select mode.");
            this.AddString(EditorStringId.Page, "Page");
            this.AddString(EditorStringId.Of, "of {0}");
            this.AddString(EditorStringId.NextPage, "Next Page");
            this.AddString(EditorStringId.PrevPage, "Previous Page");
            this.AddString(EditorStringId.LastPage, "Last Page");
            this.AddString(EditorStringId.FirstPage, "First Page");
            this.AddString(EditorStringId.RefreshPage, "Refresh");
            this.AddString(EditorStringId.DisplayFormatHelperWrongDisplayFormatValue, "Invalid display format text");
            this.AddString(EditorStringId.DisplayFormatTextControlExample, "Example: ");
            this.AddString(EditorStringId.DisplayFormatTextControlPrefix, "Prefix:");
            this.AddString(EditorStringId.DisplayFormatTextControlSuffix, "Suffix:");
            this.AddString(EditorStringId.DisplayFormatTextControlDisplayFormatText, "Display format text:");
            this.AddString(EditorStringId.DataTypeStringExample, "ABCXYZ");
            this.AddString(EditorStringId.DataTypeCharExample, "A");
            this.AddString(EditorStringId.DisplayFormatNullValue, "None");
            this.AddString(EditorStringId.DisplayFormatGroupTypeDefault, "Default");
            this.AddString(EditorStringId.DisplayFormatGroupTypeNumber, "Number");
            this.AddString(EditorStringId.DisplayFormatGroupTypePercent, "Percent");
            this.AddString(EditorStringId.DisplayFormatGroupTypeCurrency, "Currency");
            this.AddString(EditorStringId.DisplayFormatGroupTypeSpecial, "Special");
            this.AddString(EditorStringId.DisplayFormatGroupTypeDatetime, "Datetime");
            this.AddString(EditorStringId.DisplayFormatGroupTypeCustom, "Custom");
            this.AddString(EditorStringId.ConfirmationDialogMessage, "The font \"{0}\" is not available on your system. Do you want to use it anyway?");
            this.AddString(EditorStringId.ConfirmationDialogCaption, "Confirmation");
            this.AddString(EditorStringId.CheckChecked, "Checked");
            this.AddString(EditorStringId.CheckUnchecked, "Unchecked");
            this.AddString(EditorStringId.CheckIndeterminate, "Indeterminate");
            this.AddString(EditorStringId.CMYK, "CMYK");
            this.AddString(EditorStringId.RGB, "RGB");
            this.AddString(EditorStringId.HLS, "HLS");
            this.AddString(EditorStringId.HSB, "HSB");
            this.AddString(EditorStringId.ColorPickerAlpha, "Alpha");
            this.AddString(EditorStringId.ColorPickerBlue, "Blue");
            this.AddString(EditorStringId.ColorPickerBrightness, "Brightness");
            this.AddString(EditorStringId.ColorPickerCyan, "Cyan");
            this.AddString(EditorStringId.ColorPickerGreen, "Green");
            this.AddString(EditorStringId.ColorPickerHue, "Hue");
            this.AddString(EditorStringId.ColorPickerKeyColor, "Key color");
            this.AddString(EditorStringId.ColorPickerLightness, "Lightness");
            this.AddString(EditorStringId.ColorPickerMagenta, "Magenta");
            this.AddString(EditorStringId.ColorPickerRed, "Red");
            this.AddString(EditorStringId.ColorPickerSaturation, "Saturation");
            this.AddString(EditorStringId.ColorPickerYellow, "Yellow");
            this.AddString(EditorStringId.Caption_CommonCharactersToggleButton, "Common Characters");
            this.AddString(EditorStringId.Caption_SpecialCharactersToggleButton, "Special Characters");
            this.AddString(EditorStringId.Caption_SymbolFormSearchByCode, "Search by code:");
            this.AddString(EditorStringId.Caption_SymbolFormFontName, "Font name:");
            this.AddString(EditorStringId.Caption_SymbolFormCharacterSet, "Character set:");
            this.AddString(EditorStringId.Caption_SymbolFormFilter, "Filter:");
            this.AddString(EditorStringId.Caption_EncodingUnicode, "Unicode");
            this.AddString(EditorStringId.Caption_UnicodeCategoryAllSymbols, "All Symbols");
            this.AddString(EditorStringId.Caption_UnicodeCategoryUppercaseLetter, "Uppercase Letter");
            this.AddString(EditorStringId.Caption_UnicodeCategoryLowercaseLetter, "Lowercase Letter");
            this.AddString(EditorStringId.Caption_UnicodeCategoryTitlecaseLetter, "Titlecase Letter");
            this.AddString(EditorStringId.Caption_UnicodeCategoryModifierLetter, "Modifier Letter");
            this.AddString(EditorStringId.Caption_UnicodeCategoryOtherLetter, "Other Letter");
            this.AddString(EditorStringId.Caption_UnicodeCategoryNonSpacingMark, "Nonspacing Mark");
            this.AddString(EditorStringId.Caption_UnicodeCategorySpacingCombiningMark, "Spacing Combining Mark");
            this.AddString(EditorStringId.Caption_UnicodeCategoryEnclosingMark, "Enclosing Mark");
            this.AddString(EditorStringId.Caption_UnicodeCategoryDecimalDigitNumber, "Decimal Digit Number");
            this.AddString(EditorStringId.Caption_UnicodeCategoryLetterNumber, "Letter Number");
            this.AddString(EditorStringId.Caption_UnicodeCategoryOtherNumber, "Other Number");
            this.AddString(EditorStringId.Caption_UnicodeCategorySpaceSeparator, "Space Separator");
            this.AddString(EditorStringId.Caption_UnicodeCategoryLineSeparator, "Line Separator");
            this.AddString(EditorStringId.Caption_UnicodeCategoryParagraphSeparator, "Paragraph Separator");
            this.AddString(EditorStringId.Caption_UnicodeCategoryControl, "Control");
            this.AddString(EditorStringId.Caption_UnicodeCategoryFormat, "Format");
            this.AddString(EditorStringId.Caption_UnicodeCategorySurrogate, "Surrogate");
            this.AddString(EditorStringId.Caption_UnicodeCategoryPrivateUse, "Private-use");
            this.AddString(EditorStringId.Caption_UnicodeCategoryConnectorPunctuation, "Connector Punctuation");
            this.AddString(EditorStringId.Caption_UnicodeCategoryDashPunctuation, "Dash Punctuation");
            this.AddString(EditorStringId.Caption_UnicodeCategoryOpenPunctuation, "Open Punctuation");
            this.AddString(EditorStringId.Caption_UnicodeCategoryClosePunctuation, "Close Punctuation");
            this.AddString(EditorStringId.Caption_UnicodeCategoryInitialQuotePunctuation, "Initial Quote Punctuation");
            this.AddString(EditorStringId.Caption_UnicodeCategoryFinalQuotePunctuation, "Final Quote Punctuation");
            this.AddString(EditorStringId.Caption_UnicodeCategoryOtherPunctuation, "Other Punctuation");
            this.AddString(EditorStringId.Caption_UnicodeCategoryMathSymbol, "Math Symbol");
            this.AddString(EditorStringId.Caption_UnicodeCategoryCurrencySymbol, "Currency Symbol");
            this.AddString(EditorStringId.Caption_UnicodeCategoryModifierSymbol, "Modifier Symbol");
            this.AddString(EditorStringId.Caption_UnicodeCategoryOtherSymbol, "Other Symbol");
            this.AddString(EditorStringId.Caption_UnicodeCategoryOtherNotAssigned, "Other Not Assigned");
            this.AddString(EditorStringId.DatePickerHours, "hours");
            this.AddString(EditorStringId.DatePickerMilliseconds, "msecs");
            this.AddString(EditorStringId.DatePickerMinutes, "mins");
            this.AddString(EditorStringId.DatePickerSeconds, "secs");
            this.AddString(EditorStringId.BrushEditNone, "None");
            this.AddString(EditorStringId.BrushEditSolid, "Solid");
            this.AddString(EditorStringId.BrushEditLinear, "Linear");
            this.AddString(EditorStringId.BrushEditRadial, "Radial");
            this.AddString(EditorStringId.BrushEditStartPoint, "StartPoint");
            this.AddString(EditorStringId.BrushEditStartPointDescription, "Gets or sets the two-dimensional coordinates for the start point of the linear gradient.");
            this.AddString(EditorStringId.BrushEditEndPoint, "EndPoint");
            this.AddString(EditorStringId.BrushEditEndPointDescription, "Gets or sets the two-dimensional coordinates for the end point of the linear gradient.");
            this.AddString(EditorStringId.BrushEditMappingMode, "MappingMode");
            this.AddString(EditorStringId.BrushEditMappingModeDescription, "Gets or sets a value that specifies whether the gradient brush positioning coordinates are absolute or relative to the output area.");
            this.AddString(EditorStringId.BrushEditSpreadMethod, "SpreadMethod");
            this.AddString(EditorStringId.BrushEditSpreadMethodDescription, "Gets or sets the type of spread method that specifies how to draw a gradient that starts or ends inside the bounds of the object to be painted.");
            this.AddString(EditorStringId.BrushEditGradientOrigin, "GradientOrigin");
            this.AddString(EditorStringId.BrushEditGradientOriginDescription, "Gets or sets the two-dimensional focal point that defines the beginning of a gradient.");
            this.AddString(EditorStringId.BrushEditCenter, "Center");
            this.AddString(EditorStringId.BrushEditCenterDescription, "Gets or sets the center of the outermost circle of the radial gradient.");
            this.AddString(EditorStringId.BrushEditRadiusX, "RadiusX");
            this.AddString(EditorStringId.BrushEditRadiusXDescription, "Gets or sets the horizontal radius of the outermost circle of the radial gradient.");
            this.AddString(EditorStringId.BrushEditRadiusY, "RadiusY");
            this.AddString(EditorStringId.BrushEditRadiusYDescription, "Gets or sets the vertical radius of the outermost circle of the radial gradient.");
            this.AddString(EditorStringId.InvalidValueConversion, "Invalid value conversion");
            this.AddString(EditorStringId.WaitIndicatorText, "Loading...");
            this.AddString(EditorStringId.LookUpFind, "Find");
            this.AddString(EditorStringId.LookUpSearch, "Search");
            this.AddString(EditorStringId.LookUpClose, "Close Search Panel");
            this.AddString(EditorStringId.LookUpAddNew, "Add New");
            this.AddString(EditorStringId.LookUpNext, "Next");
            this.AddString(EditorStringId.LookUpPrevious, "Previous");
            this.AddString(EditorStringId.LookUpResultInfo, "{0}/{1}");
            this.AddString(EditorStringId.LookUpShow, "Show Search Panel");
            this.AddString(EditorStringId.SparklineViewLine, "Line");
            this.AddString(EditorStringId.SparklineViewArea, "Area");
            this.AddString(EditorStringId.SparklineViewBar, "Bar");
            this.AddString(EditorStringId.SparklineViewWinLoss, "WinLoss");
            this.AddString(EditorStringId.TokenEditorNewTokenText, "New...");
            this.AddString(EditorStringId.CameraSettingsCaption, "Camera Settings");
            this.AddString(EditorStringId.CameraResolutionCaption, "Resolution:");
            this.AddString(EditorStringId.CameraBrightnessCaption, "Brightness:");
            this.AddString(EditorStringId.CameraContrastCaption, "Contrast:");
            this.AddString(EditorStringId.CameraDesaturateCaption, "Desaturate:");
            this.AddString(EditorStringId.CameraResetButtonCaption, "Reset To Default");
            this.AddString(EditorStringId.CameraDeviceCaption, "Device:");
            this.AddString(EditorStringId.CameraAgainButtonCaption, "Try Again");
            this.AddString(EditorStringId.CameraTakePictureCaption, "Take Picture");
            this.AddString(EditorStringId.CameraTakePictureToolTip, "Take Picture From Camera");
            this.AddString(EditorStringId.CameraCaptureButtonCaption, "Capture");
            this.AddString(EditorStringId.CameraErrorCaption, "The webcam is not available. Try closing other applications that might be using it.");
            this.AddString(EditorStringId.CameraRefreshButtonCaption, "Refresh");
            this.AddString(EditorStringId.CameraNoDevicesErrorCaption, "The application couldn't find a webcam.");
            this.AddString(EditorStringId.DragDropAddRecords, "Add records");
            this.AddString(EditorStringId.DragDropInsertBefore, "Insert before record:");
            this.AddString(EditorStringId.DragDropInsertAfter, "Insert after record:");
            this.AddString(EditorStringId.DragDropMoveToChildren, "Move to children collection:");
            this.AddString(EditorStringId.DragDropCannotDrop, "Cannot drop here");
            this.AddString(EditorStringId.DragDropOneRecord, "Dragging 1 record:");
            this.AddString(EditorStringId.DragDropMultipleRecords, "Dragging {0} records");
            this.AddString(EditorStringId.TimeSpanDays, "day");
            this.AddString(EditorStringId.TimeSpanDaysPlural, "days");
            this.AddString(EditorStringId.TimeSpanDaysShort, "d");
            this.AddString(EditorStringId.TimeSpanHours, "hour");
            this.AddString(EditorStringId.TimeSpanHoursPlural, "hours");
            this.AddString(EditorStringId.TimeSpanHoursShort, "h");
            this.AddString(EditorStringId.TimeSpanMinutes, "minute");
            this.AddString(EditorStringId.TimeSpanMinutesPlural, "minutes");
            this.AddString(EditorStringId.TimeSpanMinutesShort, "m");
            this.AddString(EditorStringId.TimeSpanSeconds, "second");
            this.AddString(EditorStringId.TimeSpanSecondsPlural, "seconds");
            this.AddString(EditorStringId.TimeSpanSecondsShort, "s");
            this.AddString(EditorStringId.TimeSpanFractionalSeconds, "fractional");
            this.AddString(EditorStringId.TimeSpanFractionalSecondsPlural, "fractional");
            this.AddString(EditorStringId.TimeSpanFractionalSecondsShort, "f");
            this.AddString(EditorStringId.TimeSpanMilliseconds, "millisecond");
            this.AddString(EditorStringId.TimeSpanMillisecondsPlural, "milliseconds");
            this.AddString(EditorStringId.TimeSpanMillisecondsShort, "ms");
            this.AddString(EditorStringId.ThemedWindow_Minimize, "Minimize");
            this.AddString(EditorStringId.ThemedWindow_Restore, "Restore");
            this.AddString(EditorStringId.ThemedWindow_Maximize, "Maximize");
            this.AddString(EditorStringId.ThemedWindow_Close, "Close");
            this.AddString(EditorStringId.TimePicker_ValidationErrorGreaterThan, "Value must be greater than {0:G}");
            this.AddString(EditorStringId.TimePicker_ValidationErrorLessThan, "Value must be less than {0:G}");
            this.AddString(EditorStringId.TimePicker_ValidationErrorInRange, "Value must be between {0:G} and {1:G}");
        }

        public static XtraLocalizer<EditorStringId> Active
        {
            get => 
                XtraLocalizer<EditorStringId>.Active;
            set => 
                XtraLocalizer<EditorStringId>.Active = value;
        }
    }
}

