namespace DevExpress.Office.Import.OpenXml
{
    using DevExpress.Office;
    using DevExpress.Office.Drawing;
    using System;
    using System.Collections.Generic;
    using System.Xml;

    public class PresetGeometryDestination : ElementDestination<DestinationAndXmlBasedImporter>
    {
        public static Dictionary<ShapePreset, string> shapeTypeTable = ShapeTypeTable();
        private static readonly ElementHandlerTable<DestinationAndXmlBasedImporter> handlerTable = CreateElementHandlerTable();
        private readonly ShapeProperties shapeProperties;

        public PresetGeometryDestination(DestinationAndXmlBasedImporter importer, ShapeProperties shapeProperties) : base(importer)
        {
            this.shapeProperties = shapeProperties;
        }

        private static ElementHandlerTable<DestinationAndXmlBasedImporter> CreateElementHandlerTable()
        {
            ElementHandlerTable<DestinationAndXmlBasedImporter> table = new ElementHandlerTable<DestinationAndXmlBasedImporter>();
            table.Add("avLst", new ElementHandler<DestinationAndXmlBasedImporter>(PresetGeometryDestination.OnShapeAdjust));
            return table;
        }

        private static PresetGeometryDestination GetThis(DestinationAndXmlBasedImporter importer) => 
            (PresetGeometryDestination) importer.PeekDestination();

        private static Destination OnShapeAdjust(DestinationAndXmlBasedImporter importer, XmlReader reader) => 
            new ModelShapeGuideListDestination(importer, GetThis(importer).shapeProperties.PresetAdjustList, new AdjustableCoordinateCache());

        public override void ProcessElementOpen(XmlReader reader)
        {
            this.shapeProperties.ShapeType = this.Importer.GetWpEnumValue<ShapePreset>(reader, "prst", shapeTypeTable, ShapePreset.Rect);
        }

        private static Dictionary<ShapePreset, string> ShapeTypeTable() => 
            new Dictionary<ShapePreset, string> { 
                { 
                    ShapePreset.Line,
                    "line"
                },
                { 
                    ShapePreset.LineInv,
                    "lineInv"
                },
                { 
                    ShapePreset.Triangle,
                    "triangle"
                },
                { 
                    ShapePreset.RtTriangle,
                    "rtTriangle"
                },
                { 
                    ShapePreset.Rect,
                    "rect"
                },
                { 
                    ShapePreset.Diamond,
                    "diamond"
                },
                { 
                    ShapePreset.Parallelogram,
                    "parallelogram"
                },
                { 
                    ShapePreset.Trapezoid,
                    "trapezoid"
                },
                { 
                    ShapePreset.NonIsoscelesTrapezoid,
                    "nonIsoscelesTrapezoid"
                },
                { 
                    ShapePreset.Pentagon,
                    "pentagon"
                },
                { 
                    ShapePreset.Hexagon,
                    "hexagon"
                },
                { 
                    ShapePreset.Heptagon,
                    "heptagon"
                },
                { 
                    ShapePreset.Octagon,
                    "octagon"
                },
                { 
                    ShapePreset.Decagon,
                    "decagon"
                },
                { 
                    ShapePreset.Dodecagon,
                    "dodecagon"
                },
                { 
                    ShapePreset.Star4,
                    "star4"
                },
                { 
                    ShapePreset.Star5,
                    "star5"
                },
                { 
                    ShapePreset.Star6,
                    "star6"
                },
                { 
                    ShapePreset.Star7,
                    "star7"
                },
                { 
                    ShapePreset.Star8,
                    "star8"
                },
                { 
                    ShapePreset.Star10,
                    "star10"
                },
                { 
                    ShapePreset.Star12,
                    "star12"
                },
                { 
                    ShapePreset.Star16,
                    "star16"
                },
                { 
                    ShapePreset.Star24,
                    "star24"
                },
                { 
                    ShapePreset.Star32,
                    "star32"
                },
                { 
                    ShapePreset.RoundRect,
                    "roundRect"
                },
                { 
                    ShapePreset.Round1Rect,
                    "round1Rect"
                },
                { 
                    ShapePreset.Round2SameRect,
                    "round2SameRect"
                },
                { 
                    ShapePreset.Round2DiagRect,
                    "round2DiagRect"
                },
                { 
                    ShapePreset.SnipRoundRect,
                    "snipRoundRect"
                },
                { 
                    ShapePreset.Snip1Rect,
                    "snip1Rect"
                },
                { 
                    ShapePreset.Snip2SameRect,
                    "snip2SameRect"
                },
                { 
                    ShapePreset.Snip2DiagRect,
                    "snip2DiagRect"
                },
                { 
                    ShapePreset.Plaque,
                    "plaque"
                },
                { 
                    ShapePreset.Ellipse,
                    "ellipse"
                },
                { 
                    ShapePreset.Teardrop,
                    "teardrop"
                },
                { 
                    ShapePreset.HomePlate,
                    "homePlate"
                },
                { 
                    ShapePreset.Chevron,
                    "chevron"
                },
                { 
                    ShapePreset.PieWedge,
                    "pieWedge"
                },
                { 
                    ShapePreset.Pie,
                    "pie"
                },
                { 
                    ShapePreset.BlockArc,
                    "blockArc"
                },
                { 
                    ShapePreset.Donut,
                    "donut"
                },
                { 
                    ShapePreset.NoSmoking,
                    "noSmoking"
                },
                { 
                    ShapePreset.RightArrow,
                    "rightArrow"
                },
                { 
                    ShapePreset.LeftArrow,
                    "leftArrow"
                },
                { 
                    ShapePreset.UpArrow,
                    "upArrow"
                },
                { 
                    ShapePreset.DownArrow,
                    "downArrow"
                },
                { 
                    ShapePreset.StripedRightArrow,
                    "stripedRightArrow"
                },
                { 
                    ShapePreset.NotchedRightArrow,
                    "notchedRightArrow"
                },
                { 
                    ShapePreset.BentUpArrow,
                    "bentUpArrow"
                },
                { 
                    ShapePreset.LeftRightArrow,
                    "leftRightArrow"
                },
                { 
                    ShapePreset.UpDownArrow,
                    "upDownArrow"
                },
                { 
                    ShapePreset.LeftUpArrow,
                    "leftUpArrow"
                },
                { 
                    ShapePreset.LeftRightUpArrow,
                    "leftRightUpArrow"
                },
                { 
                    ShapePreset.QuadArrow,
                    "quadArrow"
                },
                { 
                    ShapePreset.LeftArrowCallout,
                    "leftArrowCallout"
                },
                { 
                    ShapePreset.RightArrowCallout,
                    "rightArrowCallout"
                },
                { 
                    ShapePreset.UpArrowCallout,
                    "upArrowCallout"
                },
                { 
                    ShapePreset.DownArrowCallout,
                    "downArrowCallout"
                },
                { 
                    ShapePreset.LeftRightArrowCallout,
                    "leftRightArrowCallout"
                },
                { 
                    ShapePreset.UpDownArrowCallout,
                    "upDownArrowCallout"
                },
                { 
                    ShapePreset.QuadArrowCallout,
                    "quadArrowCallout"
                },
                { 
                    ShapePreset.BentArrow,
                    "bentArrow"
                },
                { 
                    ShapePreset.UturnArrow,
                    "uturnArrow"
                },
                { 
                    ShapePreset.CircularArrow,
                    "circularArrow"
                },
                { 
                    ShapePreset.LeftCircularArrow,
                    "leftCircularArrow"
                },
                { 
                    ShapePreset.LeftRightCircularArrow,
                    "leftRightCircularArrow"
                },
                { 
                    ShapePreset.CurvedRightArrow,
                    "curvedRightArrow"
                },
                { 
                    ShapePreset.CurvedLeftArrow,
                    "curvedLeftArrow"
                },
                { 
                    ShapePreset.CurvedUpArrow,
                    "curvedUpArrow"
                },
                { 
                    ShapePreset.CurvedDownArrow,
                    "curvedDownArrow"
                },
                { 
                    ShapePreset.SwooshArrow,
                    "swooshArrow"
                },
                { 
                    ShapePreset.Cube,
                    "cube"
                },
                { 
                    ShapePreset.Can,
                    "can"
                },
                { 
                    ShapePreset.LightningBolt,
                    "lightningBolt"
                },
                { 
                    ShapePreset.Heart,
                    "heart"
                },
                { 
                    ShapePreset.Sun,
                    "sun"
                },
                { 
                    ShapePreset.Moon,
                    "moon"
                },
                { 
                    ShapePreset.SmileyFace,
                    "smileyFace"
                },
                { 
                    ShapePreset.IrregularSeal1,
                    "irregularSeal1"
                },
                { 
                    ShapePreset.IrregularSeal2,
                    "irregularSeal2"
                },
                { 
                    ShapePreset.FoldedCorner,
                    "foldedCorner"
                },
                { 
                    ShapePreset.Bevel,
                    "bevel"
                },
                { 
                    ShapePreset.Frame,
                    "frame"
                },
                { 
                    ShapePreset.HalfFrame,
                    "halfFrame"
                },
                { 
                    ShapePreset.Corner,
                    "corner"
                },
                { 
                    ShapePreset.DiagStripe,
                    "diagStripe"
                },
                { 
                    ShapePreset.Chord,
                    "chord"
                },
                { 
                    ShapePreset.Arc,
                    "arc"
                },
                { 
                    ShapePreset.LeftBracket,
                    "leftBracket"
                },
                { 
                    ShapePreset.RightBracket,
                    "rightBracket"
                },
                { 
                    ShapePreset.LeftBrace,
                    "leftBrace"
                },
                { 
                    ShapePreset.RightBrace,
                    "rightBrace"
                },
                { 
                    ShapePreset.BracketPair,
                    "bracketPair"
                },
                { 
                    ShapePreset.BracePair,
                    "bracePair"
                },
                { 
                    ShapePreset.StraightConnector1,
                    "straightConnector1"
                },
                { 
                    ShapePreset.BentConnector2,
                    "bentConnector2"
                },
                { 
                    ShapePreset.BentConnector3,
                    "bentConnector3"
                },
                { 
                    ShapePreset.BentConnector4,
                    "bentConnector4"
                },
                { 
                    ShapePreset.BentConnector5,
                    "bentConnector5"
                },
                { 
                    ShapePreset.CurvedConnector2,
                    "curvedConnector2"
                },
                { 
                    ShapePreset.CurvedConnector3,
                    "curvedConnector3"
                },
                { 
                    ShapePreset.CurvedConnector4,
                    "curvedConnector4"
                },
                { 
                    ShapePreset.CurvedConnector5,
                    "curvedConnector5"
                },
                { 
                    ShapePreset.Callout1,
                    "callout1"
                },
                { 
                    ShapePreset.Callout2,
                    "callout2"
                },
                { 
                    ShapePreset.Callout3,
                    "callout3"
                },
                { 
                    ShapePreset.AccentCallout1,
                    "accentCallout1"
                },
                { 
                    ShapePreset.AccentCallout2,
                    "accentCallout2"
                },
                { 
                    ShapePreset.AccentCallout3,
                    "accentCallout3"
                },
                { 
                    ShapePreset.BorderCallout1,
                    "borderCallout1"
                },
                { 
                    ShapePreset.BorderCallout2,
                    "borderCallout2"
                },
                { 
                    ShapePreset.BorderCallout3,
                    "borderCallout3"
                },
                { 
                    ShapePreset.AccentBorderCallout1,
                    "accentBorderCallout1"
                },
                { 
                    ShapePreset.AccentBorderCallout2,
                    "accentBorderCallout2"
                },
                { 
                    ShapePreset.AccentBorderCallout3,
                    "accentBorderCallout3"
                },
                { 
                    ShapePreset.WedgeRectCallout,
                    "wedgeRectCallout"
                },
                { 
                    ShapePreset.WedgeRoundRectCallout,
                    "wedgeRoundRectCallout"
                },
                { 
                    ShapePreset.WedgeEllipseCallout,
                    "wedgeEllipseCallout"
                },
                { 
                    ShapePreset.CloudCallout,
                    "cloudCallout"
                },
                { 
                    ShapePreset.Cloud,
                    "cloud"
                },
                { 
                    ShapePreset.Ribbon,
                    "ribbon"
                },
                { 
                    ShapePreset.Ribbon2,
                    "ribbon2"
                },
                { 
                    ShapePreset.EllipseRibbon,
                    "ellipseRibbon"
                },
                { 
                    ShapePreset.EllipseRibbon2,
                    "ellipseRibbon2"
                },
                { 
                    ShapePreset.LeftRightRibbon,
                    "leftRightRibbon"
                },
                { 
                    ShapePreset.VerticalScroll,
                    "verticalScroll"
                },
                { 
                    ShapePreset.HorizontalScroll,
                    "horizontalScroll"
                },
                { 
                    ShapePreset.Wave,
                    "wave"
                },
                { 
                    ShapePreset.DoubleWave,
                    "doubleWave"
                },
                { 
                    ShapePreset.Plus,
                    "plus"
                },
                { 
                    ShapePreset.FlowChartProcess,
                    "flowChartProcess"
                },
                { 
                    ShapePreset.FlowChartDecision,
                    "flowChartDecision"
                },
                { 
                    ShapePreset.FlowChartInputOutput,
                    "flowChartInputOutput"
                },
                { 
                    ShapePreset.FlowChartPredefinedProcess,
                    "flowChartPredefinedProcess"
                },
                { 
                    ShapePreset.FlowChartInternalStorage,
                    "flowChartInternalStorage"
                },
                { 
                    ShapePreset.FlowChartDocument,
                    "flowChartDocument"
                },
                { 
                    ShapePreset.FlowChartMultidocument,
                    "flowChartMultidocument"
                },
                { 
                    ShapePreset.FlowChartTerminator,
                    "flowChartTerminator"
                },
                { 
                    ShapePreset.FlowChartPreparation,
                    "flowChartPreparation"
                },
                { 
                    ShapePreset.FlowChartManualInput,
                    "flowChartManualInput"
                },
                { 
                    ShapePreset.FlowChartManualOperation,
                    "flowChartManualOperation"
                },
                { 
                    ShapePreset.FlowChartConnector,
                    "flowChartConnector"
                },
                { 
                    ShapePreset.FlowChartPunchedCard,
                    "flowChartPunchedCard"
                },
                { 
                    ShapePreset.FlowChartPunchedTape,
                    "flowChartPunchedTape"
                },
                { 
                    ShapePreset.FlowChartSummingJunction,
                    "flowChartSummingJunction"
                },
                { 
                    ShapePreset.FlowChartOr,
                    "flowChartOr"
                },
                { 
                    ShapePreset.FlowChartCollate,
                    "flowChartCollate"
                },
                { 
                    ShapePreset.FlowChartSort,
                    "flowChartSort"
                },
                { 
                    ShapePreset.FlowChartExtract,
                    "flowChartExtract"
                },
                { 
                    ShapePreset.FlowChartMerge,
                    "flowChartMerge"
                },
                { 
                    ShapePreset.FlowChartOfflineStorage,
                    "flowChartOfflineStorage"
                },
                { 
                    ShapePreset.FlowChartOnlineStorage,
                    "flowChartOnlineStorage"
                },
                { 
                    ShapePreset.FlowChartMagneticTape,
                    "flowChartMagneticTape"
                },
                { 
                    ShapePreset.FlowChartMagneticDisk,
                    "flowChartMagneticDisk"
                },
                { 
                    ShapePreset.FlowChartMagneticDrum,
                    "flowChartMagneticDrum"
                },
                { 
                    ShapePreset.FlowChartDisplay,
                    "flowChartDisplay"
                },
                { 
                    ShapePreset.FlowChartDelay,
                    "flowChartDelay"
                },
                { 
                    ShapePreset.FlowChartAlternateProcess,
                    "flowChartAlternateProcess"
                },
                { 
                    ShapePreset.FlowChartOffpageConnector,
                    "flowChartOffpageConnector"
                },
                { 
                    ShapePreset.ActionButtonBlank,
                    "actionButtonBlank"
                },
                { 
                    ShapePreset.ActionButtonHome,
                    "actionButtonHome"
                },
                { 
                    ShapePreset.ActionButtonHelp,
                    "actionButtonHelp"
                },
                { 
                    ShapePreset.ActionButtonInformation,
                    "actionButtonInformation"
                },
                { 
                    ShapePreset.ActionButtonForwardNext,
                    "actionButtonForwardNext"
                },
                { 
                    ShapePreset.ActionButtonBackPrevious,
                    "actionButtonBackPrevious"
                },
                { 
                    ShapePreset.ActionButtonEnd,
                    "actionButtonEnd"
                },
                { 
                    ShapePreset.ActionButtonBeginning,
                    "actionButtonBeginning"
                },
                { 
                    ShapePreset.ActionButtonReturn,
                    "actionButtonReturn"
                },
                { 
                    ShapePreset.ActionButtonDocument,
                    "actionButtonDocument"
                },
                { 
                    ShapePreset.ActionButtonSound,
                    "actionButtonSound"
                },
                { 
                    ShapePreset.ActionButtonMovie,
                    "actionButtonMovie"
                },
                { 
                    ShapePreset.Gear6,
                    "gear6"
                },
                { 
                    ShapePreset.Gear9,
                    "gear9"
                },
                { 
                    ShapePreset.Funnel,
                    "funnel"
                },
                { 
                    ShapePreset.MathPlus,
                    "mathPlus"
                },
                { 
                    ShapePreset.MathMinus,
                    "mathMinus"
                },
                { 
                    ShapePreset.MathMultiply,
                    "mathMultiply"
                },
                { 
                    ShapePreset.MathDivide,
                    "mathDivide"
                },
                { 
                    ShapePreset.MathEqual,
                    "mathEqual"
                },
                { 
                    ShapePreset.MathNotEqual,
                    "mathNotEqual"
                },
                { 
                    ShapePreset.CornerTabs,
                    "cornerTabs"
                },
                { 
                    ShapePreset.SquareTabs,
                    "squareTabs"
                },
                { 
                    ShapePreset.PlaqueTabs,
                    "plaqueTabs"
                },
                { 
                    ShapePreset.ChartX,
                    "chartX"
                },
                { 
                    ShapePreset.ChartStar,
                    "chartStar"
                },
                { 
                    ShapePreset.ChartPlus,
                    "chartPlus"
                }
            };

        protected override ElementHandlerTable<DestinationAndXmlBasedImporter> ElementHandlerTable =>
            handlerTable;
    }
}

