namespace DevExpress.Internal
{
    using System;

    internal static class AssemblyInfo
    {
        public const string AssemblyCopyright = "Copyright \x00a9 2000-2020 Developer Express Inc.";
        public const string AssemblyCompany = "Developer Express Inc.";
        public const int VersionId = 0xc0;
        public const int VersionIdMinor = 0x4b09;
        public const string VersionShort = "19.2";
        public const string Version = "19.2.9.0";
        public const string FileVersion = "19.2.9.0";
        public const string MarketingVersion = "v2019 vol 2";
        public const string VirtDirSuffix = "_v19_2";
        public const string PublicKeyToken = "b88d1754d700e49a";
        public const string PublicKey = "0024000004800000940000000602000000240000525341310004000001000100dfcd8cadc2dd24a7cd4ce95c4a9c1b8e7cb1dc2d665120556b4b0ec35495fddb2bd6eed0ca1e56480276295a225ba2a9746f3d3e1a04547ccf5b26acc3f96eb2a13ac467512497aa79208e32f242fd0618014d53c95a36e5de0e891873841fa8f559566e38e968426488b4aa4d0f0b59e59f38dcf3fbccf25d990ab19c27ddc2";
        public const string FullAssemblyVersionExtension = ", Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string TestsSuffix = ".Tests";
        public const string DesignSuffix = ".Design";
        public const string SatelliteContractVersion = "19.2.0.0";
        public const string VSuffixWithoutSeparator = "v19.2";
        public const string VSuffix = ".v19.2";
        public const string VSuffixDesign = ".v19.2.Design";
        public const string VSuffixExport = ".v19.2.Export";
        public const string VSuffixLinq = ".v19.2.Linq";
        public const string SRAssemblyAgScheduler = "DevExpress.Xpf.Scheduler.v19.2";
        public const string SRAssemblyAssemblyLoader = "DevExpress.Xpf.AssemblyLoader.v19.2";
        public const string SRAssemblyXpfSpellChecker = "DevExpress.Xpf.SpellChecker.v19.2";
        public const string SRAssemblyXpfRichEdit = "DevExpress.Xpf.RichEdit.v19.2";
        public const string SRAssemblyXpfSpreadsheet = "DevExpress.Xpf.Spreadsheet.v19.2";
        public const string SRAssemblyXpfScheduler = "DevExpress.Xpf.Scheduler.v19.2";
        public const string SRAssemblyXpfScheduling = "DevExpress.Xpf.Scheduling.v19.2";
        public const string SRAssemblyXpfSchedulingReportDesigner = "DevExpress.Xpf.Scheduling.ReportDesigner.v19.2";
        public const string SRAssemblyXpfSchedulingDesign = "DevExpress.Xpf.Scheduling.v19.2.Design";
        public const string SRAssemblyXpfRichEditExtensions = "DevExpress.Xpf.RichEdit.v19.2.Extensions";
        public const string SRAssemblyXpfPrinting = "DevExpress.Xpf.Printing.v19.2";
        public const string SRAssemblyXpfPrintingFull = "DevExpress.Xpf.Printing.v19.2, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblyXpfDataAccess = "DevExpress.Xpf.DataAccess.v19.2";
        public const string SRAssemblyXpfExpressionEditor = "DevExpress.Xpf.ExpressionEditor.v19.2";
        public const string SRAssemblyXpfReportDesigner = "DevExpress.Xpf.ReportDesigner.v19.2";
        public const string SRAssemblyXpfCore = "DevExpress.Xpf.Core.v19.2";
        public const string SRAssemblyXpfPdfViewer = "DevExpress.Xpf.PdfViewer.v19.2";
        public const string SRAssemblyXpfDocumentViewerCore = "DevExpress.Xpf.DocumentViewer.v19.2.Core";
        public const string SRAssemblyXpfMvvm = "DevExpress.Mvvm.v19.2";
        public const string SRAssemblyXpfMvvmFree = "DevExpress.Mvvm";
        public const string SRAssemblyXpfMvvmUIFree = "DevExpress.Mvvm.UI";
        public const string SRAssemblyXpfRibbon = "DevExpress.Xpf.Ribbon.v19.2";
        public const string SRAssemblyXpfNavBar = "DevExpress.Xpf.NavBar.v19.2";
        public const string SRAssemblyXpfCoreExtensions = "DevExpress.Xpf.Core.v19.2.Extensions";
        public const string SRAssemblyXpfDemoBase = "DevExpress.Xpf.DemoBase.v19.2";
        public const string SRAssemblyXpfGrid = "DevExpress.Xpf.Grid.v19.2";
        public const string SRAssemblyXpfGridCore = "DevExpress.Xpf.Grid.v19.2.Core";
        public const string SRAssemblyXpfGridExtensions = "DevExpress.Xpf.Grid.v19.2.Extensions";
        public const string SRAssemblyXpfPivotGrid = "DevExpress.Xpf.PivotGrid.v19.2";
        public const string SRAssemblyXpfPivotGridTests = "DevExpress.Xpf.PivotGrid.v19.2.Tests";
        public const string SRAssemblyXpfDiagram = "DevExpress.Xpf.Diagram.v19.2";
        public const string SRAssemblyXpfDiagramTests = "DevExpress.Xpf.Diagram.v19.2.Tests";
        public const string SRAssemblyXpfGantt = "DevExpress.Xpf.Gantt.v19.2";
        public const string SRAssemblyXpfGanttTests = "DevExpress.Xpf.Gantt.v19.2.Tests";
        public const string SRAssemblyXpfDialogs = "DevExpress.Xpf.Dialogs.v19.2";
        public const string SRAssemblyXpfDialogsTests = "DevExpress.Xpf.Dialogs.v19.2.Tests";
        public const string SRAssemblyXpfAccordion = "DevExpress.Xpf.Accordion.v19.2";
        public const string SRAssemblyXpfAccordionTests = "DevExpress.Xpf.Accordion.v19.2.Tests";
        public const string SRAssemblyXpfAccordionDesign = "DevExpress.Xpf.Accordion.v19.2.Design";
        public const string SRAssemblyXpfDocking = "DevExpress.Xpf.Docking.v19.2";
        public const string SRAssemblyXpfControls = "DevExpress.Xpf.Controls.v19.2";
        public const string SRAssemblyXpfLayoutControl = "DevExpress.Xpf.LayoutControl.v19.2";
        public const string SRAssemblyImages = "DevExpress.Images.v19.2";
        public const string SRAssemblyImagesFull = "DevExpress.Images.v19.2, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblyMvvm = "DevExpress.Mvvm.v19.2";
        public const string SRAssemblyMvvmFull = "DevExpress.Mvvm.v19.2, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblyXpfDockingExtensions = "DevExpress.Xpf.Docking.v19.2.Extensions";
        public const string SRAssemblyXpfLayoutCore = "DevExpress.Xpf.Layout.v19.2.Core";
        public const string SRAssemblyDXCharts = "DevExpress.Xpf.Charts.v19.2";
        public const string SRAssemblyChartDesigner = "DevExpress.Charts.Designer.v19.2";
        public const string SRAssemblyDXGauges = "DevExpress.Xpf.Gauges.v19.2";
        public const string SRAssemblyDXMap = "DevExpress.Xpf.Map.v19.2";
        public const string SRAssemblyDXMapTests = "DevExpress.Xpf.Map.Tests";
        public const string SRAssemblyDXTreeMap = "DevExpress.Xpf.TreeMap.v19.2";
        public const string SRAssemblyData = "DevExpress.Data.v19.2";
        public const string SRAssemblyDemoData = "DevExpress.DemoData.v19.2";
        public const string SRAssemblyPrintingCore = "DevExpress.Printing.v19.2.Core";
        public const string SRAssemblyRichEditCore = "DevExpress.RichEdit.v19.2.Core";
        public const string SRAssemblyOfficeCore = "DevExpress.Office.v19.2.Core";
        public const string SRAssemblyDocs = "DevExpress.Docs.v19.2";
        public const string SRAssemblySpreadsheetCore = "DevExpress.Spreadsheet.v19.2.Core";
        public const string SRAssemblySchedulerCore = "DevExpress.XtraScheduler.v19.2.Core";
        public const string SRAssemblyPrintingDesign = "DevExpress.XtraPrinting.v19.2.Design";
        public const string SRAssemblyPrintingDesignFull = "DevExpress.XtraPrinting.v19.2.Design, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblyRichEditLayoutEngine = "DevExpress.RichEdit.LayoutEngine.v19.2";
        public const string SRAssemblyRichEditLayoutEngineTests = "DevExpress.RichEdit.LayoutEngine.v19.2.Tests";
        public const string SRDocumentationLink = "http://documentation.devexpress.com/";
        public const string InstallationRegistryKeyBase = @"SOFTWARE\DevExpress\Components\";
        public const string InstallationRegistryKey = @"SOFTWARE\DevExpress\Components\v19.2";
        public const string InstallationRegistryRootPathValueName = "RootDirectory";
        public const string SRAssemblyXpfPrefix = "DevExpress.Xpf";
        public const string ThemePrefixWithoutSeparator = "Themes";
        public const string ThemePrefix = ".Themes.";
        public const string UINamespace = "DevExpress.UI.Xaml.";
        public const string SRAssemblyCoreUwp = "DevExpress.Core";
        public const string SRAssemblyCoreUwpTests = "DevExpress.Core.Tests";
        public const string SRAssemblyCoreUwpDesign = "DevExpress.Core.Design";
        public const string SRAssemblyPdfCoreUwp = "DevExpress.Pdf.Core";
        public const string SRAssemblyPdfCoreUwpTests = "DevExpress.Pdf.Core.Tests";
        public const string SRAssemblyDrawingUwp = "DevExpress.Drawing";
        public const string SRAssemblyDrawingUwpTests = "DevExpress.Drawing.Tests";
        public const string SRAssemblyUIUwp = "DevExpress.UI.Xaml";
        public const string SRAssemblyUIUwpTests = "DevExpress.UI.Xaml.Tests";
        public const string SRAssemblyUIUwpDesign = "DevExpress.UI.Xaml.Design";
        public const string SRAssemblyEditorsUwp = "DevExpress.UI.Xaml.Editors";
        public const string SRAssemblyEditorsUwpTests = "DevExpress.UI.Xaml.Editors.Tests";
        public const string SRAssemblyEditorsUwpDesign = "DevExpress.UI.Xaml.Editors.Design";
        public const string SRAssemblyLayoutUwp = "DevExpress.UI.Xaml.Layout";
        public const string SRAssemblyLayoutUwpTests = "DevExpress.UI.Xaml.Layout.Tests";
        public const string SRAssemblyLayoutUwpDesign = "DevExpress.UI.Xaml.Layout.Design";
        public const string SRAssemblyGridUwp = "DevExpress.UI.Xaml.Grid";
        public const string SRAssemblyGridUwpTests = "DevExpress.UI.Xaml.Grid.Tests";
        public const string SRAssemblyGridUwpDesign = "DevExpress.UI.Xaml.Grid.Design";
        public const string SRAssemblyControlsUwp = "DevExpress.UI.Xaml.Controls";
        public const string SRAssemblyControlsUwpTests = "DevExpress.UI.Xaml.Controls.Tests";
        public const string SRAssemblyControlsUwpDesign = "DevExpress.UI.Xaml.Controls.Design";
        public const string SRAssemblyChartsUwp = "DevExpress.UI.Xaml.Charts";
        public const string SRAssemblyChartsUwpTests = "DevExpress.UI.Xaml.Charts.Tests";
        public const string SRAssemblyChartsUwpDesign = "DevExpress.UI.Xaml.Charts.Design";
        public const string SRAssemblyGaugesUwp = "DevExpress.UI.Xaml.Gauges";
        public const string SRAssemblyGaugesUwpTests = "DevExpress.UI.Xaml.Gauges.Tests";
        public const string SRAssemblyGaugesUwpDesign = "DevExpress.UI.Xaml.Gauges.Design";
        public const string SRAssemblyMapUwp = "DevExpress.UI.Xaml.Map";
        public const string SRAssemblyMapUwpTests = "DevExpress.UI.Xaml.Map.Tests";
        public const string SRAssemblyMapUwpDesign = "DevExpress.UI.Xaml.Map.Design";
        public const string SRAssemblyRibbonUwp = "DevExpress.UI.Xaml.Ribbon";
        public const string SRAssemblyRibbonUwpTests = "DevExpress.UI.Xaml.Ribbon.Tests";
        public const string SRAssemblyRibbonUwpDesign = "DevExpress.UI.Xaml.Ribbon.Design";
        public const string SRAssemblyColorSchemeManagerUwp = "DevExpress.ColorSchemeManager";
        public const string SRAssemblyColorSchemeManagerUwpTests = "DevExpress.Core.Tests";
        public const string SRAssemblyThemesUwp = "DevExpress.Themes";
        public const string SRAssemblyThemesUwpTests = "DevExpress.Themes.Tests";
        public const string SRAssemblySchedulerUwp = "DevExpress.UI.Xaml.Scheduler";
        public const string SRAssemblySchedulerUwpTests = "DevExpress.UI.Xaml.Scheduler.Tests";
        public const string SRAssemblySchedulerUwpDesign = "DevExpress.UI.Xaml.Scheduler.Design";
        public const string SRAssemblyAspNetCore = "DevExpress.AspNetCore.Core.v19.2";
        public const string SRAssemblyAspNetCoreBootstrap = "DevExpress.AspNetCore.Bootstrap.Render.v19.2";
        public const string SRAssemblyAspNetCoreSchedulerCore = "DevExpress.AspNetCore.Scheduler.Core.v19.2";
        public const string SRAssemblyAspNetCoreBootstrapMvc = "DevExpress.AspNetCore.Bootstrap.v19.2";
        public const string SRAssemblyAspNetCoreResources = "DevExpress.AspNetCore.Resources.v19.2";
        public const string SRAssemblyAspNetCoreCommon = "DevExpress.AspNetCore.Common.v19.2";
        public const string SRAssemblyAspNetCoreTests = "DevExpress.AspNetCore.Core.Tests";
        public const string SRAssemblyAspNetCoreBootstrapMvcTests = "DevExpress.AspNetCore.Bootstrap.Tests";
        public const string SRAssemblyAspNetCoreSpreadsheet = "DevExpress.AspNetCore.Spreadsheet.v19.2";
        public const string SRAssemblyAspNetCoreSpreadsheetTest = "DevExpress.AspNetCore.Spreadsheet.v19.2.Tests";
        public const string SRAssemblyMVC = "DevExpress.Web.Mvc.v19.2";
        public const string SRAssemblyMVC5 = "DevExpress.Web.Mvc5.v19.2";
        public const string SRAssemblyMVCTests = "DevExpress.Web.Mvc.v19.2.Tests";
        public const string SRAssemblyBootstrap = "DevExpress.Web.Bootstrap.v19.2";
        public const string SRAssemblyBootstrapDesign = "DevExpress.Web.Bootstrap.v19.2.Design";
        public const string SRAssemblyBootstrapDesignFull = "DevExpress.Web.Bootstrap.v19.2.Design, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblyBootstrapTests = "DevExpress.Web.Bootstrap.v19.2.Tests";
        public const string SRAssemblyExpressAppWeb = "DevExpress.ExpressApp.Web.v19.2";
        public const string SRAssemblyExpressAppNotificationsWeb = "DevExpress.ExpressApp.Notifications.Web.v19.2";
        public const string SRAssemblyExpressAppMapsWeb = "DevExpress.ExpressApp.Maps.Web.v19.2";
        public const string SRAssemblyASPxThemes = "DevExpress.Web.ASPxThemes.v19.2";
        public const string SRAssemblyASPxThemesFull = "DevExpress.Web.ASPxThemes.v19.2, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblyASPxThemesTests = "DevExpress.Web.ASPxThemes.v19.2.Tests";
        public const string SRAssemblyASPxResources = "DevExpress.Web.Resources.v19.2";
        public const string SRAssemblyASPxGridView = "DevExpress.Web.ASPxGridView.v19.2";
        public const string SRAssemblyASPxPivotGrid = "DevExpress.Web.ASPxPivotGrid.v19.2";
        public const string SRAssemblyASPxPivotGridExport = "DevExpress.Web.ASPxPivotGrid.v19.2.Export";
        public const string SRAssemblyASPxPivotGridTests = "DevExpress.Web.ASPxPivotGrid.v19.2.Tests";
        public const string SRAssemblyBonusSkins = "DevExpress.BonusSkins.v19.2";
        public const string SRAssemblyBonusSkinsFull = "DevExpress.BonusSkins.v19.2, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblyDesign = "DevExpress.Design.v19.2";
        public const string SRAssemblyDesignFull = "DevExpress.Design.v19.2, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblyDataLinq = "DevExpress.Data.v19.2.Linq";
        public const string SRAssemblyUtils = "DevExpress.Utils.v19.2";
        public const string SRAssemblyUtilsFull = "DevExpress.Utils.v19.2, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblyParser = "DevExpress.Parser.v19.2";
        public const string SRAssemblyPrinting = "DevExpress.XtraPrinting.v19.2";
        public const string SRAssemblyPrintingFull = "DevExpress.XtraPrinting.v19.2, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblyEditors = "DevExpress.XtraEditors.v19.2";
        public const string SRAssemblyEditorsFull = "DevExpress.XtraEditors.v19.2, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblyEditorsDesign = "DevExpress.XtraEditors.v19.2.Design";
        public const string SRAssemblyEditorsDesignFull = "DevExpress.XtraEditors.v19.2.Design, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblyDiagramCore = "DevExpress.Diagram.v19.2.Core";
        public const string SRAssemblyDiagramCoreTests = "DevExpress.Diagram.v19.2.Core.Tests";
        public const string SRAssemblyDiagram = "DevExpress.XtraDiagram.v19.2";
        public const string SRAssemblyDiagramTests = "DevExpress.XtraDiagram.v19.2.Tests";
        public const string SRAssemblyDiagramDesign = "DevExpress.XtraDiagram.v19.2.Design";
        public const string SRAssemblyDiagramDesignFull = "DevExpress.XtraDiagram.v19.2.Design, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblyGanttCore = "DevExpress.Gantt.v19.2.Core";
        public const string SRAssemblyGanttCoreTests = "DevExpress.Gantt.v19.2.Core.Tests";
        public const string SRAssemblyGantt = "DevExpress.XtraGantt.v19.2";
        public const string SRAssemblyGanttDesign = "DevExpress.XtraGantt.v19.2.Design";
        public const string SRAssemblyGanttDesignFull = "DevExpress.XtraGantt.v19.2.Design, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblyDialogsCore = "DevExpress.Dialogs.v19.2.Core";
        public const string SRAssemblyDialogsCoreTests = "DevExpress.Dialogs.v19.2.Core.Tests";
        public const string SRAssemblyDialogs = "DevExpress.XtraDialogs.v19.2";
        public const string SRAssemblyDialogsTests = "DevExpress.XtraDialogs.v19.2.Tests";
        public const string SRAssemblyNavBar = "DevExpress.XtraNavBar.v19.2";
        public const string SRAssemblyNavBarDesign = "DevExpress.XtraNavBar.v19.2.Design";
        public const string SRAssemblyBars = "DevExpress.XtraBars.v19.2";
        public const string SRAssemblyBarsDesign = "DevExpress.XtraBars.v19.2.Design";
        public const string SRAssemblyBarsDesignFull = "DevExpress.XtraBars.v19.2.Design, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblyGrid = "DevExpress.XtraGrid.v19.2";
        public const string SRAssemblyGaugesCore = "DevExpress.XtraGauges.v19.2.Core";
        public const string SRAssemblyGaugesPresets = "DevExpress.XtraGauges.v19.2.Presets";
        public const string SRAssemblyGaugesWin = "DevExpress.XtraGauges.v19.2.Win";
        public const string SRAssemblyASPxGauges = "DevExpress.Web.ASPxGauges.v19.2";
        public const string SRAssemblyASPxGaugesTests = "DevExpress.Web.ASPxGauges.v19.2.Tests";
        public const string SRAssemblyGaugesDesignWin = "DevExpress.XtraGauges.v19.2.Design.Win";
        public const string SRAssemblyGridDesign = "DevExpress.XtraGrid.v19.2.Design";
        public const string SRAssemblyGridDesignFull = "DevExpress.XtraGrid.v19.2.Design, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblyPivotGrid = "DevExpress.XtraPivotGrid.v19.2";
        public const string SRAssemblyPivotGridFull = "DevExpress.XtraPivotGrid.v19.2, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblyPivotGridCore = "DevExpress.PivotGrid.v19.2.Core";
        public const string SRAssemblyPivotGridDesign = "DevExpress.XtraPivotGrid.v19.2.Design";
        public const string SRAssemblyPivotGridDesignFull = "DevExpress.XtraPivotGrid.v19.2.Design, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblyTreeList = "DevExpress.XtraTreeList.v19.2";
        public const string SRAssemblyTreeListDesign = "DevExpress.XtraTreeList.v19.2.Design";
        public const string SRAssemblyTreeListDesignFull = "DevExpress.XtraTreeList.v19.2.Design, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblyVertGrid = "DevExpress.XtraVerticalGrid.v19.2";
        public const string SRAssemblyVertGridDesign = "DevExpress.XtraVerticalGrid.v19.2.Design";
        public const string SRAssemblyVertGridDesignFull = "DevExpress.XtraVerticalGrid.v19.2.Design, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblyReports = "DevExpress.XtraReports.v19.2";
        public const string SRAssemblyReportsFull = "DevExpress.XtraReports.v19.2, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblyReportsTests = "DevExpress.XtraReports.Tests";
        public const string SRAssemblyReportsService = "DevExpress.XtraReports.v19.2.Service";
        public const string SRAssemblyReportsDesign = "DevExpress.XtraReports.v19.2.Design";
        public const string SRAssemblyReportsDesignFull = "DevExpress.XtraReports.v19.2.Design, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblyReportsImport = "DevExpress.XtraReports.v19.2.Import";
        public const string SRAssemblyReportsWeb = "DevExpress.XtraReports.v19.2.Web";
        public const string SRAssemblyReportsWebForms = "DevExpress.XtraReports.v19.2.Web.WebForms";
        public const string SRAssemblyReportsWebTests = "DevExpress.XtraReports.v19.2.Web.Tests";
        public const string SRAssemblyReportsAspNetCore = "DevExpress.AspNetCore.Reporting.v19.2";
        public const string SRAssemblyReportsAspNetCoreTests = "DevExpress.AspNetCore.Reporting.v19.2.Tests";
        public const string SRAssemblyReportsAspNetCore3Tests = "DevExpress.AspNetCore3.Reporting.v19.2.Tests";
        public const string SRAssemblyReportsExtensions = "DevExpress.XtraReports.v19.2.Extensions";
        public const string SRAssemblyReportsExtensionsFull = "DevExpress.XtraReports.v19.2.Extensions, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblyReportsExtensionsTests = "DevExpress.XtraReports.Extensions.Tests";
        public const string SRAssemblyReportsNReportTest = "NReportTest.v19.2";
        public const string SRAssemblyReportServerDesigner = "DevExpress.ReportDesigner.v19.2.Core";
        public const string SRAssemblyReportServerWeb = "DevExpress.ReportServer.v19.2.Web";
        public const string SRAssemblyReportServerDataAccess = "DevExpress.ReportServer.v19.2.DataAccess";
        public const string SRAssemblyReportsCodeCompletion = "DevExpress.XtraReports.v19.2.CodeCompletion";
        public const string SRAssemblyReportsCodeCompletionTests = "DevExpress.XtraReports.v19.2.CodeCompletion.Tests";
        public const string SRAssemblyRichEdit = "DevExpress.XtraRichEdit.v19.2";
        public const string SRAssemblyRichEditDesign = "DevExpress.XtraRichEdit.v19.2.Design";
        public const string SRAssemblyRichEditDesignFull = "DevExpress.XtraRichEdit.v19.2.Design, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblyRichEditExtensions = "DevExpress.XtraRichEdit.v19.2.Extensions";
        public const string SRAssemblyRichEditExport = "DevExpress.RichEdit.v19.2.Export";
        public const string SRAssemblySpreadsheet = "DevExpress.XtraSpreadsheet.v19.2";
        public const string SRAssemblySpreadsheetDesign = "DevExpress.XtraSpreadsheet.v19.2.Design";
        public const string SRAssemblyScheduler = "DevExpress.XtraScheduler.v19.2";
        public const string SRAssemblySchedulerDesign = "DevExpress.XtraScheduler.v19.2.Design";
        public const string SRAssemblySchedulerDesignFull = "DevExpress.XtraScheduler.v19.2.Design, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblySchedulerWeb = "DevExpress.Web.ASPxScheduler.v19.2";
        public const string SRAssemblySchedulerAspNetCore = "DevExpress.AspNetCore.Scheduler.Core.v19.2";
        public const string SRAssemblySchedulerWebDesign = "DevExpress.Web.ASPxScheduler.v19.2.Design";
        public const string SRAssemblySchedulerWebDesignFull = "DevExpress.Web.ASPxScheduler.v19.2.Design, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblySchedulerExtensions = "DevExpress.XtraScheduler.v19.2.Extensions";
        public const string SRAssemblySchedulerSynchronizationGoogle = "DevExpress.XtraScheduler.v19.2.GoogleCalendar";
        public const string SRAssemblySchedulerReporting = "DevExpress.XtraScheduler.v19.2.Reporting";
        public const string SRAssemblySchedulerReportingTests = "DevExpress.XtraScheduler.Reporting.Tests";
        public const string SRAssemblySchedulerReportingExtensions = "DevExpress.XtraScheduler.v19.2.Reporting.Extensions";
        public const string SRAssemblyChartsCore = "DevExpress.Charts.v19.2.Core";
        public const string SRAssemblySparklineCore = "DevExpress.Sparkline.v19.2.Core";
        public const string SRAssemblyCharts = "DevExpress.XtraCharts.v19.2";
        public const string SRAssemblyChartsExtensions = "DevExpress.XtraCharts.v19.2.Extensions";
        public const string SRAssemblyChartsWizard = "DevExpress.XtraCharts.v19.2.Wizard, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblyChartsDesign = "DevExpress.XtraCharts.v19.2.Design";
        public const string SRAssemblyChartsWebDesign = "DevExpress.XtraCharts.v19.2.Web.Design, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblyChartsUI = "DevExpress.XtraCharts.v19.2.UI";
        public const string SRAssemblyChartsWeb = "DevExpress.XtraCharts.v19.2.Web";
        public const string SRAssemblyWizard = "DevExpress.XtraWizard.v19.2";
        public const string SRAssemblyWizardDesign = "DevExpress.XtraWizard.v19.2.Design";
        public const string SRAssemblyXpo = "DevExpress.Xpo.v19.2";
        public const string SRAssemblyXpoUI = "DevExpress.Xpo.v19.2.UI";
        public const string SRAssemblyXpoUIFull = "DevExpress.Xpo.v19.2.UI, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblyXpoDesign = "DevExpress.Xpo.v19.2.Design";
        public const string SRAssemblyXpoDesignFull = "DevExpress.Xpo.v19.2.Design, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblyLayoutControl = "DevExpress.XtraLayout.v19.2";
        public const string SRAssemblyLayoutControlFull = "DevExpress.XtraLayout.v19.2, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblyLayoutControlDesign = "DevExpress.XtraLayout.v19.2.Design";
        public const string SRAssemblyLayoutControlDesignFull = "DevExpress.XtraLayout.v19.2.Design, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblySpellCheckerCore = "DevExpress.SpellChecker.v19.2.Core";
        public const string SRAssemblySpellChecker = "DevExpress.XtraSpellChecker.v19.2";
        public const string SRAssemblySpellCheckerDesign = "DevExpress.XtraSpellChecker.v19.2.Design";
        public const string SRAssemblySpellCheckerDesignFull = "DevExpress.XtraSpellChecker.v19.2.Design, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblySpellCheckerWeb = "DevExpress.Web.ASPxSpellChecker.v19.2";
        public const string SRAssemblySpellCheckerWebTests = "DevExpress.Web.ASPxSpellChecker.v19.2.Tests";
        public const string SRAssemblyWeb = "DevExpress.Web.v19.2";
        public const string SRAssemblyWebDesign = "DevExpress.Web.v19.2.Design";
        public const string SRAssemblyWebTests = "DevExpress.Web.v19.2.Tests";
        public const string SRAssemblyWebDemoData = "DevExpress.Web.DemoData.v19.2";
        public const string SRAssemblyWebDemoDataTests = "DevExpress.Web.DemoData.v19.2.Tests";
        public const string SRAssemblyWebDesignFull = "DevExpress.Web.v19.2.Design, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblyWebDesignTests = "DevExpress.Web.v19.2.Design.Tests";
        public const string SRAssemblyWebLinq = "DevExpress.Web.v19.2.Linq";
        public const string SRAssemblyANCSpreadsheet = "DevExpress.AspNetCore.Spreadsheet.v19.2";
        public const string SRAssemblyWebSpreadsheet = "DevExpress.Web.ASPxSpreadsheet.v19.2";
        public const string SRAssemblyWebSpreadsheetFull = "DevExpress.Web.ASPxSpreadsheet.v19.2, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblyWebSpreadsheetTests = "DevExpress.Web.ASPxSpreadsheet.v19.2.Tests";
        public const string SRAssemblyWebRichEdit = "DevExpress.Web.ASPxRichEdit.v19.2";
        public const string SRAssemblyWebRichEditFull = "DevExpress.Web.ASPxRichEdit.v19.2, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblyWebRichEditTests = "DevExpress.Web.ASPxRichEdit.v19.2.Tests";
        public const string SRAssemblyHtmlEditorWeb = "DevExpress.Web.ASPxHtmlEditor.v19.2";
        public const string SRAssemblyWebHtmlEditorTests = "DevExpress.Web.ASPxHtmlEditor.v19.2.Tests";
        public const string SRAssemblyEditorsWeb = "DevExpress.Web.ASPxEditors.v19.2";
        public const string SRAssemblyTreeListWeb = "DevExpress.Web.ASPxTreeList.v19.2";
        public const string SRAssemblyDiagramWeb = "DevExpress.Web.ASPxDiagram.v19.2";
        public const string SRAssemblyDiagramWebTests = "DevExpress.Web.ASPxDiagram.v19.2.Tests";
        public const string SRAssemblyGanttWeb = "DevExpress.Web.ASPxGantt.v19.2";
        public const string SRAssemblyGanttWebTests = "DevExpress.Web.ASPxGantt.v19.2.Tests";
        public const string SRAssemblyTreeListWebTests = "DevExpress.Web.ASPxTreeList.v19.2.Tests";
        public const string SRAssemblyDXPivotGrid = "DevExpress.Xpf.PivotGrid.v19.2";
        public const string SRAssemblyDXThemeEditorUIWithoutVSuffix = "DevExpress.Xpf.ThemeEditor";
        public const string SRAssemblyDXThemeEditorUI = "DevExpress.Xpf.ThemeEditor.v19.2";
        public const string SRAssemblySnap = "DevExpress.Snap.v19.2";
        public const string SRAssemblySnapCore = "DevExpress.Snap.v19.2.Core";
        public const string SRAssemblySnapExtensions = "DevExpress.Snap.v19.2.Extensions";
        public const string SRAssemblySnapDesign = "DevExpress.Snap.v19.2.Design";
        public const string SRAssemblySnapDesignFull = "DevExpress.Snap.v19.2.Design, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblyUtilsUI = "DevExpress.Utils.v19.2.UI";
        public const string SRAssemblyUtilsUIFull = "DevExpress.Utils.v19.2.UI, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblyDashboardCore = "DevExpress.Dashboard.v19.2.Core";
        public const string SRAssemblyDashboardWin = "DevExpress.Dashboard.v19.2.Win";
        public const string SRAssemblyDashboardWinFull = "DevExpress.Dashboard.v19.2.Win, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblyDashboardXpf = "DevExpress.Xpf.Dashboard.v19.2";
        public const string SRAssemblyDashboardWpf = "DevExpress.Dashboard.v19.2.Wpf";
        public const string SRAssemblyDashboardWeb = "DevExpress.Dashboard.v19.2.Web";
        public const string SRAssemblyDashboardWebWebForms = "DevExpress.Dashboard.v19.2.Web.WebForms";
        public const string SRAssemblyDashboardWebWebFormsTests = "DevExpress.Dashboard.v19.2.Web.WebForms.Tests";
        public const string SRAssemblyDashboardWebMVC = "DevExpress.Dashboard.v19.2.Web.Mvc";
        public const string SRAssemblyDashboardWebMVC5 = "DevExpress.Dashboard.v19.2.Web.Mvc5";
        public const string SRAssemblyDashboardAspNetCore = "DevExpress.Dashboard.v19.2.AspNetCore";
        public const string SRAssemblyDashboardAspNetCoreTests = "DevExpress.Dashboard.v19.2.AspNetCore.Tests";
        public const string SRAssemblyDashboardAspNetCore3Tests = "DevExpress.Dashboard.v19.2.AspNetCore3.Tests";
        public const string SRAssemblyDashboardWpfDesign = "DevExpress.Dashboard.v19.2.Wpf.Design";
        public const string SRAssemblyDashboardWinDesign = "DevExpress.Dashboard.v19.2.Win.Design";
        public const string SRAssemblyDashboardWinDesignFull = "DevExpress.Dashboard.v19.2.Win.Design, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblyDashboardWebDesign = "DevExpress.Dashboard.v19.2.Web.Design";
        public const string SRAssemblyDashboardWebDesignFull = "DevExpress.Dashboard.v19.2.Web.Design, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblyMapCore = "DevExpress.Map.v19.2.Core";
        public const string SRAssemblyMapCoreTests = "DevExpress.Map.Core.Tests";
        public const string SRAssemblyMap = "DevExpress.XtraMap.v19.2";
        public const string SRAssemblyMapTests = "DevExpress.XtraMap.Tests";
        public const string SRAssemblyMapDesign = "DevExpress.XtraMap.v19.2.Design";
        public const string SRAssemblyMapDesignFull = "DevExpress.XtraMap.v19.2.Design, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblyTreeMapCore = "DevExpress.TreeMap.v19.2.Core";
        public const string SRAssemblyTreeMap = "DevExpress.XtraTreeMap.v19.2";
        public const string SRAssemblyTreeMapDesign = "DevExpress.XtraTreeMap.v19.2.Design, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblyDataAccess = "DevExpress.DataAccess.v19.2";
        public const string SRAssemblyDataAccessFull = "DevExpress.DataAccess.v19.2, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblyDataAccessUI = "DevExpress.DataAccess.v19.2.UI";
        public const string SRAssemblyDataAccessUIFull = "DevExpress.DataAccess.v19.2.UI, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblyDataAccessDesign = "DevExpress.DataAccess.v19.2.Design";
        public const string SRAssemblyDataAccessDesignFull = "DevExpress.DataAccess.v19.2.Design, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblyCodeParser = "DevExpress.CodeParser.v19.2";
        public const string SRAssemblyPdfCore = "DevExpress.Pdf.v19.2.Core";
        public const string SRAssemblyPdfDrawing = "DevExpress.Pdf.v19.2.Drawing";
        public const string SRAssemblyXtraPdfViewer = "DevExpress.XtraPdfViewer.v19.2";
        public const string SRAssemblyXtraPdfViewerDesign = "DevExpress.XtraPdfViewer.v19.2.Design";
        public const string SRAssemblyXtraPdfViewerDesignFull = "DevExpress.XtraPdfViewer.v19.2.Design, Version=19.2.9.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a";
        public const string SRAssemblySpreadsheetCoreTestsRangeCopy = "DevExpress.Spreadsheet.v19.2.Core.Tests.RangeCopy";
        public const string SRAssemblySpreadsheetCoreTestsNotification = "DevExpress.Spreadsheet.v19.2.Core.Tests.Notification";
        public const string SRAssemblySpreadsheetCoreTestsFunctions = "DevExpress.Spreadsheet.v19.2.Core.Tests.Functions";
        public const string SRNuGetPackageVersion = "19.2.9.0-eap";
        public const string DXTabNameComponents = "Components";
        public const string DXTabNameNavigationAndLayout = "Navigation & Layout";
        public const string DXTabNameOrmComponents = "ORM Components";
        public const string DXTabNameReporting = "Reporting";
        public const string DXTabNameReportControls = "Report Controls";
        public const string DXTabNameDataUwp = "Data";
        public const string DXTabNameDashboardItems = "Dashboard Items";
        public const string DXTabNameData = "Data & Analytics";
        public const string DXTabNameVisualization = "Visualization";
        public const string DXTabNameScheduling = "Scheduling";
        public const string DXTabNameSchedulerReporting = "Scheduler Reporting";
        public const string DXTabNameRichEdit = "Rich Text Editor";
        public const string DXTabNameSpreadsheet = "Spreadsheet";
        public const string DXTabNameCommon = "Common Controls";
        public const string DXTabNameBootstrap = "Bootstrap Controls";
        public const string DXTabNameLayoutContainers = "Layout Containers";
        public const string DXTabNameLayoutControl = "Layout Control";
        public const string DXTabPrefix = "DX.19.2: ";
        public const string DXTabFree = "DX.19.2: Free";
        public const string DXTabComponents = "DX.19.2: Components";
        public const string DXTabNavigation = "DX.19.2: Navigation & Layout";
        public const string DXTabLayoutControl = "DX.19.2: Layout Control";
        public const string DXTabLayoutContainers = "DX.19.2: Layout Containers";
        public const string DXTabReporting = "DX.19.2: Reporting";
        public const string DXTabReportControls = "DX.19.2: Report Controls";
        public const string DXTabDataUwp = "DX.19.2: Data";
        public const string DXTabDashboardItems = "DX.19.2: Dashboard Items";
        public const string DXTabData = "DX.19.2: Data & Analytics";
        public const string DXTabVisualization = "DX.19.2: Visualization";
        public const string DXTabOrmComponents = "DX.19.2: ORM Components";
        public const string DXTabScheduling = "DX.19.2: Scheduling";
        public const string DXTabSchedulerReporting = "DX.19.2: Scheduler Reporting";
        public const string DXTabRichEdit = "DX.19.2: Rich Text Editor";
        public const string DXTabSpreadsheet = "DX.19.2: Spreadsheet";
        public const string DXTabCommon = "DX.19.2: Common Controls";
        public const string DXTabBootstrap = "DX.19.2: Bootstrap Controls";
        public const string DXTabNameXPOProfiler = "XPO 19.2 Profiler";
        public const string DXTabWpfNavigation = "DX.19.2: Navigation & Layout";
        public const string DXTabWpfReporting = "DX.19.2: Reporting";
        public const string DXTabWpfData = "DX.19.2: Data";
        public const string DXTabWpfVisualization = "DX.19.2: Visualization";
        public const string DXTabWpfCommon = "DX.19.2: Common Controls";
        public const string DXTabWpfScheduling = "DX.19.2: Scheduling";
        public const string DXTabWpfSchedulingOld = "DX.19.2: Scheduling (old)";
        public const string DXTabWpfRichEdit = "DX.19.2: Rich Text Editor";
        public const string DXTabWpfSpreadsheet = "DX.19.2: Spreadsheet";
        public const string DXLinkCompetitiveDiscounts = "https://go.devexpress.com/Demo_2013_Competitive_Discounts.aspx";
        public const string DXLinkCompare = "https://go.devexpress.com/Demo_2013_CompareSubscriptions.aspx";
        public const string DXLinkTrial = "https://go.devexpress.com/Demo_2013_DownloadTrial.aspx";
        public const string DXLinkChat = "Https://go.devexpress.com/Demo_2013_Chat.aspx";
        public const string DXLinkHelp = "Https://go.devexpress.com/Demo_2013_Help.aspx";
        public const string DXLinkBuyNow = "Https://go.devexpress.com/Demo_2013_BuyNow.aspx";
        public const string DXLinkBuyNowASP = "https://go.devexpress.com/Demo_2013_BuyNow_ASP.aspx";
        public const string DXLinkWhatsNew = "Https://go.devexpress.com/Demo_2013_13_2_WhatsNew.aspx";
        public const string DXLinkGetSupport = "Https://go.devexpress.com/Demo_2013_GetSupport.aspx";
        public const string DXLinkGetStarted = "Https://go.devexpress.com/Demo_2013_GetStartedOverall.aspx";
        public const string DXLinkRegisterKB = "https://go.devexpress.com/Demo_2013_RegisterTrial.aspx";
        public const string DXLinkGetStartedWinGrid = "https://go.devexpress.com/Demo_2013_GetStartedWinGrid.aspx";
        public const string DXEmailInfo = "info@devexpress.com";
        public const string DXLinkEmailInfo = "mailto:info@devexpress.com";
    }
}

