namespace DevExpress.Xpf.Bars.Native
{
    using System;

    public enum WinEventConstants
    {
        public const WinEventConstants EVENT_AIA_START = WinEventConstants.EVENT_AIA_START;,
        public const WinEventConstants EVENT_AIA_END = WinEventConstants.EVENT_AIA_END;,
        public const WinEventConstants EVENT_MIN = WinEventConstants.EVENT_MIN;,
        public const WinEventConstants EVENT_MAX = WinEventConstants.EVENT_MAX;,
        public const WinEventConstants EVENT_OBJECT_ACCELERATORCHANGE = WinEventConstants.EVENT_OBJECT_ACCELERATORCHANGE;,
        public const WinEventConstants EVENT_OBJECT_CLOAKED = WinEventConstants.EVENT_OBJECT_CLOAKED;,
        public const WinEventConstants EVENT_OBJECT_CONTENTSCROLLED = WinEventConstants.EVENT_OBJECT_CONTENTSCROLLED;,
        public const WinEventConstants EVENT_OBJECT_CREATE = WinEventConstants.EVENT_OBJECT_CREATE;,
        public const WinEventConstants EVENT_OBJECT_DEFACTIONCHANGE = WinEventConstants.EVENT_OBJECT_DEFACTIONCHANGE;,
        public const WinEventConstants EVENT_OBJECT_DESCRIPTIONCHANGE = WinEventConstants.EVENT_OBJECT_DESCRIPTIONCHANGE;,
        public const WinEventConstants EVENT_OBJECT_DESTROY = WinEventConstants.EVENT_OBJECT_DESTROY;,
        public const WinEventConstants EVENT_OBJECT_DRAGSTART = WinEventConstants.EVENT_OBJECT_DRAGSTART;,
        public const WinEventConstants EVENT_OBJECT_DRAGCANCEL = WinEventConstants.EVENT_OBJECT_DRAGCANCEL;,
        public const WinEventConstants EVENT_OBJECT_DRAGCOMPLETE = WinEventConstants.EVENT_OBJECT_DRAGCOMPLETE;,
        public const WinEventConstants EVENT_OBJECT_DRAGENTER = WinEventConstants.EVENT_OBJECT_DRAGENTER;,
        public const WinEventConstants EVENT_OBJECT_DRAGLEAVE = WinEventConstants.EVENT_OBJECT_DRAGLEAVE;,
        public const WinEventConstants EVENT_OBJECT_DRAGDROPPED = WinEventConstants.EVENT_OBJECT_DRAGDROPPED;,
        public const WinEventConstants EVENT_OBJECT_END = WinEventConstants.EVENT_OBJECT_END;,
        public const WinEventConstants EVENT_OBJECT_FOCUS = WinEventConstants.EVENT_OBJECT_FOCUS;,
        public const WinEventConstants EVENT_OBJECT_HELPCHANGE = WinEventConstants.EVENT_OBJECT_HELPCHANGE;,
        public const WinEventConstants EVENT_OBJECT_HIDE = WinEventConstants.EVENT_OBJECT_HIDE;,
        public const WinEventConstants EVENT_OBJECT_HOSTEDOBJECTSINVALIDATED = WinEventConstants.EVENT_OBJECT_HOSTEDOBJECTSINVALIDATED;,
        public const WinEventConstants EVENT_OBJECT_IME_HIDE = WinEventConstants.EVENT_OBJECT_IME_HIDE;,
        public const WinEventConstants EVENT_OBJECT_IME_SHOW = WinEventConstants.EVENT_OBJECT_IME_SHOW;,
        public const WinEventConstants EVENT_OBJECT_IME_CHANGE = WinEventConstants.EVENT_OBJECT_IME_CHANGE;,
        public const WinEventConstants EVENT_OBJECT_INVOKED = WinEventConstants.EVENT_OBJECT_INVOKED;,
        public const WinEventConstants EVENT_OBJECT_LIVEREGIONCHANGED = WinEventConstants.EVENT_OBJECT_LIVEREGIONCHANGED;,
        public const WinEventConstants EVENT_OBJECT_LOCATIONCHANGE = WinEventConstants.EVENT_OBJECT_LOCATIONCHANGE;,
        public const WinEventConstants EVENT_OBJECT_NAMECHANGE = WinEventConstants.EVENT_OBJECT_NAMECHANGE;,
        public const WinEventConstants EVENT_OBJECT_PARENTCHANGE = WinEventConstants.EVENT_OBJECT_PARENTCHANGE;,
        public const WinEventConstants EVENT_OBJECT_REORDER = WinEventConstants.EVENT_OBJECT_REORDER;,
        public const WinEventConstants EVENT_OBJECT_SELECTION = WinEventConstants.EVENT_OBJECT_SELECTION;,
        public const WinEventConstants EVENT_OBJECT_SELECTIONADD = WinEventConstants.EVENT_OBJECT_SELECTIONADD;,
        public const WinEventConstants EVENT_OBJECT_SELECTIONREMOVE = WinEventConstants.EVENT_OBJECT_SELECTIONREMOVE;,
        public const WinEventConstants EVENT_OBJECT_SELECTIONWITHIN = WinEventConstants.EVENT_OBJECT_SELECTIONWITHIN;,
        public const WinEventConstants EVENT_OBJECT_SHOW = WinEventConstants.EVENT_OBJECT_SHOW;,
        public const WinEventConstants EVENT_OBJECT_STATECHANGE = WinEventConstants.EVENT_OBJECT_STATECHANGE;,
        public const WinEventConstants EVENT_OBJECT_TEXTEDIT_CONVERSIONTARGETCHANGED = WinEventConstants.EVENT_OBJECT_TEXTEDIT_CONVERSIONTARGETCHANGED;,
        public const WinEventConstants EVENT_OBJECT_TEXTSELECTIONCHANGED = WinEventConstants.EVENT_OBJECT_TEXTSELECTIONCHANGED;,
        public const WinEventConstants EVENT_OBJECT_UNCLOAKED = WinEventConstants.EVENT_OBJECT_UNCLOAKED;,
        public const WinEventConstants EVENT_OBJECT_VALUECHANGE = WinEventConstants.EVENT_OBJECT_VALUECHANGE;,
        public const WinEventConstants EVENT_OEM_DEFINED_START = WinEventConstants.EVENT_OEM_DEFINED_START;,
        public const WinEventConstants EVENT_OEM_DEFINED_END = WinEventConstants.EVENT_OEM_DEFINED_END;,
        public const WinEventConstants EVENT_SYSTEM_ALERT = WinEventConstants.EVENT_SYSTEM_ALERT;,
        public const WinEventConstants EVENT_SYSTEM_ARRANGMENTPREVIEW = WinEventConstants.EVENT_SYSTEM_ARRANGMENTPREVIEW;,
        public const WinEventConstants EVENT_SYSTEM_CAPTUREEND = WinEventConstants.EVENT_SYSTEM_CAPTUREEND;,
        public const WinEventConstants EVENT_SYSTEM_CAPTURESTART = WinEventConstants.EVENT_SYSTEM_CAPTURESTART;,
        public const WinEventConstants EVENT_SYSTEM_CONTEXTHELPEND = WinEventConstants.EVENT_SYSTEM_CONTEXTHELPEND;,
        public const WinEventConstants EVENT_SYSTEM_CONTEXTHELPSTART = WinEventConstants.EVENT_SYSTEM_CONTEXTHELPSTART;,
        public const WinEventConstants EVENT_SYSTEM_DESKTOPSWITCH = WinEventConstants.EVENT_SYSTEM_DESKTOPSWITCH;,
        public const WinEventConstants EVENT_SYSTEM_DIALOGEND = WinEventConstants.EVENT_SYSTEM_DIALOGEND;,
        public const WinEventConstants EVENT_SYSTEM_DIALOGSTART = WinEventConstants.EVENT_SYSTEM_DIALOGSTART;,
        public const WinEventConstants EVENT_SYSTEM_DRAGDROPEND = WinEventConstants.EVENT_SYSTEM_DRAGDROPEND;,
        public const WinEventConstants EVENT_SYSTEM_DRAGDROPSTART = WinEventConstants.EVENT_SYSTEM_DRAGDROPSTART;,
        public const WinEventConstants EVENT_SYSTEM_END = WinEventConstants.EVENT_SYSTEM_END;,
        public const WinEventConstants EVENT_SYSTEM_FOREGROUND = WinEventConstants.EVENT_SYSTEM_FOREGROUND;,
        public const WinEventConstants EVENT_SYSTEM_MENUPOPUPEND = WinEventConstants.EVENT_SYSTEM_MENUPOPUPEND;,
        public const WinEventConstants EVENT_SYSTEM_MENUPOPUPSTART = WinEventConstants.EVENT_SYSTEM_MENUPOPUPSTART;,
        public const WinEventConstants EVENT_SYSTEM_MENUEND = WinEventConstants.EVENT_SYSTEM_MENUEND;,
        public const WinEventConstants EVENT_SYSTEM_MENUSTART = WinEventConstants.EVENT_SYSTEM_MENUSTART;,
        public const WinEventConstants EVENT_SYSTEM_MINIMIZEEND = WinEventConstants.EVENT_SYSTEM_MINIMIZEEND;,
        public const WinEventConstants EVENT_SYSTEM_MINIMIZESTART = WinEventConstants.EVENT_SYSTEM_MINIMIZESTART;,
        public const WinEventConstants EVENT_SYSTEM_MOVESIZEEND = WinEventConstants.EVENT_SYSTEM_MOVESIZEEND;,
        public const WinEventConstants EVENT_SYSTEM_MOVESIZESTART = WinEventConstants.EVENT_SYSTEM_MOVESIZESTART;,
        public const WinEventConstants EVENT_SYSTEM_SCROLLINGEND = WinEventConstants.EVENT_SYSTEM_SCROLLINGEND;,
        public const WinEventConstants EVENT_SYSTEM_SCROLLINGSTART = WinEventConstants.EVENT_SYSTEM_SCROLLINGSTART;,
        public const WinEventConstants EVENT_SYSTEM_SOUND = WinEventConstants.EVENT_MIN;,
        public const WinEventConstants EVENT_SYSTEM_SWITCHEND = WinEventConstants.EVENT_SYSTEM_SWITCHEND;,
        public const WinEventConstants EVENT_SYSTEM_SWITCHSTART = WinEventConstants.EVENT_SYSTEM_SWITCHSTART;,
        public const WinEventConstants EVENT_UIA_EVENTID_START = WinEventConstants.EVENT_UIA_EVENTID_START;,
        public const WinEventConstants EVENT_UIA_EVENTID_END = WinEventConstants.EVENT_UIA_EVENTID_END;,
        public const WinEventConstants EVENT_UIA_PROPID_START = WinEventConstants.EVENT_UIA_PROPID_START;,
        public const WinEventConstants EVENT_UIA_PROPID_END = WinEventConstants.EVENT_UIA_PROPID_END;
    }
}

