namespace DevExpress.Xpf.Bars.Themes
{
    using System;

    public enum BarSplitButtonItemThemeKeys
    {
        public const BarSplitButtonItemThemeKeys Template = BarSplitButtonItemThemeKeys.Template;,
        public const BarSplitButtonItemThemeKeys InMenuTemplate = BarSplitButtonItemThemeKeys.InMenuTemplate;,
        public const BarSplitButtonItemThemeKeys InMenuHorizontalTemplate = BarSplitButtonItemThemeKeys.InMenuHorizontalTemplate;,
        public const BarSplitButtonItemThemeKeys InPageGroupTemplate = BarSplitButtonItemThemeKeys.InPageGroupTemplate;,
        public const BarSplitButtonItemThemeKeys InRibbonPageHeaderTemplate = BarSplitButtonItemThemeKeys.InRibbonPageHeaderTemplate;,
        public const BarSplitButtonItemThemeKeys InRibbonQuickAccessToolbarFooterTemplate = BarSplitButtonItemThemeKeys.InRibbonQuickAccessToolbarFooterTemplate;,
        public const BarSplitButtonItemThemeKeys ArrowLayoutPanelStyle = BarSplitButtonItemThemeKeys.ArrowLayoutPanelStyle;,
        public const BarSplitButtonItemThemeKeys ArrowLayoutPanelStyleInMainMenu = BarSplitButtonItemThemeKeys.ArrowLayoutPanelStyleInMainMenu;,
        public const BarSplitButtonItemThemeKeys ArrowLayoutPanelStyleInStatusBar = BarSplitButtonItemThemeKeys.ArrowLayoutPanelStyleInStatusBar;,
        public const BarSplitButtonItemThemeKeys ArrowLayoutPanelStyleInRibbonToolbar = BarSplitButtonItemThemeKeys.ArrowLayoutPanelStyleInRibbonToolbar;,
        public const BarSplitButtonItemThemeKeys ArrowLayoutPanelStyleInRibbonStatusBarLeft = BarSplitButtonItemThemeKeys.ArrowLayoutPanelStyleInRibbonStatusBarLeft;,
        public const BarSplitButtonItemThemeKeys ArrowLayoutPanelStyleInRibbonStatusBarRight = BarSplitButtonItemThemeKeys.ArrowLayoutPanelStyleInRibbonStatusBarRight;,
        public const BarSplitButtonItemThemeKeys ArrowLayoutPanelStyleInRibbonPageGroup = BarSplitButtonItemThemeKeys.ArrowLayoutPanelStyleInRibbonPageGroup;,
        public const BarSplitButtonItemThemeKeys ArrowLayoutPanelStyleInBarButtonGroup = BarSplitButtonItemThemeKeys.ArrowLayoutPanelStyleInBarButtonGroup;,
        public const BarSplitButtonItemThemeKeys ArrowStyle = BarSplitButtonItemThemeKeys.ArrowStyle;,
        public const BarSplitButtonItemThemeKeys ArrowTemplate = BarSplitButtonItemThemeKeys.ArrowTemplate;,
        public const BarSplitButtonItemThemeKeys ArrowStyleInMenu = BarSplitButtonItemThemeKeys.ArrowStyleInMenu;,
        public const BarSplitButtonItemThemeKeys ArrowTemplateInMenu = BarSplitButtonItemThemeKeys.ArrowTemplateInMenu;,
        public const BarSplitButtonItemThemeKeys ArrowStyleInMainMenu = BarSplitButtonItemThemeKeys.ArrowStyleInMainMenu;,
        public const BarSplitButtonItemThemeKeys ArrowTemplateInMainMenu = BarSplitButtonItemThemeKeys.ArrowTemplateInMainMenu;,
        public const BarSplitButtonItemThemeKeys ArrowStyleInStatusBar = BarSplitButtonItemThemeKeys.ArrowStyleInStatusBar;,
        public const BarSplitButtonItemThemeKeys ArrowTemplateInStatusBar = BarSplitButtonItemThemeKeys.ArrowTemplateInStatusBar;,
        public const BarSplitButtonItemThemeKeys ArrowStyleInRibbonQuickAccessToolbarFooter = BarSplitButtonItemThemeKeys.ArrowStyleInRibbonQuickAccessToolbarFooter;,
        public const BarSplitButtonItemThemeKeys ArrowTemplateInRibbonQuickAccessToolbarFooter = BarSplitButtonItemThemeKeys.ArrowTemplateInRibbonQuickAccessToolbarFooter;,
        public const BarSplitButtonItemThemeKeys ArrowStyleInRibbonStatusBarLeft = BarSplitButtonItemThemeKeys.ArrowStyleInRibbonStatusBarLeft;,
        public const BarSplitButtonItemThemeKeys ArrowTemplateInRibbonStatusBarLeft = BarSplitButtonItemThemeKeys.ArrowTemplateInRibbonStatusBarLeft;,
        public const BarSplitButtonItemThemeKeys ArrowStyleInRibbonStatusBarRight = BarSplitButtonItemThemeKeys.ArrowStyleInRibbonStatusBarRight;,
        public const BarSplitButtonItemThemeKeys ArrowTemplateInRibbonStatusBarRight = BarSplitButtonItemThemeKeys.ArrowTemplateInRibbonStatusBarRight;,
        public const BarSplitButtonItemThemeKeys ArrowStyleInRibbonPageGroup = BarSplitButtonItemThemeKeys.ArrowStyleInRibbonPageGroup;,
        public const BarSplitButtonItemThemeKeys ArrowTemplateInRibbonPageGroup = BarSplitButtonItemThemeKeys.ArrowTemplateInRibbonPageGroup;,
        public const BarSplitButtonItemThemeKeys ArrowStyleInRibbonPageHeader = BarSplitButtonItemThemeKeys.ArrowStyleInRibbonPageHeader;,
        public const BarSplitButtonItemThemeKeys ArrowTemplateInRibbonPageHeader = BarSplitButtonItemThemeKeys.ArrowTemplateInRibbonPageHeader;,
        public const BarSplitButtonItemThemeKeys ArrowStyleInRibbonQuickAccessToolbar = BarSplitButtonItemThemeKeys.ArrowStyleInRibbonQuickAccessToolbar;,
        public const BarSplitButtonItemThemeKeys ArrowTemplateInRibbonQuickAccessToolbar = BarSplitButtonItemThemeKeys.ArrowTemplateInRibbonQuickAccessToolbar;,
        public const BarSplitButtonItemThemeKeys ArrowStyleInBarButtonGroup = BarSplitButtonItemThemeKeys.ArrowStyleInBarButtonGroup;,
        public const BarSplitButtonItemThemeKeys ArrowTemplateInBarButtonGroup = BarSplitButtonItemThemeKeys.ArrowTemplateInBarButtonGroup;,
        public const BarSplitButtonItemThemeKeys ContentBorderTemplateInRibbonPageGroup = BarSplitButtonItemThemeKeys.ContentBorderTemplateInRibbonPageGroup;,
        public const BarSplitButtonItemThemeKeys ArrowBorderTemplateInRibbonPageGroup = BarSplitButtonItemThemeKeys.ArrowBorderTemplateInRibbonPageGroup;,
        public const BarSplitButtonItemThemeKeys LargeContentBorderTemplateInRibbonPageGroup = BarSplitButtonItemThemeKeys.LargeContentBorderTemplateInRibbonPageGroup;,
        public const BarSplitButtonItemThemeKeys LargeArrowBorderTemplateInRibbonPageGroup = BarSplitButtonItemThemeKeys.LargeArrowBorderTemplateInRibbonPageGroup;,
        public const BarSplitButtonItemThemeKeys LargeArrowBorderStyleInRibbonPageGroup = BarSplitButtonItemThemeKeys.LargeArrowBorderStyleInRibbonPageGroup;,
        public const BarSplitButtonItemThemeKeys LargeContentBorderStyleInRibbonPageGroup = BarSplitButtonItemThemeKeys.LargeContentBorderStyleInRibbonPageGroup;,
        public const BarSplitButtonItemThemeKeys TextSplitterStyleInRibbonPageGroup = BarSplitButtonItemThemeKeys.TextSplitterStyleInRibbonPageGroup;,
        public const BarSplitButtonItemThemeKeys NormalArrowTemplateInTextSplitter = BarSplitButtonItemThemeKeys.NormalArrowTemplateInTextSplitter;,
        public const BarSplitButtonItemThemeKeys SelectedArrowTemplateInTextSplitter = BarSplitButtonItemThemeKeys.SelectedArrowTemplateInTextSplitter;,
        public const BarSplitButtonItemThemeKeys SelectedTextStyleInTextSplitter = BarSplitButtonItemThemeKeys.SelectedTextStyleInTextSplitter;,
        public const BarSplitButtonItemThemeKeys NormalTextStyleInTextSplitter = BarSplitButtonItemThemeKeys.NormalTextStyleInTextSplitter;,
        public const BarSplitButtonItemThemeKeys BottomSideArrowContainerStyleInTextSplitter = BarSplitButtonItemThemeKeys.BottomSideArrowContainerStyleInTextSplitter;,
        public const BarSplitButtonItemThemeKeys RightSideArrowContainerStyleInTextSplitter = BarSplitButtonItemThemeKeys.RightSideArrowContainerStyleInTextSplitter;,
        public const BarSplitButtonItemThemeKeys ControlTemplateInRadialMenu = BarSplitButtonItemThemeKeys.ControlTemplateInRadialMenu;
    }
}

