namespace DevExpress.DirectX.NativeInterop
{
    using DevExpress.DirectX.Common;
    using DevExpress.DirectX.Common.Direct2D;
    using DevExpress.DirectX.Common.Direct3D;
    using DevExpress.DirectX.Common.DirectWrite;
    using DevExpress.DirectX.Common.WIC;
    using DevExpress.DirectX.NativeInterop.Direct2D;
    using System;
    using System.Runtime.InteropServices;

    [CLSCompliant(false)]
    public interface IInvokeHelper
    {
        void Calli(IntPtr param0, int param1);
        void Calli(IntPtr param0, D2D_POINT_2F param1, int param2);
        void Calli(IntPtr param0, int param1, int param2);
        void Calli(IntPtr param0, IntPtr param1, int param2);
        void Calli(IntPtr param0, ref D2D_MATRIX_3X2_F param1, int param2);
        void Calli(IntPtr param0, float param1, int param2);
        void Calli(IntPtr param0, ref D2D_RECT_F param1, int param2);
        void Calli(IntPtr param0, out D2D_SIZE_U param1, int param2);
        void Calli(IntPtr param0, ref D2D1_BEZIER_SEGMENT param1, int param2);
        void Calli(IntPtr param0, ref D2D1_COLOR_F param1, int param2);
        void Calli(IntPtr param0, out D2D1_PIXEL_FORMAT param1, int param2);
        void Calli(IntPtr param0, ref D3D11_TEXTURE2D_DESC param1, int param2);
        void Calli(IntPtr param0, out DWRITE_FONT_METRICS param1, int param2);
        void Calli(IntPtr param0, out IntPtr param1, int param2);
        void Calli(IntPtr param0, IntPtr param1, int param2, int param3);
        void Calli(IntPtr param0, ref D2D_RECT_F param1, int param2, int param3);
        void Calli(IntPtr param0, D2D_POINT_2F param1, int param2, int param3);
        void Calli(IntPtr param0, ref D2D_POINT_2F param1, int param2, int param3);
        void Calli(IntPtr param0, ref D2D_RECT_F param1, IntPtr param2, int param3);
        void Calli(IntPtr param0, ref D2D1_BEZIER_SEGMENT param1, int param2, int param3);
        void Calli(IntPtr param0, IntPtr param1, IntPtr param2, int param3);
        void Calli(IntPtr param0, ref D2D1_ELLIPSE param1, IntPtr param2, int param3);
        void Calli(IntPtr param0, ref D2D1_ROUNDED_RECT param1, IntPtr param2, int param3);
        void Calli(IntPtr param0, ref D2D1_LAYER_PARAMETERS param1, IntPtr param2, int param3);
        void Calli(IntPtr param0, int param1, out IntPtr param2, int param3);
        void Calli(IntPtr param0, ref D2D1_LAYER_PARAMETERS1 param1, IntPtr param2, int param3);
        void Calli(IntPtr param0, IntPtr param1, ref D2D_POINT_2F param2, int param3);
        void Calli(IntPtr param0, float param1, float param2, int param3);
        void Calli(IntPtr param0, out float param1, out float param2, int param3);
        void Calli(IntPtr param0, int param1, IntPtr param2, int param3, int param4);
        void Calli(IntPtr param0, IntPtr param1, IntPtr param2, IntPtr param3, int param4);
        void Calli(IntPtr param0, D2D_POINT_2F param1, ref DWRITE_GLYPH_RUN_COMMON param2, IntPtr param3, int param4, int param5);
        void Calli(IntPtr param0, ref D2D_RECT_F param1, IntPtr param2, float param3, IntPtr param4, int param5);
        void Calli(IntPtr param0, ref D2D1_ELLIPSE param1, IntPtr param2, float param3, IntPtr param4, int param5);
        void Calli(IntPtr param0, ref D2D1_ROUNDED_RECT param1, IntPtr param2, float param3, IntPtr param4, int param5);
        void Calli(IntPtr param0, IntPtr param1, IntPtr param2, float param3, IntPtr param4, int param5);
        void Calli(IntPtr param0, IntPtr param1, IntPtr param2, ref D2D_RECT_F param3, ref D2D_RECT_F param4, int param5);
        void Calli(IntPtr param0, D2D_POINT_2F param1, D2D_POINT_2F param2, IntPtr param3, float param4, IntPtr param5, int param6);
        void Calli(IntPtr param0, IntPtr param1, ref D2D_POINT_2F param2, ref D2D_RECT_F param3, int param4, int param5, int param6);
        void Calli(IntPtr param0, IntPtr param1, ref D2D_POINT_2F param2, IntPtr param3, int param4, int param5, int param6);
        void Calli(IntPtr param0, IntPtr param1, ref D2D_RECT_F param2, float param3, int param4, ref D2D_RECT_F param5, int param6);
        void Calli(IntPtr param0, IntPtr param1, ref D2D_RECT_F param2, float param3, int param4, IntPtr param5, int param6);
        void Calli(IntPtr param0, IntPtr param1, ref D2D_RECT_F param2, float param3, int param4, ref D2D_RECT_F param5, IntPtr param6, int param7);
        void Calli(IntPtr param0, IntPtr param1, ref D2D_RECT_F param2, float param3, int param4, IntPtr param5, IntPtr param6, int param7);
        int CalliInt(IntPtr param0, int param1);
        int CalliInt(IntPtr param0, int param1, int param2);
        int CalliInt(IntPtr param0, IntPtr param1, int param2);
        int CalliInt(IntPtr param0, ref D2D1_RENDER_TARGET_PROPERTIES param1, int param2);
        int CalliInt(IntPtr param0, ref RECT param1, int param2);
        int CalliInt(IntPtr param0, out int param1, int param2);
        int CalliInt(IntPtr param0, out IntPtr param1, int param2);
        int CalliInt(IntPtr param0, ref D2D_MATRIX_3X2_F param1, ref D2D_RECT_F param2, int param3);
        int CalliInt(IntPtr param0, int param1, ref D2D1_MAPPED_RECT param2, int param3);
        int CalliInt(IntPtr param0, int param1, out int param2, int param3);
        int CalliInt(IntPtr param0, ref D2D_RECT_F param1, out IntPtr param2, int param3);
        int CalliInt(IntPtr param0, out long param1, out long param2, int param3);
        int CalliInt(IntPtr param0, int param1, out IntPtr param2, int param3);
        int CalliInt(IntPtr param0, int param1, int param2, int param3);
        int CalliInt(IntPtr param0, ref D2D_SIZE_F param1, out IntPtr param2, int param3);
        int CalliInt(IntPtr param0, ref D2D1_RENDER_TARGET_PROPERTIES param1, out IntPtr param2, int param3);
        int CalliInt(IntPtr param0, out IntPtr param1, int param2, int param3);
        int CalliInt(IntPtr param0, int param1, IntPtr param2, int param3);
        int CalliInt(IntPtr param0, IntPtr param1, ref D2D_RECT_F param2, int param3);
        int CalliInt(IntPtr param0, IntPtr param1, int param2, int param3);
        int CalliInt(IntPtr param0, IntPtr param1, ref RECT param2, int param3);
        int CalliInt(IntPtr param0, IntPtr param1, out IntPtr param2, int param3);
        int CalliInt(IntPtr param0, int param1, out IntPtr param2, out int param3, int param4);
        int CalliInt(IntPtr param0, int param1, int param2, short param3, int param4);
        int CalliInt(IntPtr param0, int param1, int param2, int param3, int param4);
        int CalliInt(IntPtr param0, int param1, IntPtr param2, int param3, int param4);
        int CalliInt(IntPtr param0, int param1, IntPtr param2, out int param3, int param4);
        int CalliInt(IntPtr param0, IntPtr param1, int param2, int param3, int param4);
        int CalliInt(IntPtr param0, IntPtr param1, int param2, ref D2D_RECT_F param3, int param4);
        int CalliInt(IntPtr param0, IntPtr param1, ref D2D_MATRIX_3X2_F param2, out IntPtr param3, int param4);
        int CalliInt(IntPtr param0, IntPtr param1, ref D2D_RECT_F param2, int param3, int param4);
        int CalliInt(IntPtr param0, IntPtr param1, ref D2D1_BITMAP_PROPERTIES param2, out IntPtr param3, int param4);
        int CalliInt(IntPtr param0, ref D2D_MATRIX_3X2_F param1, float param2, IntPtr param3, int param4);
        int CalliInt(IntPtr param0, ref D2D_MATRIX_3X2_F param1, float param2, float param3, int param4);
        int CalliInt(IntPtr param0, ref D2D_POINT_2U param1, IntPtr param2, ref D2D_RECT_U param3, int param4);
        int CalliInt(IntPtr param0, ref D2D_RECT_U param1, IntPtr param2, int param3, int param4);
        int CalliInt(IntPtr param0, IntPtr param1, ref D2D1_BITMAP_PROPERTIES1 param2, out IntPtr param3, int param4);
        int CalliInt(IntPtr param0, ref D2D1_COLOR_F param1, ref D2D1_BRUSH_PROPERTIES param2, out IntPtr param3, int param4);
        int CalliInt(IntPtr param0, long param1, int param2, IntPtr param3, int param4);
        int CalliInt(IntPtr param0, IntPtr param1, ref D2D1_RENDER_TARGET_PROPERTIES param2, out IntPtr param3, int param4);
        int CalliInt(IntPtr param0, IntPtr param1, out int param2, out int param3, int param4);
        int CalliInt(IntPtr param0, IntPtr param1, int param2, out IntPtr param3, int param4);
        int CalliInt(IntPtr param0, IntPtr param1, int param2, IntPtr param3, int param4);
        int CalliInt(IntPtr param0, IntPtr param1, IntPtr param2, out IntPtr param3, int param4);
        int CalliInt(IntPtr param0, IntPtr param1, IntPtr param2, int param3, int param4);
        int CalliInt(IntPtr param0, ref D2D_MATRIX_3X2_F param1, float param2, out float param3, int param4);
        int CalliInt(IntPtr param0, ref D3D11_TEXTURE2D_DESC param1, IntPtr param2, out IntPtr param3, int param4);
        int CalliInt(IntPtr param0, ref WICRect param1, int param2, int param3, IntPtr param4, int param5);
        int CalliInt(IntPtr param0, D2D_POINT_2F param1, ref DWRITE_GLYPH_RUN_COMMON param2, int param3, out D2D_RECT_F param4, int param5);
        int CalliInt(IntPtr param0, int param1, int param2, int param3, out IntPtr param4, int param5);
        int CalliInt(IntPtr param0, int param1, int param2, IntPtr param3, int param4, int param5);
        int CalliInt(IntPtr param0, int param1, ref D2D_MATRIX_3X2_F param2, float param3, IntPtr param4, int param5);
        int CalliInt(IntPtr param0, IntPtr param1, int param2, int param3, int param4, int param5);
        int CalliInt(IntPtr param0, IntPtr param1, ref D2D1_IMAGE_BRUSH_PROPERTIES param2, ref D2D1_BRUSH_PROPERTIES param3, out IntPtr param4, int param5);
        int CalliInt(IntPtr param0, IntPtr param1, int param2, IntPtr param3, out IntPtr param4, int param5);
        int CalliInt(IntPtr param0, IntPtr param1, IntPtr param2, int param3, int param4, int param5);
        int CalliInt(IntPtr param0, IntPtr param1, IntPtr param2, int param3, out IntPtr param4, int param5);
        int CalliInt(IntPtr param0, IntPtr param1, ref D2D_MATRIX_3X2_F param2, float param3, int param4, int param5);
        int CalliInt(IntPtr param0, IntPtr param1, ref D2D1_BITMAP_BRUSH_PROPERTIES1 param2, ref D2D1_BRUSH_PROPERTIES param3, out IntPtr param4, int param5);
        int CalliInt(IntPtr param0, IntPtr param1, int param2, int param3, IntPtr param4, int param5);
        int CalliInt(IntPtr param0, ref D2D1_STROKE_STYLE_PROPERTIES1 param1, IntPtr param2, int param3, out IntPtr param4, int param5);
        int CalliInt(IntPtr param0, IntPtr param1, IntPtr param2, IntPtr param3, IntPtr param4, int param5);
        int CalliInt(IntPtr param0, ref D2D1_LINEAR_GRADIENT_BRUSH_PROPERTIES param1, ref D2D1_BRUSH_PROPERTIES param2, IntPtr param3, out IntPtr param4, int param5);
        int CalliInt(IntPtr param0, IntPtr param1, int param2, IntPtr param3, int param4, int param5);
        int CalliInt(IntPtr param0, ref D2D1_VERTEX_BUFFER_PROPERTIES param1, IntPtr param2, ref D2D1_CUSTOM_VERTEX_BUFFER_PROPERTIES param3, out IntPtr param4, int param5);
        int CalliInt(IntPtr param0, IntPtr param1, IntPtr param2, ref D2D1_PRINT_CONTROL_PROPERTIES param3, out IntPtr param4, int param5);
        int CalliInt(IntPtr param0, ref D2D1_RADIAL_GRADIENT_BRUSH_PROPERTIES param1, ref D2D1_BRUSH_PROPERTIES param2, IntPtr param3, out IntPtr param4, int param5);
        int CalliInt(IntPtr param0, D2D_SIZE_U param1, IntPtr param2, int param3, ref D2D1_BITMAP_PROPERTIES param4, out IntPtr param5, int param6);
        int CalliInt(IntPtr param0, D2D_SIZE_U param1, IntPtr param2, int param3, ref D2D1_BITMAP_PROPERTIES1 param4, out IntPtr param5, int param6);
        int CalliInt(IntPtr param0, IntPtr param1, D2D_SIZE_F param2, IntPtr param3, IntPtr param4, IntPtr param5, int param6);
        int CalliInt(IntPtr param0, IntPtr param1, int param2, int param3, int param4, ref D3D11_MAPPED_SUBRESOURCE param5, int param6);
        int CalliInt(IntPtr param0, IntPtr param1, int param2, int param3, int param4, out IntPtr param5, int param6);
        int CalliInt(IntPtr param0, IntPtr param1, int param2, ref D2D_MATRIX_3X2_F param3, float param4, IntPtr param5, int param6);
        int CalliInt(IntPtr param0, IntPtr param1, int param2, IntPtr param3, ref D2D1_VERTEX_RANGE param4, IntPtr param5, int param6);
        int CalliInt(IntPtr param0, IntPtr param1, IntPtr param2, IntPtr param3, int param4, IntPtr param5, int param6);
        int CalliInt(IntPtr param0, IntPtr param1, IntPtr param2, IntPtr param3, IntPtr param4, out IntPtr param5, int param6);
        int CalliInt(IntPtr param0, float param1, IntPtr param2, ref D2D_MATRIX_3X2_F param3, float param4, ref D2D_RECT_F param5, int param6);
        int CalliInt(IntPtr param0, float param1, float param2, int param3, IntPtr param4, int param5, int param6);
        int CalliInt(IntPtr param0, float param1, ref D2D_MATRIX_3X2_F param2, float param3, out D2D_POINT_2F param4, out D2D_POINT_2F param5, int param6);
        int CalliInt(IntPtr param0, float param1, IntPtr param2, ref D2D_MATRIX_3X2_F param3, float param4, IntPtr param5, int param6);
        int CalliInt(IntPtr param0, int param1, int param2, IntPtr param3, int param4, int param5, out IntPtr param6, int param7);
        int CalliInt(IntPtr param0, IntPtr param1, IntPtr param2, int param3, IntPtr param4, double param5, int param6, int param7);
        int CalliInt(IntPtr param0, IntPtr param1, ref D2D1_RESOURCE_TEXTURE_PROPERTIES_COMMON param2, IntPtr param3, IntPtr param4, int param5, out IntPtr param6, int param7);
        int CalliInt(IntPtr param0, float param1, IntPtr param2, IntPtr param3, IntPtr param4, int param5, int param6, int param7, IntPtr param8, int param9);
        IntPtr CalliIntPtr(IntPtr param0, int param1);
    }
}

